"""
test_emit_schema_pin — design-time gate pinning the cockpit-contract
emission surface named by CLAUDE.md § Architecture as a hard external
dependency: `contract.cockpit_schema.emit_schema` is the sole canonical
regeneration path for coordinator-claude's frozen `coordinator/cockpit-contract/schema/
*.json`. Relocating or renaming the module/symbol, changing the
`out_dir`/`COCKPIT_SCHEMA_OUT_DIR` resolution contract, or changing the
emitted bytes for a fixed input destroys coordinator-claude's release capability and trips
their bilateral version-bump gate (see CLAUDE.md § Architecture, this repo
root).

This is a CLOSED design-time gate in the house idiom of
`coordinator_core/frontmatter/tests/test_no_node_schema_shellout.py` /
`test_no_bare_argv0_script_launch.py`: it does not ask "does the schema
still validate" (a shape-level question `test_committed_emit_drift.py`
already owns, and which is @skip_no_schema-gated on a coordinator-claude clone being
present on this machine). It asks "are the EXACT bytes this port promises
to keep stable actually stable" — unconditionally, with no coordinator-claude-clone
dependency, so it always runs.

Three properties pinned, matching the brief's three failure classes:
  1. module path / symbol name — `build_emit_schemas_callable` below fails
     loud (ImportError re-raised with a pointed message) if
     `coordinator_core.contract.cockpit_schema.emit_schema.emit_schemas`
     moves or is renamed.
  2. `out_dir` resolution contract — explicit `out_dir=` beats
     `COCKPIT_SCHEMA_OUT_DIR` beats the `<repo-root>/schema` default
     (`_schema_out_dir`'s own precedence chain).
  3. emitted bytes for a fixed input — a minimal, structurally-frozen
     `PinFixtureEntity` run through `emit_schemas()` with `CONTRACT_VERSION`
     monkeypatched to a fixed literal (so a routine, legitimate
     CONTRACT_VERSION bump — this module has taken a dozen of them, see its
     own docstring history — never trips this gate; only a SHAPE change
     does), compared byte-for-byte against a checked-in golden fixture.

Golden-fixture design decision: `fixtures/pin_fixture_entity.schema.json` is
a COMMITTED artifact, not derived at test time. Deriving it at test time
(e.g. calling `emit_schemas()` once to produce the "expected" bytes, then
calling it again to compare) would make the assertion tautological — it
would only ever compare the emitter's output to itself, and could never
fail no matter how the emission shape drifted, since both sides move
together. Pinning requires an independent, frozen reference; a golden that
is itself regenerated by the code under test cannot serve as one. The
golden's OWN drift risk (a contributor "fixing" a failing test by
regenerating it) is exactly the failure mode CLAUDE.md's dependency note
warns against, which is why the failure message below spells out that the
correct response to a red run is a heads-up to claude-central-em, not a
golden refresh.

Spec backlink: CLAUDE.md § Architecture (`contract.cockpit_schema.emit_schema`
hard external dependency note).
"""
from __future__ import annotations

import importlib
import json
from pathlib import Path
from typing import Optional

import pytest
from pydantic import BaseModel, Field

_HEADS_UP = (
    "cockpit-contract emission is a hard external dependency (CLAUDE.md "
    "§ Architecture): coordinator-claude's coordinator/cockpit-contract/schema/*.json "
    "is byte-frozen from this module's output, and downstream tooling "
    "hard-throws on a MAJOR version mismatch. DO NOT regenerate the golden "
    "fixture or otherwise silence this failure locally -- give "
    "claude-central-em a heads-up first so the bilateral version-bump gate "
    "is negotiated before anything ships."
)

_FIXTURES_DIR = Path(__file__).parent / "fixtures"
_PIN_GOLDEN = _FIXTURES_DIR / "pin_fixture_entity.schema.json"

_EXPECTED_MODULE = "coordinator_core.contract.cockpit_schema.emit_schema"
_EXPECTED_SYMBOL = "emit_schemas"
_EXPECTED_ENV_VAR = "COCKPIT_SCHEMA_OUT_DIR"


class PinFixtureEntity(BaseModel):
    """A minimal, structurally-frozen entity used ONLY to pin
    emit_schema's byte-level output shape -- never registered in
    ENTITY_SCHEMAS, never touched by any real cockpit-contract consumer.
    Do not extend/edit this class; it exists to stay fixed forever so its
    golden fixture stays fixed forever."""

    name: str = Field(description="entity name")
    count: int
    note: Optional[str] = None


def _import_emit_schema_module():
    try:
        return importlib.import_module(_EXPECTED_MODULE)
    except ImportError as exc:  # pragma: no cover - exercised only on drift
        raise AssertionError(
            f"{_EXPECTED_MODULE} could not be imported -- the module has "
            f"moved or been renamed. {_HEADS_UP}"
        ) from exc


def test_emit_schemas_symbol_is_stable_at_its_documented_location():
    module = _import_emit_schema_module()
    assert hasattr(module, _EXPECTED_SYMBOL), (
        f"{_EXPECTED_MODULE}.{_EXPECTED_SYMBOL} no longer exists -- the "
        f"canonical emission symbol has moved or been renamed. {_HEADS_UP}"
    )
    assert callable(getattr(module, _EXPECTED_SYMBOL))


def test_out_dir_resolution_precedence_explicit_arg_beats_env_beats_default(
    tmp_path, monkeypatch
):
    from coordinator_core.contract.cockpit_schema.emit_schema import _schema_out_dir

    explicit_dir = tmp_path / "explicit"
    env_dir = tmp_path / "from-env"
    monkeypatch.setenv(_EXPECTED_ENV_VAR, str(env_dir))

    assert _schema_out_dir(explicit_dir) == explicit_dir.resolve(), (
        "an explicit out_dir= argument must win over "
        f"{_EXPECTED_ENV_VAR} -- resolution precedence changed. {_HEADS_UP}"
    )

    monkeypatch.delenv(_EXPECTED_ENV_VAR, raising=False)
    monkeypatch.setenv(_EXPECTED_ENV_VAR, str(env_dir))
    assert _schema_out_dir(None) == env_dir.resolve(), (
        f"the {_EXPECTED_ENV_VAR} environment-variable override no longer "
        f"takes effect when out_dir= is omitted. {_HEADS_UP}"
    )

    monkeypatch.delenv(_EXPECTED_ENV_VAR, raising=False)
    repo_root = Path(__file__).resolve().parents[3]
    assert _schema_out_dir(None) == (repo_root / "schema").resolve(), (
        "the no-argument, no-env-var default out_dir no longer resolves to "
        f"<repo-root>/schema. {_HEADS_UP}"
    )


def test_emitted_bytes_are_pinned_for_a_fixed_input(tmp_path, monkeypatch):
    from coordinator_core.contract.cockpit_schema import emit_schema as es

    monkeypatch.setattr(es, "CONTRACT_VERSION", "0.0.0-pin-fixture")

    out_dir = tmp_path / "pin-emit"
    es.emit_schemas({"pin-fixture-entity": PinFixtureEntity}, out_dir=out_dir)

    emitted_path = out_dir / "pin-fixture-entity.schema.json"
    assert emitted_path.exists(), (
        "emit_schemas no longer writes one <name>.schema.json per registry "
        f"entry using the entity-registry key as the filename stem. {_HEADS_UP}"
    )

    emitted_bytes = emitted_path.read_bytes()
    golden_bytes = _PIN_GOLDEN.read_bytes()

    assert emitted_bytes == golden_bytes, (
        "emit_schemas' emitted bytes for a fixed, frozen input entity have "
        "changed -- this is the exact class of change that would silently "
        "desync coordinator-claude's committed cockpit-contract/schema/*.json. "
        f"{_HEADS_UP}\n\n"
        f"golden:\n{golden_bytes.decode('utf-8')}\n\n"
        f"emitted:\n{emitted_bytes.decode('utf-8')}"
    )

    parsed = json.loads(emitted_bytes)
    assert parsed["version"] == "0.0.0-pin-fixture"


if __name__ == "__main__":
    raise SystemExit(pytest.main([__file__, "-v"]))
