"""
coordinator_core.py_probe_sh -- the ONE POSIX-sh Python-interpreter-probe
snippet, shared by every emitted git-hook that needs to resolve python3 /
python / py from inside a `#!/bin/sh` body.

Purpose (ORIGIN, three sites): three independent call sites each hand-rolled
the same `command -v python3 || command -v python || command -v py` probe into
an EMITTED shell hook body (`coordinator_core.ops.install_meta_repo_precommit_hook`,
`coordinator_core.ops.install_makima_precommit_hook`,
`coordinator.bin.lib.git_hook_install`). On Windows, PATH commonly resolves
those names first to Microsoft Store App Execution Alias stubs --
non-functional launchers -- so every one of those three probes would invoke
the stub instead of a real interpreter. `.cmd` launchers generated by
`gen-launcher-shim.py` already filter this (`findstr /I /C:"\\WindowsApps\\"`);
none of the three `sh`-emitted probes did, until 47c4c70b fixed the first of
the three (the meta-repo installer) and this module generalized that fix into
a shared primitive for the other two rather than a second and third hand-copy.

CURRENT CONSUMERS ARE THREE MODULES, FOUR CALL SITES -- NOT THE "THREE
INDEPENDENT call sites" the origin paragraph above names, and not the FOUR
this docstring itself asserted between 2026-08-2x and the C17 row of
`docs/plans/2026-08-21-the-cli-bootstrap-tax-dies-at-the-interpreter-floor.md`.
That earlier "four" count is now stale too: `coordinator_core.ops.
install_makima_precommit_hook` converted off this primitive at C17 -- git's
own hook-exec contract still forces a shell for its emitted trampoline, but
that trampoline now bakes `sys.executable` at install time (a real
filesystem path the running installer already resolved) instead of walking
`$PATH` in shell, so it no longer calls `python_probe_lines` at all. Today's
callers: `coordinator.bin.lib.git_hook_install` (two sites),
`coordinator_core.ops.install_meta_repo_precommit_hook`, and
`coordinator_core.ops.install_doe_claude_precommit_hook` (DoE-claude's own
hook -- another repo's surface, out of C17's scope; see that plan's C17 row
for why only the makima installer converts). Grep `python_probe_lines`
before quoting a count; this line drifts as consumers are added or removed
and is not a substitute for the grep.

`_is_store_python`-equivalent filtering is mirrored here (case-insensitive
`windowsapps` path-component check), not imported from
`coordinator_core.pyresolve` -- that module's `_is_store_python` runs
IN-PROCESS, on a candidate path a running Python interpreter already
resolved; this module has no process to run inside -- it emits TEXT that a
future `sh` process (git's hook runner) will interpret. The two mirror the
same defect class deliberately, per two disjoint consumer shapes -- see that
module's own docstring, "Two consumers".

Walking `$PATH` directory-by-directory per candidate name (rather than
rejecting a candidate NAME and falling through to the next name) is
load-bearing, and was established empirically (see 47c4c70b's commit
message), not by reasoning: on the realistic Windows topology the
WindowsApps stub and the real interpreter share a name (`python.exe`), so
"reject this name, try the next name" never reaches the real interpreter.
Directory-by-directory is also what the `.cmd` generator's own `where` loop
does. Do not regress to the simpler per-name-only shape.

Two emission shapes, one shared body:
    - `python_probe_lines(var)` -- newline-joined POSIX-sh source defining
      `_py_resolve()` and assigning `<var>="$(_py_resolve)"`. Used verbatim
      by both `_hook_body`-style standalone hooks (one call, own line) and
      spliced into a single-line `{ ...; }` append block (embedded newlines
      inside a semicolon-chained compound statement are valid POSIX sh --
      `sh` does not care whether a statement separator is `\\n` or `;`, and
      mixing the two within one script is unremarkable).

Not shared: the surrounding gate-execution / shim-body assembly machinery in
each of the three call sites. Each site's contract around WHAT runs after
python is resolved differs (gate registries with clamped exit codes vs. a
single target script with a self-heal fallback chain) -- see
`install_makima_precommit_hook`'s own module docstring, "Kept as an
independent module", for why that surrounding machinery stays independently
duplicated even though this one probe snippet does not. Sharing only the
probe (not the whole gate-block shape) does not reintroduce the coupling
that docstring warns against.

Bootstrap-safety: stdlib only, zero external calls, zero subprocess -- same
contract as `coordinator_core.win_portability`, which this module sits
alongside rather than inside (that module's own scope is Python-side
path/exec primitives operating on real filesystem paths; this module emits
shell TEXT for a process that has not started yet -- a different concern).
"""

from __future__ import annotations

__all__ = ["python_probe_lines"]


def python_probe_lines(var: str = "_py") -> str:
    """Return POSIX-sh source (one string, internally newline-joined)
    defining `_py_resolve()` and assigning `<var>="$(_py_resolve)"`.

    `_py_resolve()` walks $PATH directory-by-directory, in candidate order
    python3 -> python -> py, testing both the bare name and a `.exe`-suffixed
    form per directory (MSYS/git-bash resolves the extension via
    `command -v` but a manual `-x` file test does not), and skips any hit
    whose resolved path contains a `windowsapps` path component
    (case-insensitive). No-op filtering on POSIX, where that path component
    never appears.

    The case-insensitive match is a literal `case` bracket-expression glob,
    NOT a `tr`-based case-fold, and that is load-bearing rather than
    stylistic: the filter must resolve zero external binaries. A `$(... |
    tr ...)` fold fails OPEN -- when `tr` is off the hook's PATH the command
    substitution yields the empty string, the `case` matches nothing, and the
    stub is selected, which is the exact defect this filter exists to
    prevent. Observed, not reasoned: the `tr` form returned the WindowsApps
    stub under a PATH carrying only the stub. Every construct emitted here is
    a `sh` builtin or reserved word.

    Prints the first surviving candidate's absolute path and
    returns 0; returns 1 (empty `<var>`) if nothing survives -- callers must
    already handle an empty `<var>` (missing-interpreter branch), unchanged
    from the pre-fix probe's own empty-on-failure contract.
    """
    return "\n".join(
        [
            "_py_resolve() {",
            '  _py_oldifs="$IFS"',
            "  for _py_cand in python3 python py; do",
            "    IFS=:",
            "    for _py_dir in $PATH; do",
            '      IFS="$_py_oldifs"',
            '      [ -n "$_py_dir" ] || continue',
            '      for _py_exe in "$_py_dir/$_py_cand" "$_py_dir/$_py_cand.exe"; do',
            '        [ -x "$_py_exe" ] || continue',
            '        case "$_py_exe" in',
            "          */[Ww][Ii][Nn][Dd][Oo][Ww][Ss][Aa][Pp][Pp][Ss]/*) continue ;;",
            "        esac",
            "        printf '%s' \"$_py_exe\"",
            '        IFS="$_py_oldifs"',
            "        return 0",
            "      done",
            "    done",
            "    IFS=:",
            "  done",
            '  IFS="$_py_oldifs"',
            "  return 1",
            "}",
            f'{var}="$(_py_resolve)"',
        ]
    )
