"""coordinator_core.ops.compute_layer_scaffold.emit — the Sub-shape B module composer.

Purpose: composes the TEXT of a `<skill>_assemble` decision-object producer
skeleton from a caller-declared verb set. Emission is f-string concatenation
— the same shape as `coordinator_core.ops.workflow_scaffold::_compose_script`
— never a reusable template engine, and this module does NOT import
`workflow_scaffold`: the spike verified that module's emission is plain
concatenation, not shared machinery, so copying the shape is the intended
reuse (docs/research/spike-verdicts/2026-08-13-compute-layer-scaffolder-emits-conformant-producer.md).

The emitted module IMPORTS AND COMPOSES, never re-implements:
  - `coordinator_core.contract.decision_object.envelope.build_envelope`
  - `coordinator_core.contract.decision_object.envelope.extend_exit_codes`
  - `coordinator_core.contract.apply_base.execute_directives`

Negative-spec (AC4): the emitted exit ladder is always the explicit
`BUSINESS_FAIL=1, USAGE=2, TRANSPORT_FAIL=3` — `extend_exit_codes` anchors
ONLY `SUCCESS = 0` and RAISES on a caller-supplied `SUCCESS`
(`contract/decision_object/envelope.py::extend_exit_codes`); the emitted
`main()` therefore always returns `ExitCode.SUCCESS`, never `ExitCode.OK`
(the exact bug the spike's hand-written probe shipped, undetected by its own
generated test — see the spike verdict § finding 3).

Negative-spec (AC5): `_CLI_DISPATCH` is always emitted as a closed dict
literal over the module's own `CONSUMES_MANIFEST` — this emitter has no
code path producing `getattr`/`import_module` dispatch.

Negative-spec (AC12): this module writes TEXT only. It does not write to
disk, does not register the emitted module anywhere (no `authz/
classification.py`, no `ops/_registry_map.py`, no `bin/` trampoline) — that
is explicitly out of scope for this chunk (C4's surface).

Spec backlink: pln-the-compute-layer-scaffolder-e-90d036, chunk C1.
"""

from __future__ import annotations

import re
from typing import Sequence

_IDENT_SANITIZE_RE = re.compile(r"[^0-9A-Za-z_]")


class InvalidVerb(ValueError):
    pass


def _dispatch_fn_name(verb: str) -> str:
    if not verb:
        raise InvalidVerb("a manifest verb must be a non-empty string")
    sanitized = _IDENT_SANITIZE_RE.sub("_", verb)
    if not sanitized or sanitized.strip("_") == "":
        raise InvalidVerb(f"verb {verb!r} sanitizes to an empty identifier")
    return f"_dispatch_{sanitized}"


def _pascal_case(skill_name: str) -> str:
    parts = _IDENT_SANITIZE_RE.sub("_", skill_name).split("_")
    return "".join(part.capitalize() for part in parts if part)


def _py_str_literal(value: str) -> str:
    escaped = value.replace("\\", "\\\\").replace("'", "\\'").replace("\n", "\\n")
    return f"'{escaped}'"


def _docstring_safe(value: str) -> str:
    if "\x00" in value:
        raise ValueError("_docstring_safe: value must not contain a NUL byte")
    escaped = value.replace("\\", "\\\\")
    escaped = escaped.replace('"""', '\\"\\"\\"')
    escaped = escaped.replace("\r\n", "\\n")
    escaped = escaped.replace("\r", "\\n")
    escaped = escaped.replace("\n", "\\n")
    escaped = escaped.replace(" ", "\\u2028")
    escaped = escaped.replace(" ", "\\u2029")
    return escaped


def compose_producer_module(skill_name: str, verbs: Sequence[str]) -> str:
    """Composes the full TEXT of a Sub-shape B `<skill_name>_assemble`
    decision-object producer skeleton.

    Args:
        skill_name: the producer's skill identifier (e.g. "example_assemble"),
            used for the module docstring and the exit-code enum's class
            name.
        verbs: the declared `CONSUMES_MANIFEST` — one `_dispatch_<verb>`
            stub and one `_CLI_DISPATCH` entry is emitted per verb, in the
            order given. Raises `InvalidVerb` if a verb is empty or has no
            identifier-safe characters, and `ValueError` if `verbs` is
            empty (a producer with no consumable verbs has nothing for
            `apply()` to dispatch).

    Returns:
        The composed module TEXT (a `str`) — this function performs no
        file I/O and registers nothing; the caller decides whether/where
        to write it (AC12).
    """
    if not skill_name:
        raise ValueError("compose_producer_module requires a non-empty skill_name")
    if not verbs:
        raise ValueError("compose_producer_module requires at least one verb")

    verb_list = list(verbs)
    fn_names = [_dispatch_fn_name(v) for v in verb_list]
    exit_code_name = f"{_pascal_case(skill_name)}ExitCode"

    manifest_literal = ", ".join(_py_str_literal(v) for v in verb_list)
    if len(verb_list) == 1:
        manifest_literal += ","

    module_docstring = (
        f'"""{_docstring_safe(skill_name)} — generated Sub-shape B decision-object producer skeleton.\n\n'
        "Generated by coordinator_core.ops.compute_layer_scaffold.emit."
        "compose_producer_module. Composes rather than re-implements the\n"
        "shared envelope/exit-code/dispatch contract:\n"
        "coordinator_core.contract.decision_object.envelope.build_envelope,\n"
        "coordinator_core.contract.decision_object.envelope.extend_exit_codes,\n"
        "coordinator_core.contract.apply_base.execute_directives.\n\n"
        "Spec backlink: pln-the-compute-layer-scaffolder-e-90d036, chunk C1.\n"
        '"""\n'
    )

    header = (
        f"{module_docstring}\n"
        "from __future__ import annotations\n\n"
        "import json\n"
        "import sys\n"
        "from pathlib import Path\n"
        "from typing import Any, Callable\n\n"
        "from coordinator_core.contract.decision_object.envelope import (\n"
        "    build_envelope,\n"
        "    extend_exit_codes,\n"
        ")\n"
        "from coordinator_core.contract import apply_base\n"
    )

    manifest_block = (
        "\nCONSUMES_MANIFEST: tuple[str, ...] = ("
        f"{manifest_literal}"
        ")\n"
    )

    exit_code_block = (
        f"\n{exit_code_name} = extend_exit_codes(\n"
        f"    {_py_str_literal(exit_code_name)},\n"
        "    BUSINESS_FAIL=1,\n"
        "    USAGE=2,\n"
        "    TRANSPORT_FAIL=3,\n"
        ")\n"
    )

    dispatch_stubs = "\n".join(
        (
            f"\ndef {fn_name}(args: list[str], repo_root: Path) -> dict[str, Any]:\n"
            f'    """Generated stub for verb {_py_str_literal(verb)} — replace with a real handler."""\n'
            f"    raise NotImplementedError({_py_str_literal(f'{fn_name} is a generated stub')})\n"
        )
        for verb, fn_name in zip(verb_list, fn_names)
    )

    dispatch_table_entries = "\n".join(
        f"    {_py_str_literal(verb)}: {fn_name}," for verb, fn_name in zip(verb_list, fn_names)
    )
    dispatch_table_block = (
        "\n_CLI_DISPATCH: dict[str, Callable[[list[str], Path], dict[str, Any]]] = {\n"
        f"{dispatch_table_entries}\n"
        "}\n"
    )

    brief_block = (
        "\n\ndef brief(**kwargs: Any) -> dict[str, Any]:\n"
        '    """Composes an 8-key decision-object envelope via build_envelope."""\n'
        "    return build_envelope(**kwargs)\n"
    )

    apply_block = (
        "\n\ndef apply(\n"
        "    directives: list[dict[str, Any]],\n"
        "    judgment_points: list[dict[str, Any]],\n"
        "    repo_root: Path,\n"
        "    **kwargs: Any,\n"
        ") -> tuple[int, dict[str, Any]]:\n"
        '    """Delegates to apply_base.execute_directives over the closed _CLI_DISPATCH table."""\n'
        "    return apply_base.execute_directives(\n"
        "        directives, judgment_points, repo_root, _CLI_DISPATCH, **kwargs\n"
        "    )\n"
    )

    usage_block = (
        "\n\ndef _usage() -> int:\n"
        '    """Prints the generated CLI\'s usage line to stderr, returns USAGE."""\n'
        "    print(\n"
        f"        {_py_str_literal(f'usage: {skill_name} [brief|apply]')},\n"
        "        file=sys.stderr,\n"
        "    )\n"
        f"    return int({exit_code_name}.USAGE)\n"
    )

    main_block = (
        "\n\ndef main(argv: list[str]) -> int:\n"
        '    """Generated CLI entrypoint: dispatches "brief"/"apply", else USAGE."""\n'
        "    if not argv:\n"
        "        return _usage()\n"
        "    verb = argv[0]\n"
        "    if verb == 'brief':\n"
        "        print(json.dumps(brief(), indent=2, sort_keys=True))\n"
        f"        return int({exit_code_name}.SUCCESS)\n"
        "    if verb == 'apply':\n"
        "        exit_code, _report = apply([], [], Path.cwd())\n"
        "        if exit_code == apply_base.APPLY_EXIT_OK:\n"
        f"            return int({exit_code_name}.SUCCESS)\n"
        f"        return int({exit_code_name}.BUSINESS_FAIL)\n"
        "    return _usage()\n"
    )

    dunder_main_block = (
        "\n\nif __name__ == '__main__':\n"
        "    sys.exit(main(sys.argv[1:]))\n"
    )

    return (
        header
        + manifest_block
        + exit_code_block
        + dispatch_stubs
        + dispatch_table_block
        + brief_block
        + apply_block
        + usage_block
        + main_block
        + dunder_main_block
    )
