"""
coordinator_core.execute_plan_assemble.tests.test_close_out_goal_refusal —
coverage for the C2 goal-falsifier stamp-decision gate (`_evaluate_goal_
falsifier_gate` and its wiring into `close_out_and_stamp`).

Spec backlink: docs/plans/2026-08-27-the-close-ceremony-refuses-a-goal-
nothing-observed.md § C2 (AC4-AC8, AC18-AC20). See close_out_and_stamp.py's
own "§ The goal-falsifier stamp-decision gate" comment block for the design
this pins.

AC7's differential-fixture guarantee (`TestGrandfatheredCorpusIsUnaffected`
below) is the highest-value assertion in this file: a plan sampled from the
REAL corpus that never declared `prime_exit_criterion` must produce a
`close_out_and_stamp(..., dry_run=True)` result dict byte-identical to the
pre-C2 implementation's own result for the SAME plan. The fixture
(`fixtures/close_out_dry_run_pre_change.json`) was generated by loading the
pre-change module straight out of `git show HEAD:coordinator_core/
execute_plan_assemble/close_out_and_stamp.py` (the version on disk before
this chunk's own edits landed) and running it, `dry_run=True`, against three
real, terminal (`status: implemented`), pre-existing plans in this repo's
own `docs/plans/` corpus -- never a synthetic fixture plan authored for this
test. Regenerating it (only ever warranted if `close_out_and_stamp`'s own
PRE-C2 behaviour changes, which nothing in this chunk should do) is the same
recipe: check out the pre-change module text, load it via
`importlib.util.spec_from_file_location`, call `close_out_and_stamp(plan,
repo_root=repo_root, dry_run=True)` per sampled plan, and serialize
`{"exit_code": ..., "result": ...}` per plan path into that JSON file.
"""
from __future__ import annotations

import json
import subprocess
from pathlib import Path
from typing import Optional

import pytest
import yaml

import coordinator_core.execute_plan_assemble.close_out_and_stamp as coas
from coordinator_core.frontmatter.primitives import canonical_body_sha
from coordinator_core.win_portability import no_console_creationflags

pytestmark = [pytest.mark.cadence, pytest.mark.spawns_process]

_REPO_ROOT = Path(__file__).resolve().parents[3]
_FIXTURE_PATH = Path(__file__).resolve().parent / "fixtures" / "close_out_dry_run_pre_change.json"


# ---------------------------------------------------------------------------
# Git/repo test-isolation helpers (mirrors test_close_out_and_stamp.py's own)
# ---------------------------------------------------------------------------


def _run_git(args: list[str], cwd: Path) -> subprocess.CompletedProcess:
    return subprocess.run(
        ["git", *args], cwd=str(cwd), capture_output=True, text=True, check=True, **no_console_creationflags()
    )


def _init_repo(root: Path) -> None:
    _run_git(["init", "-q"], root)
    _run_git(["config", "user.email", "t@t"], root)
    _run_git(["config", "user.name", "test"], root)


def _head_sha(root: Path) -> str:
    return _run_git(["rev-parse", "HEAD"], root).stdout.strip()


def _run_close_out(
    monkeypatch: pytest.MonkeyPatch, root: Path, plan_rel: str, *, dry_run: bool = False
) -> tuple[int, dict]:
    monkeypatch.chdir(root)
    return coas.close_out_and_stamp(plan_rel, repo_root=root, dry_run=dry_run)


_PLAN_TEMPLATE = """---
title: "Fixture plan — goal-falsifier gate"
created: 2026-08-27
author: test-fixture
status: {status}
branch: "work/test-fixture/2026-08-27"
plan_id: "pln-fixture-goal-gate-000001"
deliverable_id: "dlv-fixture-goal-gate-000001"
{goal_frontmatter}---

# Fixture plan — goal-falsifier gate

## Tasks

```yaml plan-tasks
{rows}
```
"""


def _prime_exit_criterion_block(
    *,
    derived_from: str = "state/sizings/2026-08-27-fixture-sizing.yaml",
    baseline_ref: str,
    exit_criterion_met: Optional[str],
    status_override: Optional[str] = None,
) -> str:
    """Renders the `prime_exit_criterion:`/`exit_criterion_met:` frontmatter
    block this file's fixture plans embed. `exit_criterion_met` is a raw
    YAML block (pre-indented) or `None` to omit the field entirely (arm 2's
    absent case). `status_override`, when given, is a raw YAML block for
    the `status_override_*` trio (AC19)."""
    lines = [
        "prime_exit_criterion:",
        "  statement: The fixture surface behaves as claimed.",
        f"  derived_from: {derived_from}",
        "  falsifier:",
        "    how: read the fixture surface",
        "    baseline_output: 'wrong'",
        f"    baseline_ref: {baseline_ref}",
        "    expected_when_true: 'right'",
    ]
    if exit_criterion_met is not None:
        lines.append("exit_criterion_met:")
        lines.append(exit_criterion_met)
    if status_override is not None:
        lines.append(status_override)
    return "\n".join(lines) + "\n"


_SHIPPED_ROW = (
    "- id: C1\n"
    "  title: Only chunk\n"
    "  change_kind: code-edit\n"
    "  surface: fixture.py\n"
    "  deferred: false\n"
    "  disposition: coded\n"
    "  disposition_ref: {sha}\n"
    "  disposition_detail: 'landed'\n"
    "  body: |\n"
    "    The only chunk.\n"
)


def _seed_goal_plan(
    root: Path,
    *,
    goal_frontmatter: str,
    shipping_sha: str,
    status: str = "executing",
    dest_name: str = "plan.md",
) -> Path:
    text = _PLAN_TEMPLATE.format(
        status=status,
        goal_frontmatter=goal_frontmatter,
        rows=_SHIPPED_ROW.format(sha=shipping_sha),
    )
    dest = root / dest_name
    dest.write_text(text, encoding="utf-8")
    _run_git(["add", dest_name], root)
    # The default `derived_from` every `_prime_exit_criterion_block` call
    # points at (`state/sizings/2026-08-27-fixture-sizing.yaml`) must
    # resolve for tests that are not themselves exercising arm 5's own
    # unresolvable case -- seeded here so every OTHER test in this file
    # never trips arm 5 by accident.
    sizing_rel = "state/sizings/2026-08-27-fixture-sizing.yaml"
    sizing_path = root / sizing_rel
    if not sizing_path.is_file():
        sizing_path.parent.mkdir(parents=True, exist_ok=True)
        sizing_path.write_text("estimate:\n  tshirt: S\n", encoding="utf-8")
        _run_git(["add", sizing_rel], root)
    _run_git(["commit", "-q", "-m", "seed"], root)
    return dest


def _land_the_shipping_chunk(root: Path) -> str:
    """Lands a real commit this repo's own history can verify as an
    ancestor of `HEAD` -- the sha every fixture plan's `disposition_ref`
    (spine evidence) AND, in the passing-baseline case, `falsifier.
    baseline_ref` both point at."""
    (root / "fixture.py").write_text("v1", encoding="utf-8")
    _run_git(["add", "fixture.py"], root)
    _run_git(["commit", "-q", "-m", "land the only chunk"], root)
    return _head_sha(root)


def _make_non_ancestor_commit(root: Path) -> str:
    head_tree = _run_git(["rev-parse", "HEAD^{tree}"], root).stdout.strip()
    result = _run_git(
        ["commit-tree", head_tree, "-m", "unreachable commit"], root
    )
    return result.stdout.strip()


def _asserted_pass_block() -> str:
    return (
        "  asserted: true\n"
        "  falsifier_output: 'right'\n"
        "  falsifier_verdict: pass\n"
        "  prose: matches the stated pass condition\n"
    )


def _asserted_false_block() -> str:
    return "  asserted: false\n  reason: the surface was removed by the work\n"


def _asserted_true_verdict_fail_block() -> str:
    return (
        "  asserted: true\n"
        "  falsifier_output: 'still wrong'\n"
        "  falsifier_verdict: fail\n"
    )


def _status_override_block(body_sha: str, *, current: bool = True) -> str:
    reason = (
        f"body_sha={body_sha}: surface deleted by the work, cannot re-observe"
        if current
        else "body_sha=0000000000000000000000000000000000000000: stale override"
    )
    return (
        "status_override_by: test-override-session\n"
        f"status_override_reason: '{reason}'\n"
        "status_override_at: '2026-08-27T00:00:00Z'\n"
    )


# ===========================================================================
# Unit coverage -- pure helpers, no git needed
# ===========================================================================


class TestFalsifierBlockDetectionIsTotal:
    """AC7: absent, null, non-object, structurally incomplete, and
    unparseable falsifier shapes ALL route to `None` (arm 1) and none of
    them raises."""

    def test_prime_exit_criterion_not_a_dict(self):
        assert coas._falsifier_block("not a dict") is None
        assert coas._falsifier_block(None) is None
        assert coas._falsifier_block([1, 2, 3]) is None

    def test_falsifier_absent(self):
        assert coas._falsifier_block({"statement": "x", "derived_from": "y"}) is None

    def test_falsifier_null(self):
        assert coas._falsifier_block({"falsifier": None}) is None

    def test_falsifier_non_object(self):
        assert coas._falsifier_block({"falsifier": "a bare string"}) is None

    def test_falsifier_structurally_incomplete(self):
        assert (
            coas._falsifier_block(
                {"falsifier": {"how": "x", "baseline_output": "y"}}
            )
            is None
        )

    def test_falsifier_blank_required_field(self):
        assert (
            coas._falsifier_block(
                {
                    "falsifier": {
                        "how": "x",
                        "baseline_output": "y",
                        "baseline_ref": "   ",
                        "expected_when_true": "z",
                    }
                }
            )
            is None
        )

    def test_falsifier_complete_returns_the_block(self):
        falsifier = {
            "how": "x",
            "baseline_output": "y",
            "baseline_ref": "deadbeef",
            "expected_when_true": "z",
        }
        assert coas._falsifier_block({"falsifier": falsifier}) == falsifier


class TestStatusOverrideBinding:
    def _plan_text(self, body: str, extra_fm: str = "") -> str:
        return f"---\ntitle: t\n{extra_fm}---\n{body}"

    def test_absent_fields_return_none(self):
        text = self._plan_text("body text\n")
        assert coas._read_status_override(text) is None

    def test_missing_one_of_three_fields_returns_none(self):
        text = self._plan_text(
            "body text\n",
            "status_override_by: sid\nstatus_override_at: '2026-08-27T00:00:00Z'\n",
        )
        assert coas._read_status_override(text) is None

    def test_bound_to_a_stale_hash_returns_none(self):
        body = "body text\n"
        text = self._plan_text(body, "")
        text = self._plan_text(
            body,
            "status_override_by: sid\n"
            "status_override_reason: 'body_sha=0000000000000000000000000000000000000000: stale'\n"
            "status_override_at: '2026-08-27T00:00:00Z'\n",
        )
        assert coas._read_status_override(text) is None

    def test_bound_to_the_current_body_hash_verifies(self):
        body = "body text\n"
        provisional = self._plan_text(body, "")
        current_sha = canonical_body_sha(provisional)
        text = self._plan_text(
            body,
            "status_override_by: sid\n"
            f"status_override_reason: 'body_sha={current_sha}: legitimately unreproducible'\n"
            "status_override_at: '2026-08-27T00:00:00Z'\n",
        )
        override = coas._read_status_override(text)
        assert override is not None
        assert override["body_sha"] == current_sha
        assert override["by"] == "sid"


class TestResolveDerivedFrom:
    def test_sizing_path_exists(self, tmp_path):
        sizing = tmp_path / "state" / "sizings" / "x.yaml"
        sizing.parent.mkdir(parents=True)
        sizing.write_text("estimate:\n  tshirt: M\n", encoding="utf-8")
        assert coas._resolve_derived_from("state/sizings/x.yaml", tmp_path) is None

    def test_sizing_path_absent_refuses_naming_the_path(self, tmp_path):
        failure = coas._resolve_derived_from("state/sizings/never-existed.yaml", tmp_path)
        assert failure is not None
        assert "never-existed.yaml" in failure

    def test_kr_shape_resolves(self, tmp_path):
        goals_dir = tmp_path / "state" / "goals"
        goals_dir.mkdir(parents=True)
        (goals_dir / "g1.yaml").write_text(
            yaml.safe_dump(
                {
                    "id": "goal-shipping-velocity",
                    "key_results": [{"id": "kr-throughput", "text": "t"}],
                }
            ),
            encoding="utf-8",
        )
        failure = coas._resolve_derived_from(
            "goal-shipping-velocity#kr-throughput", tmp_path
        )
        assert failure is None

    def test_kr_shape_goal_id_not_found(self, tmp_path):
        goals_dir = tmp_path / "state" / "goals"
        goals_dir.mkdir(parents=True)
        (goals_dir / "g1.yaml").write_text(
            yaml.safe_dump({"id": "goal-other", "key_results": []}), encoding="utf-8"
        )
        failure = coas._resolve_derived_from("goal-nonexistent#kr-x", tmp_path)
        assert failure is not None
        assert "goal-nonexistent" in failure

    def test_kr_shape_kr_id_not_found_in_goal(self, tmp_path):
        goals_dir = tmp_path / "state" / "goals"
        goals_dir.mkdir(parents=True)
        (goals_dir / "g1.yaml").write_text(
            yaml.safe_dump(
                {"id": "goal-x", "key_results": [{"id": "kr-1", "text": "t"}]}
            ),
            encoding="utf-8",
        )
        failure = coas._resolve_derived_from("goal-x#kr-missing", tmp_path)
        assert failure is not None
        assert "kr-missing" in failure

    def test_kr_shape_never_treats_an_index_as_an_id(self, tmp_path):
        """AC20: `key_results[].id` must be matched by ITS OWN id field,
        never an array index -- a KR list whose first entry lacks a
        matching id must still refuse even though index 0 exists."""
        goals_dir = tmp_path / "state" / "goals"
        goals_dir.mkdir(parents=True)
        (goals_dir / "g1.yaml").write_text(
            yaml.safe_dump(
                {"id": "goal-x", "key_results": [{"id": "kr-other", "text": "t"}]}
            ),
            encoding="utf-8",
        )
        failure = coas._resolve_derived_from("goal-x#kr-0", tmp_path)
        assert failure is not None


# ===========================================================================
# End-to-end: close_out_and_stamp's own stamp-decision gate
# ===========================================================================


class TestGoalGateEndToEnd:
    def test_absent_falsifier_is_unaffected_arm1(self, tmp_path, monkeypatch):
        root = tmp_path
        _init_repo(root)
        shipping_sha = _land_the_shipping_chunk(root)
        goal_fm = (
            "prime_exit_criterion:\n"
            "  statement: The fixture surface behaves as claimed.\n"
            "  derived_from: state/sizings/2026-08-27-fixture-sizing.yaml\n"
        )
        _seed_goal_plan(root, goal_frontmatter=goal_fm, shipping_sha=shipping_sha)
        sizing = root / "state" / "sizings" / "2026-08-27-fixture-sizing.yaml"
        sizing.parent.mkdir(parents=True, exist_ok=True)
        sizing.write_text("estimate:\n  tshirt: S\n", encoding="utf-8")

        exit_code, result = _run_close_out(monkeypatch, root, "plan.md")

        assert exit_code == coas.EXIT_OK, result
        assert result["status_target"] == "implemented"
        assert result["goal_gate"]["refused"] is False
        assert result["goal_gate"]["override"] is False

    def test_absent_exit_criterion_met_refuses_ac4(self, tmp_path, monkeypatch):
        root = tmp_path
        _init_repo(root)
        shipping_sha = _land_the_shipping_chunk(root)
        goal_fm = _prime_exit_criterion_block(
            baseline_ref=shipping_sha, exit_criterion_met=None
        )
        _seed_goal_plan(root, goal_frontmatter=goal_fm, shipping_sha=shipping_sha)

        exit_code, result = _run_close_out(monkeypatch, root, "plan.md", dry_run=True)

        assert exit_code == coas.EXIT_OK, result
        assert result["status_target"] is None
        assert result["stamped"] is False
        assert result["goal_gate"]["refused"] is True
        assert result["goal_gate"]["reason"] == coas.GOAL_REFUSAL_EXIT_CRITERION_ABSENT
        assert "next move" not in result["message"]
        assert "close-out skill" in result["message"]

    def test_asserted_false_refuses_ac4(self, tmp_path, monkeypatch):
        root = tmp_path
        _init_repo(root)
        shipping_sha = _land_the_shipping_chunk(root)
        goal_fm = _prime_exit_criterion_block(
            baseline_ref=shipping_sha, exit_criterion_met=_asserted_false_block()
        )
        _seed_goal_plan(root, goal_frontmatter=goal_fm, shipping_sha=shipping_sha)

        exit_code, result = _run_close_out(monkeypatch, root, "plan.md", dry_run=True)

        assert exit_code == coas.EXIT_OK, result
        assert result["status_target"] is None
        assert result["goal_gate"]["reason"] == coas.GOAL_REFUSAL_NOT_ASSERTED
        assert "surface was removed" in result["goal_gate"]["detail"]

    def test_bad_baseline_ref_refuses_and_names_which_reason_ac6(
        self, tmp_path, monkeypatch
    ):
        root = tmp_path
        _init_repo(root)
        shipping_sha = _land_the_shipping_chunk(root)
        non_ancestor = _make_non_ancestor_commit(root)
        goal_fm = _prime_exit_criterion_block(
            baseline_ref=non_ancestor, exit_criterion_met=_asserted_pass_block()
        )
        _seed_goal_plan(root, goal_frontmatter=goal_fm, shipping_sha=shipping_sha)

        exit_code, result = _run_close_out(monkeypatch, root, "plan.md", dry_run=True)

        assert exit_code == coas.EXIT_OK, result
        assert result["status_target"] is None
        assert (
            result["goal_gate"]["reason"]
            == f"{coas.GOAL_REFUSAL_BASELINE_REF_PREFIX}{coas.DISPOSITION_REF_NOT_ANCESTOR}"
        )

    def test_verdict_not_pass_refuses_ac5_never_a_delta_comparison(
        self, tmp_path, monkeypatch
    ):
        """The defect this closes: a changed-but-non-matching output must
        still refuse -- this is deliberately NOT the retired delta rule
        (falsifier_output != baseline_output would have passed here)."""
        root = tmp_path
        _init_repo(root)
        shipping_sha = _land_the_shipping_chunk(root)
        goal_fm = _prime_exit_criterion_block(
            baseline_ref=shipping_sha,
            exit_criterion_met=_asserted_true_verdict_fail_block(),
        )
        _seed_goal_plan(root, goal_frontmatter=goal_fm, shipping_sha=shipping_sha)

        exit_code, result = _run_close_out(monkeypatch, root, "plan.md", dry_run=True)

        assert exit_code == coas.EXIT_OK, result
        assert result["status_target"] is None
        assert result["goal_gate"]["reason"] == coas.GOAL_REFUSAL_VERDICT_NOT_PASS

    def test_passing_verdict_ships_implemented_ac5(self, tmp_path, monkeypatch):
        root = tmp_path
        _init_repo(root)
        shipping_sha = _land_the_shipping_chunk(root)
        goal_fm = _prime_exit_criterion_block(
            baseline_ref=shipping_sha, exit_criterion_met=_asserted_pass_block()
        )
        _seed_goal_plan(root, goal_frontmatter=goal_fm, shipping_sha=shipping_sha)

        exit_code, result = _run_close_out(monkeypatch, root, "plan.md")

        assert exit_code == coas.EXIT_OK, result
        assert result["status_target"] == "implemented"
        assert result["stamped"] is True
        assert result["goal_gate"]["refused"] is False

    def test_unresolvable_derived_from_refuses_and_names_which_half_ac20(
        self, tmp_path, monkeypatch
    ):
        root = tmp_path
        _init_repo(root)
        shipping_sha = _land_the_shipping_chunk(root)
        goal_fm = _prime_exit_criterion_block(
            derived_from="state/sizings/never-existed.yaml",
            baseline_ref=shipping_sha,
            exit_criterion_met=_asserted_pass_block(),
        )
        _seed_goal_plan(root, goal_frontmatter=goal_fm, shipping_sha=shipping_sha)

        exit_code, result = _run_close_out(monkeypatch, root, "plan.md", dry_run=True)

        assert exit_code == coas.EXIT_OK, result
        assert result["status_target"] is None
        assert (
            result["goal_gate"]["reason"] == coas.GOAL_REFUSAL_DERIVED_FROM_UNRESOLVABLE
        )
        assert "never-existed.yaml" in result["goal_gate"]["detail"]

    def test_status_override_bound_to_body_hash_suppresses_the_refusal_ac19(
        self, tmp_path, monkeypatch
    ):
        root = tmp_path
        _init_repo(root)
        shipping_sha = _land_the_shipping_chunk(root)

        # Two-pass: first compute the plan's own body hash by rendering it
        # WITHOUT the override block, then re-render WITH an override bound
        # to that hash -- the override never changes the body itself
        # (frontmatter-only field), so the hash is stable across the two
        # renders.
        provisional_fm = _prime_exit_criterion_block(
            baseline_ref=shipping_sha, exit_criterion_met=None
        )
        provisional_text = _PLAN_TEMPLATE.format(
            status="executing",
            goal_frontmatter=provisional_fm,
            rows=_SHIPPED_ROW.format(sha=shipping_sha),
        )
        body_sha = canonical_body_sha(provisional_text)

        goal_fm = _prime_exit_criterion_block(
            baseline_ref=shipping_sha,
            exit_criterion_met=None,
            status_override=_status_override_block(body_sha),
        )
        _seed_goal_plan(root, goal_frontmatter=goal_fm, shipping_sha=shipping_sha)

        exit_code, result = _run_close_out(monkeypatch, root, "plan.md")

        assert exit_code == coas.EXIT_OK, result
        # The override SUPPRESSES the refusal (AC19) -- the stamp proceeds,
        # so `refused` reads `False`; `override` is the field that marks
        # this distinctly from a clean, unattested stamp.
        assert result["goal_gate"]["override"] is True
        assert result["goal_gate"]["refused"] is False
        assert result["status_target"] == "implemented"

    def test_dry_run_reports_the_refusal_without_writing_ac8(self, tmp_path, monkeypatch):
        root = tmp_path
        _init_repo(root)
        shipping_sha = _land_the_shipping_chunk(root)
        goal_fm = _prime_exit_criterion_block(
            baseline_ref=shipping_sha, exit_criterion_met=None
        )
        plan_file = _seed_goal_plan(
            root, goal_frontmatter=goal_fm, shipping_sha=shipping_sha
        )
        pre_head = _head_sha(root)

        exit_code, result = _run_close_out(monkeypatch, root, "plan.md", dry_run=True)

        assert exit_code == coas.EXIT_OK, result
        assert result["goal_gate"]["refused"] is True
        assert result["dry_run"] is True
        assert _head_sha(root) == pre_head
        assert "status: implemented" not in plan_file.read_text(encoding="utf-8")


# ===========================================================================
# AC7: the grandfathered corpus is byte-identical to the pre-C2 result dict
# ===========================================================================


class TestGrandfatheredCorpusIsUnaffected:
    """A real, pre-existing plan that never declared `prime_exit_criterion`
    must produce a `dry_run=True` result dict byte-identical to the pre-C2
    implementation's own result for the same plan (AC7). See this file's
    own module docstring for exactly how `fixtures/close_out_dry_run_pre_
    change.json` was generated."""

    def test_corpus_sample_matches_the_pre_change_fixture(self):
        fixture = json.loads(_FIXTURE_PATH.read_text(encoding="utf-8"))
        assert fixture, "fixture must not be empty -- AC7 needs a real corpus sample"

        for plan_rel, expected in fixture.items():
            plan_path = _REPO_ROOT / plan_rel
            assert plan_path.is_file(), f"corpus plan moved or deleted: {plan_rel}"
            with open(plan_path, encoding="utf-8") as fh:
                assert "prime_exit_criterion" not in fh.read(), (
                    f"{plan_rel} now declares prime_exit_criterion -- pick a "
                    "different grandfathered corpus sample, this one no "
                    "longer qualifies for AC7's own guarantee"
                )

            exit_code, result = coas.close_out_and_stamp(
                plan_rel, repo_root=_REPO_ROOT, dry_run=True
            )

            # `gates.repo_identity` carries this SESSION's own live sid/
            # session_root resolution (`session_core.resolve_session_id`)
            # -- volatile across runs/sessions for reasons entirely outside
            # this op's own stamp-decision logic, and already informational-
            # only (never gates the refusal this test exists to pin). Every
            # OTHER key -- the actual stamp decision this AC is about --
            # must still match exactly.
            actual = dict(result)
            actual.pop("gates", None)
            fixture_expected = dict(expected["result"])
            fixture_expected.pop("gates", None)

            assert exit_code == expected["exit_code"], plan_rel
            assert actual == fixture_expected, plan_rel
            assert "goal_gate" not in result, plan_rel

class TestGrandfatherDatePin:
    """Arm 0 — a plan that declares no `prime_exit_criterion` at all.

    Before this arm, absence was the gate's only unconditional exit, so an EM
    who never wrote a criterion was never caught while one who wrote it and
    got the observation wrong was. These pin the two bounds that keep the
    refusal off the grandfathered corpus: the `created` date and the M+ size.
    """

    def _plan(self, tmp_path, *, created: str, tshirt=None, extra_fm: str = "") -> str:
        sizing_line = ""
        if tshirt is not None:
            sizing = tmp_path / "state" / "sizings" / "s.yaml"
            sizing.parent.mkdir(parents=True, exist_ok=True)
            sizing.write_text(
                "schema: sizing-object\nestimate:\n  tshirt: %s\n" % tshirt,
                encoding="utf-8",
            )
            sizing_line = "sizing_object: state/sizings/s.yaml\n"
        return "---\ntitle: t\ncreated: %s\n%s%s---\n\nbody\n" % (
            created,
            sizing_line,
            extra_fm,
        )

    def test_m_plus_plan_created_on_the_date_refuses(self, tmp_path):
        text = self._plan(tmp_path, created="2026-08-27", tshirt="M")
        gate = coas._evaluate_goal_falsifier_gate(text, tmp_path)
        assert gate is not None
        assert gate["refused"] is True
        assert gate["reason"] == coas.GOAL_REFUSAL_PRIME_ABSENT
        # The refusal names the date, so a reader learns the rule without
        # going to look it up.
        assert coas.GRANDFATHER_DATE in gate["detail"]

    def test_m_plus_plan_created_after_the_date_refuses(self, tmp_path):
        text = self._plan(tmp_path, created="2026-09-15", tshirt="XL")
        gate = coas._evaluate_goal_falsifier_gate(text, tmp_path)
        assert gate is not None and gate["refused"] is True

    def test_plan_created_before_the_date_is_grandfathered(self, tmp_path):
        """The whole pre-existing corpus. `None`, not a non-refusing dict —
        the caller adds no result-dict key at all on `None`, which is AC7's
        differential-fixture guarantee."""
        text = self._plan(tmp_path, created="2026-08-26", tshirt="XXL")
        assert coas._evaluate_goal_falsifier_gate(text, tmp_path) is None

    def test_small_plan_on_the_date_is_untouched(self, tmp_path):
        """S/XS was never in scope — plan.schema.json scopes the falsifier
        requirement to M+ and this arm inherits that bound rather than
        widening it."""
        text = self._plan(tmp_path, created="2026-08-27", tshirt="S")
        assert coas._evaluate_goal_falsifier_gate(text, tmp_path) is None

    def test_unlinked_sizing_object_declines_rather_than_refusing(self, tmp_path):
        """Fails toward grandfathering, never toward refusal: an unread size
        must not be the thing that blocks a stamp."""
        text = self._plan(tmp_path, created="2026-08-27", tshirt=None)
        assert coas._evaluate_goal_falsifier_gate(text, tmp_path) is None

    def test_dangling_sizing_pointer_declines(self, tmp_path):
        text = (
            "---\ntitle: t\ncreated: 2026-08-27\n"
            "sizing_object: state/sizings/never-existed.yaml\n---\n\nbody\n"
        )
        assert coas._evaluate_goal_falsifier_gate(text, tmp_path) is None

    def test_unparseable_created_declines(self, tmp_path):
        text = self._plan(tmp_path, created="'not-a-date'", tshirt="L")
        assert coas._evaluate_goal_falsifier_gate(text, tmp_path) is None

    def test_absent_created_declines(self, tmp_path):
        sizing = tmp_path / "state" / "sizings" / "s.yaml"
        sizing.parent.mkdir(parents=True, exist_ok=True)
        sizing.write_text("estimate:\n  tshirt: M\n", encoding="utf-8")
        text = "---\ntitle: t\nsizing_object: state/sizings/s.yaml\n---\n\nbody\n"
        assert coas._evaluate_goal_falsifier_gate(text, tmp_path) is None

    def test_yaml_parsed_date_object_is_handled(self, tmp_path):
        """An unquoted ISO date loads as `datetime.date`, not `str` — the
        frontmatter validator is lenient about exactly this coercion, so both
        shapes reach here in the real corpus."""
        text = self._plan(tmp_path, created="2026-08-28", tshirt="M")
        assert "created: 2026-08-28" in text
        gate = coas._evaluate_goal_falsifier_gate(text, tmp_path)
        assert gate is not None and gate["refused"] is True

    def test_status_override_suppresses_the_refusal(self, tmp_path):
        """Same escape hatch every other arm honours (AC19), bound to the
        body hash — not a new bypass."""
        provisional = self._plan(tmp_path, created="2026-08-27", tshirt="M")
        sha = canonical_body_sha(provisional)
        text = self._plan(
            tmp_path,
            created="2026-08-27",
            tshirt="M",
            extra_fm=(
                "status_override_by: sid\n"
                "status_override_reason: 'body_sha=%s: ratified exception'\n"
                "status_override_at: '2026-08-27T00:00:00Z'\n" % sha
            ),
        )
        gate = coas._evaluate_goal_falsifier_gate(text, tmp_path)
        assert gate is not None
        assert gate["refused"] is False
        assert gate["override"] is True

    def test_declared_criterion_never_reaches_arm_zero(self, tmp_path):
        """A plan that DOES declare the field is judged by the arms below,
        not by this one — pins that arm 0 is an absence check only."""
        text = (
            "---\ntitle: t\ncreated: 2026-08-27\n"
            "prime_exit_criterion:\n  statement: s\n---\n\nbody\n"
        )
        gate = coas._evaluate_goal_falsifier_gate(text, tmp_path)
        assert gate is not None
        assert gate["reason"] != coas.GOAL_REFUSAL_PRIME_ABSENT


class TestAbsentFalsifierIsSizeGated:
    """Arm 1(cont) — a plan that DECLARES a criterion and carries no usable
    falsifier.

    Before this arm the gate returned its non-refusing result here at every
    lane, which applied the S-lane carve-out to all of them: the schema
    scopes the falsifier requirement to M+ through `sizing_object`, and
    nothing enforced it. Measured 2026-08-27 across four fixtures differing
    only in t-shirt, all four non-refusing —
    cross-repo/archive/2026-08-27-doe-claude-em-ac-12-needs-a-size-gate-not-the-verdict-gate.md.

    These pin the size bound in BOTH directions: the M+ half must refuse, and
    the S half must keep passing. A gate that only refuses is a gate that has
    lost its carve-out.
    """

    def _plan(
        self, tmp_path, *, created: str = "2026-08-28", tshirt=None, extra: str = ""
    ) -> str:
        sizing_line = ""
        if tshirt is not None:
            sizing = tmp_path / "state" / "sizings" / "s.yaml"
            sizing.parent.mkdir(parents=True, exist_ok=True)
            sizing.write_text(
                "schema: sizing-object\nestimate:\n  tshirt: %s\n" % tshirt,
                encoding="utf-8",
            )
            sizing_line = "sizing_object: state/sizings/s.yaml\n"
        return (
            "---\ntitle: t\ncreated: %s\n%s"
            "prime_exit_criterion:\n"
            "  statement: The surface behaves as claimed.\n"
            "%s"
            "exit_criterion_met:\n"
            "  asserted: true\n"
            "  falsifier_verdict: pass\n"
            "---\n\nbody\n"
        ) % (created, sizing_line, extra)

    def test_m_plus_plan_with_no_falsifier_refuses(self, tmp_path):
        gate = coas._evaluate_goal_falsifier_gate(
            self._plan(tmp_path, tshirt="M"), tmp_path
        )
        assert gate["refused"] is True
        assert gate["reason"] == coas.GOAL_REFUSAL_FALSIFIER_ABSENT
        assert coas.GRANDFATHER_DATE in gate["detail"]

    def test_the_refusal_covers_every_m_plus_lane(self, tmp_path):
        for tshirt in ("M", "L", "XL"):
            gate = coas._evaluate_goal_falsifier_gate(
                self._plan(tmp_path, tshirt=tshirt), tmp_path
            )
            assert gate["refused"] is True, tshirt

    def test_s_plan_with_no_falsifier_still_passes(self, tmp_path):
        """The carve-out this arm exists to stop over-applying. S carries
        statement+derived_from only, by design."""
        gate = coas._evaluate_goal_falsifier_gate(
            self._plan(tmp_path, tshirt="S"), tmp_path
        )
        assert gate["refused"] is False
        assert gate["reason"] is None

    def test_plan_created_before_the_date_is_grandfathered(self, tmp_path):
        gate = coas._evaluate_goal_falsifier_gate(
            self._plan(tmp_path, created="2026-08-26", tshirt="XL"), tmp_path
        )
        assert gate["refused"] is False

    def test_unreadable_size_declines_rather_than_refusing(self, tmp_path):
        """Fails toward passing, matching arm 0: an unread size must never be
        the thing that blocks a stamp."""
        gate = coas._evaluate_goal_falsifier_gate(
            self._plan(tmp_path, tshirt=None), tmp_path
        )
        assert gate["refused"] is False

    def test_named_exemption_is_honoured_at_m_plus(self, tmp_path):
        """The schema's sanctioned escape hatch. Refusing a plan that took the
        named route would punish the discipline the hatch exists to reward."""
        extra = (
            "  falsifier_exemption:\n"
            "    class: unfalsifiable-by-observation-doctrine-or-schema-edit\n"
            "    admission: Doctrine-only edit; no runtime surface a how could "
            "observe. Drafting one was attempted and failed.\n"
        )
        gate = coas._evaluate_goal_falsifier_gate(
            self._plan(tmp_path, tshirt="XL", extra=extra), tmp_path
        )
        assert gate["refused"] is False

    def test_invented_exemption_class_does_not_buy_silence(self, tmp_path):
        """The class is pinned to one spelling precisely so the hatch cannot be
        widened by naming a new one."""
        extra = (
            "  falsifier_exemption:\n"
            "    class: my-own-special-case\n"
            "    admission: It seemed fine.\n"
        )
        gate = coas._evaluate_goal_falsifier_gate(
            self._plan(tmp_path, tshirt="M", extra=extra), tmp_path
        )
        assert gate["refused"] is True
        assert gate["reason"] == coas.GOAL_REFUSAL_FALSIFIER_ABSENT

    def test_blank_admission_does_not_buy_silence(self, tmp_path):
        extra = (
            "  falsifier_exemption:\n"
            "    class: unfalsifiable-by-observation-doctrine-or-schema-edit\n"
            "    admission: '   '\n"
        )
        gate = coas._evaluate_goal_falsifier_gate(
            self._plan(tmp_path, tshirt="M", extra=extra), tmp_path
        )
        assert gate["refused"] is True

    def test_the_next_move_names_the_falsifier_not_the_statement(self, tmp_path):
        """A plan that already wrote its statement must not be told to write
        one -- that reads its own frontmatter back to it."""
        assert "falsifier" in coas._FALSIFIER_ABSENT_NEXT_MOVE
        assert "falsifier_exemption" in coas._FALSIFIER_ABSENT_NEXT_MOVE
