"""
RoadmapDagEdge — THE SOURCE OF RECORD for this entity's shape. Not a port.

It began as a pydantic port of DoE's
`coordinator/cockpit-contract/src/entities/roadmap-dag-edge.ts`, but that Zod/TS
mirror was deliberately retired (their D2 superseded by D16; cockpit-contract
README § Regenerating the schema). With the mirror gone there is nothing upstream
to agree with: this file IS the authoring surface, DoE owns the artifact and its
governance, and their generated JSON bundle is DOWNSTREAM of a regen run here
(`coordinator/bin/regen-cockpit-schema.py`). Read a disagreement between this
model and their bundle as "the regen has not run yet", never as drift to resolve
by editing the JSON — hand-editing the generated bytes is what destroys their
release capability.

A directed dependency edge in a roadmap DAG, emitted by claude-klabauter's
`coordinator_core/ops/roadmap_dag.py`. The seam stores one direction; reverse is
derived by consumers. Two altitudes ride the same entity: stub-to-stub
("blocks") and sprint-to-sprint ("blocks-sprint", D47).

Spec backlinks:
  - docs/plans/2026-07-06-cockpit-contract-v260-initiative-status-widen-roadmap-dag.md § Chunk B
  - docs/plans/2026-07-15-bash-to-naked-python-engine-migration.md § T4e

`type` is `Literal["blocks"]` — intentionally rigid. Adding an edge type is a
governed contract bump (not an oversight); a future reader who considers
widening to an enum should open a new version rather than loosening this type
in place.

Logical identity: (repo, roadmap_id, from, to).
`coordinator_root_path` is an ADDITIVE connector key present on every
connector-emitted entity — it is NOT part of the logical DAG identity.
rag's edge table MUST key on the 4-field logical identity, not the 5-field
connector composite.

`from` is a reserved word in Python — the field is declared as `from_` with
`Field(alias="from")` so both parse (`model_validate`) and emission
(`model_dump(by_alias=True)` / `model_json_schema()`, which defaults to
`by_alias=True`) speak the wire name `from`, byte-identical to the Zod
source's `from` key.
"""
from __future__ import annotations

from typing import Literal

from pydantic import BaseModel, ConfigDict, Field

from coordinator_core.contract.cockpit_schema.provenance import ContentHash, ProvenanceEnvelope


class RoadmapDagEdge(BaseModel):
    model_config = ConfigDict(extra="forbid", populate_by_name=True)

    repo: str = Field(
        description=(
            "Owner-qualified repo identity: '<owner>/<repo>'. Owner carries the "
            "producing repo's own casing (producer-authoritative — there is no "
            "independent casing authority); no '.git' suffix. Consumers must not "
            "assume pre-normalization: normalizing to lower(owner)/lower(repo) for "
            "join, dedup, or storage keying is conformant. See DR-022. This "
            "owner-qualified string is the canonical cross-entity join anchor."
        )
    )
    coordinator_root_path: str
    roadmap_id: str
    from_: str = Field(alias="from")
    to: str
    # This is atomic with CONTRACT_VERSION -> 3.15.0 in emit_schema.py AND a
    type: Literal["blocks", "blocks-sprint"]
    provenance: ProvenanceEnvelope

    content_hash: ContentHash | None = None
