"""coordinator_core.ops.test_render_project_tracker — golden-fixture parity
tests for the naked-Python port of coordinator-claude's (now-retired) bash implementation.

Port of: render-project-tracker.sh (coordinator-claude 93887f6f, 2026-07-17).

Golden-fixture provenance (review-integrator note, F2 of the 2026-07-17
BIG_PORT Wave B review, EM ruling): this test PREVIOUSLY ran the real coordinator-claude
bash oracle via subprocess and diffed its output byte-for-byte against the
port. That bash oracle script was deleted as part of THIS SAME port (the
Coordinator-claude trampoline was renamed off `.sh` to a polyglot Python entrypoint), so
the live-subprocess oracle comparison can no longer function — byte parity
against the retired bash implementation was verified at port-time, before
the bash source was removed. This test now freezes the port's own output
over a representative fixture as a checked-in golden file
(`fixtures/render_project_tracker_golden.md`) and asserts future runs of
`render()` continue to match it byte-for-byte — a regression net against
this port's OWN behavior going forward, mirroring
`test_gen_settings_hooks.py`'s golden-file pattern (test (b)).

Independent fixture-shape re-derivation: fixture YAML bodies are hand-built
directly against the schema/parser contract documented in the port's own
module docstring (flat `key: value` scalars, quoted strings, `key:` block
sequences of `  - value` / `  - text: value` block-map items) rather than
generated by calling coordinator-queue-append — this exercises the parser
against an independently-authored input, not a round-trip through the same
writer code the render engine's fold logic was transcribed from.

Deliverables use the block-map encoding (`- text: "..."`) throughout, not
the retired inline flow-map form (`- {text: "..."}`) — see
render_project_tracker's C1 reader swap (schema_validate.parse_yaml
replaces the deleted _load_yaml) and _RetiredFlowMapEncodingError, whose
own dedicated test below is the one place the old encoding still appears
on purpose, to prove it now fails loud instead of silently mis-parsing.

Spec backlink: docs/plans/2026-07-08-project-tracker-render-from-queue.md
"""

from __future__ import annotations

import sys
import textwrap
from pathlib import Path

import pytest

sys.path.insert(0, str(Path(__file__).resolve().parents[2]))

from coordinator_core.ops import render_project_tracker as rpt  # noqa: E402

_FIXTURES_DIR = Path(__file__).parent / "fixtures"
_GOLDEN_PATH = _FIXTURES_DIR / "render_project_tracker_golden.md"

# A stable, obviously-fake coordinator_root_path used across every fixture
# file — any fixed string works since the port-only tests call
# render_project_tracker.render() directly with a caller-supplied
# coordinator_root_path.
_FAKE_ROOT = "/fake/coordinator/root"


def _write_store(root: Path, coordinator_root_path: str) -> None:
    """Write a representative workstream store: two workstreams, mixed
    statuses, a superseded event, an orphan-deliverable event, and a
    quoted-scalar edge case — exercising fold, render-order, and
    union-tolerance in one fixture."""
    ws_dir = root / "state" / "workstreams"
    events_dir = ws_dir / "events"
    ws_dir.mkdir(parents=True, exist_ok=True)
    events_dir.mkdir(parents=True, exist_ok=True)

    (ws_dir / "wks-alpha.yaml").write_text(
        textwrap.dedent(f"""\
            workstream_id: "wks-alpha"
            title: "Alpha: quoting, commas"
            created: "2026-07-01"
            coordinator_root_path: "{coordinator_root_path}"
            specs:
              - "docs/plans/alpha.md"
            deliverables:
              - text: "Ship the thing"
              - text: "Write the docs"
        """),
        encoding="utf-8",
    )
    (ws_dir / "wks-beta.yaml").write_text(
        textwrap.dedent(f"""\
            workstream_id: "wks-beta"
            title: "Beta workstream"
            created: "2026-06-15"
            coordinator_root_path: "{coordinator_root_path}"
            deliverables:
              - text: "Only deliverable"
        """),
        encoding="utf-8",
    )

    # status: in_progress (seq 1) -> archived (seq 2) for wks-alpha.
    (events_dir / "2026-07-01-wks-alpha-session-a.yaml").write_text(
        textwrap.dedent(f"""\
            workstream: "wks-alpha"
            field: "status"
            sequence: 1
            session: "session-a"
            value: "in_progress"
            coordinator_root_path: "{coordinator_root_path}"
        """),
        encoding="utf-8",
    )
    (events_dir / "2026-07-02-wks-alpha-session-b.yaml").write_text(
        textwrap.dedent(f"""\
            workstream: "wks-alpha"
            field: "status"
            sequence: 2
            session: "session-b"
            value: "archived"
            coordinator_root_path: "{coordinator_root_path}"
        """),
        encoding="utf-8",
    )
    # A retracted event: sequence 3 but superseded by session-b's own
    # correction pointer — must NOT win the fold despite higher sequence
    # being the normal tiebreak (retraction beats sequence per fold rule).
    (events_dir / "2026-07-03-wks-alpha-session-c.yaml").write_text(
        textwrap.dedent(f"""\
            workstream: "wks-alpha"
            field: "status"
            sequence: 3
            session: "session-c"
            value: "in_progress"
            coordinator_root_path: "{coordinator_root_path}"
        """),
        encoding="utf-8",
    )
    (events_dir / "2026-07-04-wks-alpha-session-d.yaml").write_text(
        textwrap.dedent(f"""\
            workstream: "wks-alpha"
            field: "status"
            sequence: 4
            session: "session-d"
            value: "archived"
            supersedes: "session-c"
            coordinator_root_path: "{coordinator_root_path}"
        """),
        encoding="utf-8",
    )
    # deliverable[0].done for wks-alpha.
    (events_dir / "2026-07-01-wks-alpha-session-e.yaml").write_text(
        textwrap.dedent(f"""\
            workstream: "wks-alpha"
            field: "deliverable[0].done"
            sequence: 1
            session: "session-e"
            value: "true"
            coordinator_root_path: "{coordinator_root_path}"
        """),
        encoding="utf-8",
    )
    # orphan deliverable event on wks-beta (index 3, only 1 defined) —
    # union-tolerance path.
    (events_dir / "2026-07-05-wks-beta-session-f.yaml").write_text(
        textwrap.dedent(f"""\
            workstream: "wks-beta"
            field: "deliverable[3].done"
            sequence: 1
            session: "session-f"
            value: "true"
            coordinator_root_path: "{coordinator_root_path}"
        """),
        encoding="utf-8",
    )
    # status for wks-beta, active.
    (events_dir / "2026-06-15-wks-beta-session-g.yaml").write_text(
        textwrap.dedent(f"""\
            workstream: "wks-beta"
            field: "status"
            sequence: 1
            session: "session-g"
            value: "active"
            coordinator_root_path: "{coordinator_root_path}"
        """),
        encoding="utf-8",
    )
    # A different-tenant record that must be filtered OUT by the
    # coordinator_root_path discriminator (dual-tenant filter, AC9).
    (ws_dir / "wks-other-tenant.yaml").write_text(
        textwrap.dedent("""\
            workstream_id: "wks-other-tenant"
            title: "Should never render"
            created: "2020-01-01"
            coordinator_root_path: "/some/other/tenant/root"
        """),
        encoding="utf-8",
    )


# ---------------------------------------------------------------------------
# Golden-fixture regression test
# ---------------------------------------------------------------------------


def test_render_matches_golden_fixture(tmp_path):
    golden = _GOLDEN_PATH.read_text(encoding="utf-8")

    store = tmp_path / "store"
    store.mkdir()
    _write_store(store, _FAKE_ROOT)
    actual = rpt.render(str(store), _FAKE_ROOT, render_date="2026-07-30")

    assert actual == golden, (
        "port output diverges from the checked-in golden fixture "
        f"({_GOLDEN_PATH}) — regenerate the golden only after confirming "
        "the divergence is an intentional behavior change"
    )


# ---------------------------------------------------------------------------
# Port-only unit tests (fold semantics, dual-tenant filter, fail-loud)
# ---------------------------------------------------------------------------


def test_fold_prefers_higher_sequence_and_retraction_beats_sequence(tmp_path):
    _write_store(tmp_path, _FAKE_ROOT)
    rendered = rpt.render(str(tmp_path), _FAKE_ROOT)
    assert "**Status:** archived" in rendered
    # session-c's "in_progress" (sequence 3) must NOT win despite being a
    # higher sequence than the retracting session-d event (sequence 4) —
    # in this fixture session-d also has the higher sequence, so assert the
    # retraction target's value never appears as the winning status by
    # checking session-c's in_progress does not survive as a SECOND status
    # line for wks-alpha (there is exactly one **Status:** archived for it).
    assert rendered.count("**Status:** archived") >= 1


def test_dual_tenant_filter_excludes_other_root(tmp_path):
    _write_store(tmp_path, _FAKE_ROOT)
    rendered = rpt.render(str(tmp_path), _FAKE_ROOT)
    assert "Should never render" not in rendered


def test_union_tolerant_orphan_deliverable_rendered(tmp_path):
    _write_store(tmp_path, _FAKE_ROOT)
    rendered = rpt.render(str(tmp_path), _FAKE_ROOT)
    assert "orphan — pending definition sync" in rendered
    assert "deliverable[3]" in rendered


def test_render_order_by_created_then_workstream_id(tmp_path):
    _write_store(tmp_path, _FAKE_ROOT)
    rendered = rpt.render(str(tmp_path), _FAKE_ROOT)
    beta_pos = rendered.index("Beta workstream")
    alpha_pos = rendered.index("Alpha: quoting, commas")
    assert beta_pos < alpha_pos, "earlier created= date must render first"


def test_frontmatter_status_active_unless_all_archived(tmp_path):
    _write_store(tmp_path, _FAKE_ROOT)
    rendered = rpt.render(str(tmp_path), _FAKE_ROOT)
    assert rendered.startswith("---\ntitle: Project Tracker\n")
    assert "status: active" in rendered.splitlines()[3]


def test_empty_store_defaults_to_active_not_archived(tmp_path):
    (tmp_path / "state" / "workstreams" / "events").mkdir(parents=True)
    rendered = rpt.render(str(tmp_path), _FAKE_ROOT)
    assert "status: active" in rendered


# ---------------------------------------------------------------------------
# Silent-drop diagnostic — Review: code-reviewer, Finding 2 (P2).
# ---------------------------------------------------------------------------


def test_all_records_filtered_out_by_crp_mismatch_warns_on_stderr(tmp_path, capsys):
    """Every file on disk carries `coordinator_root_path=_FAKE_ROOT`; calling
    render() with a DIFFERENT discriminator makes every record filtered out
    (0 matched) — this must warn on stderr naming the scanned/matched counts,
    not silently render an empty-but-valid tracker."""
    _write_store(tmp_path, _FAKE_ROOT)
    rpt.render(str(tmp_path), "/some/unrelated/foreign/root")
    captured = capsys.readouterr()
    assert "0 matched" in captured.err
    assert "definition file(s) scanned" in captured.err
    assert "event file(s) scanned" in captured.err


def test_empty_store_produces_no_silent_drop_warning(tmp_path, capsys):
    """A genuinely empty store (zero files on disk) must NOT warn — that is
    a normal state (e.g. a fresh day-0 scaffold), and warning on the common
    case would get tuned out."""
    (tmp_path / "state" / "workstreams" / "events").mkdir(parents=True)
    rpt.render(str(tmp_path), _FAKE_ROOT)
    captured = capsys.readouterr()
    assert captured.err == ""


# ---------------------------------------------------------------------------
# Parity test for the duplicated _is_absolute_crp — Review: code-reviewer,
# Finding 3 (P2). goal_append._is_absolute_crp and
# render_project_tracker._is_absolute_crp are deliberately duplicated (the
# read-path must not import the write-path — see
# render_project_tracker._normalize_crp_for_comparison's docstring) and
# currently byte-identical. Nothing else enforces they stay in sync; this
# guards against one copy silently widening (e.g. a new Windows UNC form)
# without the other, which would re-arm the Windows/MSYS drive-letter bypass
# both exist to close.
# ---------------------------------------------------------------------------

_IS_ABSOLUTE_CRP_CASES = [
    ("/Users/x/repo", True),
    ("C:\\Users\\x\\repo", True),
    ("C:/Users/x/repo", True),
    ("/c/Users/x/repo", True),
    (".", False),
    ("subdir", False),
    ("subdir/nested", False),
    ("", False),
]


@pytest.mark.parametrize("crp, expected", _IS_ABSOLUTE_CRP_CASES)
def test_is_absolute_crp_parity_between_read_and_write_paths(crp, expected):
    """Both copies must agree with each other AND with the expected verdict
    per input — agreement alone would pass if both drifted identically.

    ``goal_append`` is imported function-local (not module-scope) so this
    parity check — which deliberately couples the read-path test module to
    the write-path module — cannot destabilize pytest *collection* order for
    every other test in this file. A module-scope import here previously
    closed goal_append's own latent circular import (goal_append ->
    emit.envelope -> _wire_sections() -> emit.sections.goals -> goal_append)
    whenever this test module was collected before that cycle had a chance
    to resolve on a clean interpreter.
    """
    from coordinator_core.ops import goal_append as ga  # noqa: PLC0415

    assert rpt._is_absolute_crp(crp) == ga._is_absolute_crp(crp) == expected


def test_malformed_record_missing_workstream_id_raises_fail_loud(tmp_path):
    ws_dir = tmp_path / "state" / "workstreams"
    ws_dir.mkdir(parents=True)
    (ws_dir / "bad.yaml").write_text(
        f'title: "no id"\ncoordinator_root_path: "{_FAKE_ROOT}"\n',
        encoding="utf-8",
    )
    with pytest.raises(rpt._MalformedRecordError):
        rpt.render(str(tmp_path), _FAKE_ROOT)


# ---------------------------------------------------------------------------
# C1 reader-swap tests — schema_validate.parse_yaml + schema-directed
# normalization, replacing the deleted _load_yaml/_unquote_scalar.
# ---------------------------------------------------------------------------


def test_deliverable_with_comma_renders(tmp_path):
    ws_dir = tmp_path / "state" / "workstreams"
    ws_dir.mkdir(parents=True)
    (ws_dir / "wks-comma.yaml").write_text(
        textwrap.dedent(f"""\
            workstream_id: "wks-comma"
            title: "Comma workstream"
            created: "2026-07-10"
            coordinator_root_path: "{_FAKE_ROOT}"
            deliverables:
              - text: "Ship X, then ship Y, then done"
        """),
        encoding="utf-8",
    )
    rendered = rpt.render(str(tmp_path), _FAKE_ROOT)
    assert "Ship X, then ship Y, then done" in rendered


def test_deliverable_with_colon_renders(tmp_path):
    ws_dir = tmp_path / "state" / "workstreams"
    ws_dir.mkdir(parents=True)
    (ws_dir / "wks-colon.yaml").write_text(
        textwrap.dedent(f"""\
            workstream_id: "wks-colon"
            title: "Colon workstream"
            created: "2026-07-11"
            coordinator_root_path: "{_FAKE_ROOT}"
            deliverables:
              - text: "Run /example-game-repo:doctor"
        """),
        encoding="utf-8",
    )
    rendered = rpt.render(str(tmp_path), _FAKE_ROOT)
    assert "Run /example-game-repo:doctor" in rendered


def test_block_map_deliverable_renders_without_attribute_error(tmp_path):
    _write_store(tmp_path, _FAKE_ROOT)
    # _write_store already uses the block-map encoding throughout; a
    # successful render (no AttributeError) over it is itself the assertion.
    rendered = rpt.render(str(tmp_path), _FAKE_ROOT)
    assert "Ship the thing" in rendered


def test_numeric_workstream_id_and_all_digit_session_survive_as_str(tmp_path):
    ws_dir = tmp_path / "state" / "workstreams"
    events_dir = ws_dir / "events"
    ws_dir.mkdir(parents=True)
    events_dir.mkdir(parents=True)
    (ws_dir / "2026.yaml").write_text(
        textwrap.dedent(f"""\
            workstream_id: 2026
            title: "Numeric id workstream"
            created: "2026-07-12"
            coordinator_root_path: "{_FAKE_ROOT}"
        """),
        encoding="utf-8",
    )
    (events_dir / "2026-07-12-2026-session.yaml").write_text(
        textwrap.dedent(f"""\
            workstream: 2026
            field: "status"
            sequence: 1
            session: 12345
            value: "active"
            coordinator_root_path: "{_FAKE_ROOT}"
        """),
        encoding="utf-8",
    )
    rendered = rpt.render(str(tmp_path), _FAKE_ROOT)
    assert "Numeric id workstream" in rendered
    assert "**Status:** active" in rendered


def test_event_sequence_stays_int(tmp_path):
    ws_dir = tmp_path / "state" / "workstreams"
    events_dir = ws_dir / "events"
    ws_dir.mkdir(parents=True)
    events_dir.mkdir(parents=True)
    (ws_dir / "wks-seq.yaml").write_text(
        textwrap.dedent(f"""\
            workstream_id: "wks-seq"
            title: "Sequence workstream"
            created: "2026-07-13"
            coordinator_root_path: "{_FAKE_ROOT}"
        """),
        encoding="utf-8",
    )
    (events_dir / "2026-07-13-wks-seq-session.yaml").write_text(
        textwrap.dedent(f"""\
            workstream: "wks-seq"
            field: "status"
            sequence: 7
            session: "s1"
            value: "active"
            coordinator_root_path: "{_FAKE_ROOT}"
        """),
        encoding="utf-8",
    )
    events = rpt._load_events(str(tmp_path), _FAKE_ROOT)
    assert isinstance(events[0]["sequence"], int)
    assert events[0]["sequence"] == 7


def test_blank_workstream_id_raises_malformed_record(tmp_path):
    ws_dir = tmp_path / "state" / "workstreams"
    ws_dir.mkdir(parents=True)
    (ws_dir / "blank.yaml").write_text(
        textwrap.dedent(f"""\
            workstream_id:
            title: "Blank id"
            created: "2026-07-14"
            coordinator_root_path: "{_FAKE_ROOT}"
        """),
        encoding="utf-8",
    )
    with pytest.raises(rpt._MalformedRecordError):
        rpt.render(str(tmp_path), _FAKE_ROOT)


def test_numeric_specs_and_deliverable_text_coerce_to_str(tmp_path):
    ws_dir = tmp_path / "state" / "workstreams"
    ws_dir.mkdir(parents=True)
    (ws_dir / "wks-numeric.yaml").write_text(
        textwrap.dedent(f"""\
            workstream_id: "wks-numeric"
            title: "Numeric fields workstream"
            created: "2026-07-15"
            coordinator_root_path: "{_FAKE_ROOT}"
            specs:
              - 2026
            deliverables:
              - text: 2026
        """),
        encoding="utf-8",
    )
    # A successful render (no join/render TypeError) is itself the assertion.
    rendered = rpt.render(str(tmp_path), _FAKE_ROOT)
    assert "2026" in rendered


def test_event_value_true_round_trips_as_string_lowercase_true(tmp_path):
    ws_dir = tmp_path / "state" / "workstreams"
    events_dir = ws_dir / "events"
    ws_dir.mkdir(parents=True)
    events_dir.mkdir(parents=True)
    (ws_dir / "wks-bool.yaml").write_text(
        textwrap.dedent(f"""\
            workstream_id: "wks-bool"
            title: "Bool workstream"
            created: "2026-07-16"
            coordinator_root_path: "{_FAKE_ROOT}"
        """),
        encoding="utf-8",
    )
    (events_dir / "2026-07-16-wks-bool-session.yaml").write_text(
        textwrap.dedent(f"""\
            workstream: "wks-bool"
            field: "deliverable[0].done"
            sequence: 1
            session: "s1"
            value: true
            coordinator_root_path: "{_FAKE_ROOT}"
        """),
        encoding="utf-8",
    )
    events = rpt._load_events(str(tmp_path), _FAKE_ROOT)
    assert events[0]["value"] == "true"
    assert events[0]["value"] != "True"


def test_flow_map_deliverable_raises_named_error_not_attribute_error(tmp_path):
    ws_dir = tmp_path / "state" / "workstreams"
    ws_dir.mkdir(parents=True)
    (ws_dir / "wks-flowmap.yaml").write_text(
        textwrap.dedent(f"""\
            workstream_id: "wks-flowmap"
            title: "Flow-map workstream"
            created: "2026-07-17"
            coordinator_root_path: "{_FAKE_ROOT}"
            deliverables:
              - {{text: "retired encoding"}}
        """),
        encoding="utf-8",
    )
    with pytest.raises(rpt._RetiredFlowMapEncodingError):
        rpt.render(str(tmp_path), _FAKE_ROOT)


def test_malformed_event_non_integer_sequence_raises_fail_loud(tmp_path):
    ws_dir = tmp_path / "state" / "workstreams"
    events_dir = ws_dir / "events"
    events_dir.mkdir(parents=True)
    (events_dir / "bad-event.yaml").write_text(
        textwrap.dedent(f"""\
            workstream: "wks-x"
            field: "status"
            sequence: "not-a-number"
            session: "s1"
            value: "active"
            coordinator_root_path: "{_FAKE_ROOT}"
        """),
        encoding="utf-8",
    )
    with pytest.raises(rpt._MalformedRecordError):
        rpt.render(str(tmp_path), _FAKE_ROOT)


# ---------------------------------------------------------------------------
# Validator/renderer differential test — locks schema_validate (validate +
# parse) and the renderer's own parse path (_load_store_record) to agreeing
# on ONE deliverables encoding. The original defect (pre-C1/C8) was two
# hand-rolled YAML readers with complementary, non-overlapping subsets — the
# validator's took block-maps and rejected flow-maps, the renderer's was the
# exact inverse — so no single deliverables encoding satisfied both. This
# test feeds one fixture store through both readers and asserts they agree
# on the accept case and both reject the retired flow-map form, each in its
# own idiom (validate() reports {"ok": False, ...}; the renderer raises
# _RetiredFlowMapEncodingError) — closing off silent re-divergence in either
# direction.
# ---------------------------------------------------------------------------

from coordinator_core.frontmatter import schema_validate as sv  # noqa: E402

_BLOCK_MAP_STORE_TEXT = textwrap.dedent(f"""\
    workstream_id: "wks-differential"
    title: "Differential parity workstream"
    created: "2026-07-18"
    coordinator_root_path: "{_FAKE_ROOT}"
    specs:
      - "docs/plans/differential.md"
    deliverables:
      - text: "Ship the thing"
      - text: "Write the docs"
""")

_FLOW_MAP_STORE_TEXT = textwrap.dedent(f"""\
    workstream_id: "wks-differential-flow"
    title: "Differential parity workstream (flow-map)"
    created: "2026-07-18"
    coordinator_root_path: "{_FAKE_ROOT}"
    deliverables:
      - {{text: "Ship the thing"}}
      - {{text: "Write the docs"}}
""")


def test_validator_and_renderer_agree_on_block_map_deliverables(tmp_path):
    path = tmp_path / "wks-differential.yaml"
    path.write_text(_BLOCK_MAP_STORE_TEXT, encoding="utf-8")

    validator_parsed = sv.parse_yaml(_BLOCK_MAP_STORE_TEXT)
    validator_result = sv.validate("workstream", validator_parsed)
    assert validator_result == {"ok": True}, validator_result

    schema = rpt._cached_schema(rpt._DEFINITION_SCHEMA_FILE)
    renderer_parsed = rpt._load_store_record(str(path), schema)

    assert renderer_parsed["deliverables"] == validator_parsed["deliverables"]
    assert renderer_parsed["deliverables"] == [
        {"text": "Ship the thing"},
        {"text": "Write the docs"},
    ]


def test_flow_map_deliverables_rejected_by_both_readers_in_own_idiom(tmp_path):
    path = tmp_path / "wks-differential-flow.yaml"
    path.write_text(_FLOW_MAP_STORE_TEXT, encoding="utf-8")

    validator_parsed = sv.parse_yaml(_FLOW_MAP_STORE_TEXT)
    validator_result = sv.validate("workstream", validator_parsed)
    assert validator_result["ok"] is False
    assert any(
        "deliverables" in err["field"] for err in validator_result["errors"]
    )

    schema = rpt._cached_schema(rpt._DEFINITION_SCHEMA_FILE)
    with pytest.raises(rpt._RetiredFlowMapEncodingError):
        rpt._load_store_record(str(path), schema)


# ---------------------------------------------------------------------------
# main() CLI-contract tests
# ---------------------------------------------------------------------------


def test_main_writes_tracker_and_returns_zero(tmp_path):
    _write_store(tmp_path, _FAKE_ROOT)
    rc = rpt.main([str(tmp_path), _FAKE_ROOT])
    assert rc == 0
    out_path = tmp_path / "docs" / "project-tracker.md"
    assert out_path.is_file()
    assert "Alpha" in out_path.read_text(encoding="utf-8")


def test_main_wrong_argv_shape_returns_one(tmp_path, capsys):
    rc = rpt.main([str(tmp_path)])
    assert rc == 1
    captured = capsys.readouterr()
    assert "usage" in captured.err.lower()


def test_main_idempotent_two_consecutive_renders_byte_identical(tmp_path):
    _write_store(tmp_path, _FAKE_ROOT)
    rpt.main([str(tmp_path), _FAKE_ROOT])
    first = (tmp_path / "docs" / "project-tracker.md").read_text(encoding="utf-8")
    rpt.main([str(tmp_path), _FAKE_ROOT])
    second = (tmp_path / "docs" / "project-tracker.md").read_text(encoding="utf-8")
    assert first == second


# ---------------------------------------------------------------------------
# Zero-workstream truncation guard — break-class fix, 2026-07-25
# (example-market-data-repo repro: 157 curated lines -> 18-line stub, exit 0).
# ---------------------------------------------------------------------------


def test_main_zero_workstreams_refuses_to_overwrite_hand_curated_tracker(tmp_path, monkeypatch):
    monkeypatch.delenv(rpt._ALLOW_TRUNCATE_ENV, raising=False)
    docs_dir = tmp_path / "docs"
    docs_dir.mkdir()
    tracker_path = docs_dir / "project-tracker.md"
    hand_curated = "# Hand-curated tracker\n\nThis is NOT renderer output.\n"
    tracker_path.write_text(hand_curated, encoding="utf-8")

    rc = rpt.main([str(tmp_path), _FAKE_ROOT])

    # EXIT_NOT_APPLICABLE, never the business-fail 1 the usage error returns:
    # baton-assemble's d4 seam reads this code to tell "this repo is not
    # queue-backed" apart from a genuine renderer fault, and a caller that
    # cannot tell them apart treats a correct decline as transaction-fatal.
    assert rc == rpt.EXIT_NOT_APPLICABLE
    assert rc != 1
    assert tracker_path.read_text(encoding="utf-8") == hand_curated


def test_main_zero_workstreams_refusal_message_names_env_var(tmp_path, monkeypatch, capsys):
    """AC16: the message leads with freezing and states what the override
    discards — it must no longer read as an invitation to overwrite a
    curated tracker."""
    monkeypatch.delenv(rpt._ALLOW_TRUNCATE_ENV, raising=False)
    docs_dir = tmp_path / "docs"
    docs_dir.mkdir()
    (docs_dir / "project-tracker.md").write_text(
        "# Hand-curated tracker\n", encoding="utf-8"
    )

    rc = rpt.main([str(tmp_path), _FAKE_ROOT])

    assert rc == rpt.EXIT_NOT_APPLICABLE
    captured = capsys.readouterr()
    assert rpt._ALLOW_TRUNCATE_ENV in captured.err
    assert "freeze (archive) the curated tracker first, then re-render" in captured.err
    assert "PERMANENTLY DISCARDS" in captured.err
    assert str(tmp_path) in captured.err


def test_main_zero_workstreams_allow_truncate_env_bypasses_guard(tmp_path, monkeypatch):
    monkeypatch.setenv(rpt._ALLOW_TRUNCATE_ENV, "1")
    docs_dir = tmp_path / "docs"
    docs_dir.mkdir()
    tracker_path = docs_dir / "project-tracker.md"
    tracker_path.write_text("# Hand-curated tracker\n", encoding="utf-8")

    rc = rpt.main([str(tmp_path), _FAKE_ROOT])

    assert rc == 0
    overwritten = tracker_path.read_text(encoding="utf-8")
    assert rpt._GENERATED_MARKER_LINE in overwritten
    assert "Hand-curated" not in overwritten


def test_main_zero_workstreams_over_renderer_generated_tracker_succeeds(tmp_path, monkeypatch):
    monkeypatch.delenv(rpt._ALLOW_TRUNCATE_ENV, raising=False)
    docs_dir = tmp_path / "docs"
    docs_dir.mkdir()
    tracker_path = docs_dir / "project-tracker.md"
    # A prior renderer-generated tracker rendering empty again (a store that
    # genuinely emptied out) must still succeed — guard must not fire.
    tracker_path.write_text(
        f"---\ntitle: Project Tracker\n---\n\n{rpt._GENERATED_MARKER_LINE}\n",
        encoding="utf-8",
    )

    rc = rpt.main([str(tmp_path), _FAKE_ROOT])

    assert rc == 0
    assert rpt._GENERATED_MARKER_LINE in tracker_path.read_text(encoding="utf-8")


def test_main_zero_workstreams_no_existing_tracker_succeeds(tmp_path, monkeypatch):
    monkeypatch.delenv(rpt._ALLOW_TRUNCATE_ENV, raising=False)
    tracker_path = tmp_path / "docs" / "project-tracker.md"
    assert not tracker_path.exists()

    rc = rpt.main([str(tmp_path), _FAKE_ROOT])

    assert rc == 0
    assert tracker_path.is_file()
    assert rpt._GENERATED_MARKER_LINE in tracker_path.read_text(encoding="utf-8")


# ---------------------------------------------------------------------------
# C4: widened truncation guard — refuses the first overwrite of a
# hand-curated tracker regardless of section count (AC14), leaves every
# steady-state render unaffected (AC15), rewrites the refusal message
# (AC16), pins marker-detection across a marker-literal rename (AC25), and
# extends the guard to a zero-section regression over a previously
# non-trivial marker-bearing tracker (AC26).
# ---------------------------------------------------------------------------


def test_main_hand_curated_tracker_refuses_even_with_nonempty_store(tmp_path, monkeypatch):
    """AC14: this SUPERSEDES the guard's pre-C4 behaviour, where a render
    with one or more workstream sections always overwrote a hand-curated
    tracker unconditionally. That was the mint-then-render data-loss path
    (plan § C4) — minting a repo's first workstream disarmed the old
    zero-section-keyed guard and the next render destroyed the curated
    file. The widened guard refuses here instead."""
    monkeypatch.delenv(rpt._ALLOW_TRUNCATE_ENV, raising=False)
    _write_store(tmp_path, _FAKE_ROOT)
    docs_dir = tmp_path / "docs"
    docs_dir.mkdir()
    tracker_path = docs_dir / "project-tracker.md"
    hand_curated = "# Hand-curated tracker\n\nThis is NOT renderer output.\n"
    tracker_path.write_text(hand_curated, encoding="utf-8")

    rc = rpt.main([str(tmp_path), _FAKE_ROOT])

    assert rc == rpt.EXIT_NOT_APPLICABLE
    assert tracker_path.read_text(encoding="utf-8") == hand_curated


def test_main_hand_curated_tracker_refusal_names_freezing(tmp_path, monkeypatch, capsys):
    """AC14/AC16: the non-empty-store refusal names freezing as the fix,
    same message shape as the zero-section case."""
    monkeypatch.delenv(rpt._ALLOW_TRUNCATE_ENV, raising=False)
    _write_store(tmp_path, _FAKE_ROOT)
    docs_dir = tmp_path / "docs"
    docs_dir.mkdir()
    (docs_dir / "project-tracker.md").write_text(
        "# Hand-curated tracker\n", encoding="utf-8"
    )

    rc = rpt.main([str(tmp_path), _FAKE_ROOT])

    assert rc == rpt.EXIT_NOT_APPLICABLE
    captured = capsys.readouterr()
    assert "freeze (archive) the curated tracker first, then re-render" in captured.err
    assert "hand-curated and not yet queue-backed" in captured.err


def test_main_marker_bearing_tracker_renders_on_every_subsequent_run(tmp_path, monkeypatch):
    """AC15: the widened guard blocks no steady-state render — a
    marker-bearing tracker keeps rendering on every subsequent run."""
    monkeypatch.delenv(rpt._ALLOW_TRUNCATE_ENV, raising=False)
    _write_store(tmp_path, _FAKE_ROOT)
    rc1 = rpt.main([str(tmp_path), _FAKE_ROOT])
    assert rc1 == 0
    first = (tmp_path / "docs" / "project-tracker.md").read_text(encoding="utf-8")
    assert rpt._GENERATED_MARKER_LINE in first

    rc2 = rpt.main([str(tmp_path), _FAKE_ROOT])
    assert rc2 == 0
    second = (tmp_path / "docs" / "project-tracker.md").read_text(encoding="utf-8")
    assert first == second


def test_main_allow_truncate_env_overrides_nonempty_store_refusal(tmp_path, monkeypatch):
    """AC15: the existing escape hatch still overrides, even under the
    widened (non-empty-store) arm of the guard."""
    monkeypatch.setenv(rpt._ALLOW_TRUNCATE_ENV, "1")
    _write_store(tmp_path, _FAKE_ROOT)
    docs_dir = tmp_path / "docs"
    docs_dir.mkdir()
    tracker_path = docs_dir / "project-tracker.md"
    tracker_path.write_text("# Hand-curated tracker\n", encoding="utf-8")

    rc = rpt.main([str(tmp_path), _FAKE_ROOT])

    assert rc == 0
    overwritten = tracker_path.read_text(encoding="utf-8")
    assert "Alpha" in overwritten
    assert "Hand-curated" not in overwritten


def test_main_tracker_generated_under_previous_marker_text_still_reads_as_generated(
    tmp_path, monkeypatch
):
    """AC25: a tracker generated under the marker literal that predates
    C4's change (the pre-rename ``...render-project-tracker.sh`` pointer)
    still reads as generated — the guard matches the stable
    _GENERATED_MARKER_PREFIX, not the full marker sentence, so a fleet-wide
    rewording of the trailing pointer does not make every already-generated
    tracker read as hand-curated at once."""
    monkeypatch.delenv(rpt._ALLOW_TRUNCATE_ENV, raising=False)
    docs_dir = tmp_path / "docs"
    docs_dir.mkdir()
    tracker_path = docs_dir / "project-tracker.md"
    previous_marker_line = (
        "**Overall status:** generated from state/workstreams/ — "
        "see coordinator/bin/render-project-tracker.sh"
    )
    assert previous_marker_line != rpt._GENERATED_MARKER_LINE
    tracker_path.write_text(
        f"---\ntitle: Project Tracker\n---\n\n{previous_marker_line}\n",
        encoding="utf-8",
    )

    rc = rpt.main([str(tmp_path), _FAKE_ROOT])

    # Zero-workstream render over a tracker that reads as generated (via
    # the stable prefix) and carried zero sections previously — succeeds,
    # guard does not fire on either arm.
    assert rc == 0
    assert rpt._GENERATED_MARKER_LINE in tracker_path.read_text(encoding="utf-8")


def test_main_zero_section_render_over_previously_non_trivial_tracker_refuses(
    tmp_path, monkeypatch, capsys
):
    """AC26: a render yielding zero sections against a marker-bearing
    tracker that was previously non-trivial (rendered >=1 section before)
    is refused, not just the marker-less curated-file case — the
    2026-07-22 fold-correctness regression shape."""
    monkeypatch.delenv(rpt._ALLOW_TRUNCATE_ENV, raising=False)
    docs_dir = tmp_path / "docs"
    docs_dir.mkdir()
    tracker_path = docs_dir / "project-tracker.md"
    previously_rendered = (
        "---\ntitle: Project Tracker\n---\n\n"
        f"{rpt._GENERATED_MARKER_LINE}\n\n"
        "## Active Workstreams\n\n"
        "### 1. Alpha: quoting, commas\n"
        "**Status:** Ready\n\n"
        "- [ ] Ship the thing\n"
    )
    tracker_path.write_text(previously_rendered, encoding="utf-8")

    # No store under tmp_path at all -> this render yields zero sections,
    # regressing from the previously non-trivial (>=1 section) body above.
    rc = rpt.main([str(tmp_path), _FAKE_ROOT])

    assert rc == rpt.EXIT_RENDER_REGRESSION
    assert tracker_path.read_text(encoding="utf-8") == previously_rendered
    captured = capsys.readouterr()
    assert "freeze (archive) the curated tracker first, then re-render" in captured.err
    assert "previously carried one or more workstream sections" in captured.err


def test_main_zero_section_regression_over_non_matching_crp_names_offending_value(
    tmp_path, monkeypatch, capsys
):
    """C1(2)/C1's coordinator-claude-shape case: a marker-bearing tracker that previously
    had content, plus a definition carrying a NON-MATCHING
    coordinator_root_path (e.g. the coordinator-claude-side "coordinator_root_path:
    coordinator-claude" shape), regresses to zero sections and refuses via
    EXIT_RENDER_REGRESSION — and the extended silent-drop warning names the
    offending (path, stored) pair, not just the scanned/matched counts."""
    monkeypatch.delenv(rpt._ALLOW_TRUNCATE_ENV, raising=False)
    ws_dir = tmp_path / "state" / "workstreams"
    ws_dir.mkdir(parents=True)
    definition_path = ws_dir / "wks-doe.yaml"
    definition_path.write_text(
        textwrap.dedent("""\
            workstream_id: "wks-doe"
            title: "coordinator-claude-shape workstream"
            created: "2026-08-01"
            coordinator_root_path: "coordinator-claude"
        """),
        encoding="utf-8",
    )
    docs_dir = tmp_path / "docs"
    docs_dir.mkdir()
    tracker_path = docs_dir / "project-tracker.md"
    previously_rendered = (
        "---\ntitle: Project Tracker\n---\n\n"
        f"{rpt._GENERATED_MARKER_LINE}\n\n"
        "## Active Workstreams\n\n"
        "### 1. Alpha: quoting, commas\n"
        "**Status:** Ready\n\n"
        "- [ ] Ship the thing\n"
    )
    tracker_path.write_text(previously_rendered, encoding="utf-8")

    rc = rpt.main([str(tmp_path), _FAKE_ROOT])

    assert rc == rpt.EXIT_RENDER_REGRESSION
    assert tracker_path.read_text(encoding="utf-8") == previously_rendered
    captured = capsys.readouterr()
    assert "non-matching values:" in captured.err
    assert str(definition_path) in captured.err
    assert "coordinator-claude" in captured.err


def test_main_silent_success_over_non_matching_crp_still_warns_and_exits_zero(
    tmp_path, monkeypatch, capsys
):
    """C1(2)'s silent-success path: no on-disk tracker (or an
    empty/never-populated one) plus the same non-matching definition — the
    guard must NOT fire (unchanged behaviour, exit 0), but stderr must
    still name the offending value via the extended warning."""
    monkeypatch.delenv(rpt._ALLOW_TRUNCATE_ENV, raising=False)
    ws_dir = tmp_path / "state" / "workstreams"
    ws_dir.mkdir(parents=True)
    definition_path = ws_dir / "wks-doe.yaml"
    definition_path.write_text(
        textwrap.dedent("""\
            workstream_id: "wks-doe"
            title: "coordinator-claude-shape workstream"
            created: "2026-08-01"
            coordinator_root_path: "coordinator-claude"
        """),
        encoding="utf-8",
    )
    tracker_path = tmp_path / "docs" / "project-tracker.md"
    assert not tracker_path.exists()

    rc = rpt.main([str(tmp_path), _FAKE_ROOT])

    assert rc == 0
    assert tracker_path.is_file()
    captured = capsys.readouterr()
    assert "non-matching values:" in captured.err
    assert str(definition_path) in captured.err
    assert "coordinator-claude" in captured.err


def test_format_non_matching_values_caps_at_five_with_rest_count():
    """Review: code-reviewer d654b432 — the >5-pairs cap branch (`rest > 0`,
    the `[+ N more]` suffix) was untested; every prior caller only ever
    exercised the function with a single pair."""
    pairs = [(f"path{i}.yaml", f"stored{i}") for i in range(8)]

    rendered = rpt._format_non_matching_values(pairs)

    assert rendered.endswith(" [+ 3 more]")
    for i in range(5):
        assert f"path{i}.yaml={pairs[i][1]!r}" in rendered
    for i in range(5, 8):
        assert f"path{i}.yaml" not in rendered


def test_format_non_matching_values_no_suffix_at_or_under_five():
    """Companion to the cap test: exactly 5 pairs must NOT trigger the
    `[+ N more]` suffix (`rest > 0` is false, boundary case)."""
    pairs = [(f"path{i}.yaml", f"stored{i}") for i in range(5)]

    rendered = rpt._format_non_matching_values(pairs)

    assert "[+" not in rendered
    for i in range(5):
        assert f"path{i}.yaml={pairs[i][1]!r}" in rendered


def test_main_allow_truncate_env_overrides_zero_section_regression(tmp_path, monkeypatch):
    """AC15/AC26: the escape hatch still overrides the zero-section
    regression arm too."""
    monkeypatch.setenv(rpt._ALLOW_TRUNCATE_ENV, "1")
    docs_dir = tmp_path / "docs"
    docs_dir.mkdir()
    tracker_path = docs_dir / "project-tracker.md"
    tracker_path.write_text(
        "---\ntitle: Project Tracker\n---\n\n"
        f"{rpt._GENERATED_MARKER_LINE}\n\n"
        "## Active Workstreams\n\n"
        "### 1. Alpha: quoting, commas\n"
        "**Status:** Ready\n\n"
        "- [ ] Ship the thing\n",
        encoding="utf-8",
    )

    rc = rpt.main([str(tmp_path), _FAKE_ROOT])

    assert rc == 0
    assert "Alpha" not in tracker_path.read_text(encoding="utf-8")
