"""
coordinator_core.ops.verify_schema_registry_sync — SSOT drift gate: every
schemas/*.yaml (or *.schema.json) with an applies_to: must derive a query
type recognised by the registry.

Purpose: prevents the two-registry duplication problem (Substrate Fact #6)
from silently drifting. Adding a new schema without wiring it into
query-records.js TYPE_TO_GLOB (via _buildTypeToGlob schema derivation or an
explicit supplement) causes this check to fail loudly, making "add schema,
forget query-records" impossible.

How the check works: for each schemas/*.yaml|*.schema.json that carries an
applies_to: field, derive the expected query --type name (schema filename
sans suffix, renamed via the single-sourced
`coordinator_core.frontmatter.schema_validate._SCHEMA_NAME_TO_QUERY_TYPE`
map). The recognised-type set is derived natively via
`schema_validate.build_type_to_glob(schemas_dir)` — an in-process port of
query-records.js's own `_buildTypeToGlob()` registry derivation (loadSchemas
+ the same rename/override/supplement vendored contract) — and membership in
that map's keys IS the recognition check. No subprocess, no `node`.

De-node port (2026-07-22, DR-210 native-tooling-ownership strangler): this
module previously shelled out to `node bin/query-records.js --type X
--format json --limit 1` per schema and read the exit code. That spawn is
retired — `build_type_to_glob()` derives the SAME recognised-type set from
the SAME live schemas/ input `_buildTypeToGlob()` reads, so the check is
exit-code-equivalent to the old spawn without invoking node at all. See
`coordinator_core/frontmatter/tests/test_no_node_schema_shellout.py` (C8),
whose `_EXEMPT_NODE_ORACLE_CALLS` entry for this module is retired in the
same change.

Port of: verify-schema-registry-sync.sh (DoE b5a4192c, 2026-07-20); node-spawn
era ported from coordinator/bin/query-records.js (2026-07-22, see
schema_validate.py build_type_to_glob for the line-cited registry-derivation
port).
Spec backlink: docs/plans/2026-06-23-deliverable-type-schema-taxonomy.md
§ Decision 3 + C4 (DoE-claude repo).

Not a JSON-RPC op — a plain module, NOT @register_op'd, called by direct
import from the DoE-side polyglot trampoline (template-variant #1, mirrors
coordinator-auto-push / handoff-gate-aging).

Negative-spec (hard-won, faithfully reproduced from the .sh/node-spawn
original except where corrected below):
    - Does NOT compare applies_to glob values — only checks that a --type
      for the schema is a key in the natively-derived registry map.
    - Deliberate divergences (cross-repo-memo and handoff-archived) are
      exempted because their applies_to: globs intentionally differ from the
      TYPE_TO_GLOB override values. Their query types DO exist and would
      pass the recognition check; the exemption is kept for documentation
      consistency, not because the check would otherwise fail.
    - handoff-ledger is synthetic (no schema file) — not checked here.
    - GENERATED-NOT-VENDORED (Decision-0, 2026-07-24, plan
      docs/plans/2026-07-24-cross-repo-memo-ownership-and-redesign.md § C5):
      `cross-repo-memo.schema.json` on this gate's `schemas_dir`
      (`data_root("schemas")`, DoE-resident when not co-located) is now a
      DOWNSTREAM CONSUMED ARTIFACT of claude-klabauter's own emission —
      `coordinator_core.contract.emit_memo_schema.emit_schemas()` is the
      canonical regeneration path, mirroring the cockpit_schema precedent.
      `archived-memo.schema.json` is generated by the same module but is
      NOT listed in `_DELIBERATE_DIVERGENCES` below — its `applies_to`
      (`cross-repo/archive/*.md`) matches the `archived-memo` TYPE_TO_GLOB
      entry exactly (records_query.py), so it was never a glob-divergence
      case; only genuinely-diverging globs belong in this set. Neither
      generated file is registered into claude-klabauter's own
      `coordinator_core/frontmatter/schemas/` auto-load dir (see
      `emit_memo_schema`'s module docstring CRITICAL note) — this gate's
      `schemas_dir` is a wholly separate directory (DoE's/the shared
      plugin-distribution `coordinator/schemas/`), so that non-auto-load
      invariant is orthogonal to (and unaffected by) this check.
    - CORRECTED 2026-07-22 (false-positive fix, PM-ratified): bug-backlog,
      debt-backlog, and improvement-queue schemas were previously reported
      MISSING because this module's own `_LEGACY_TYPE_RENAMES` carried only
      2 of the registry's real 5 renames (completion-entry, lesson-entry),
      so those three schemas derived un-renamed types (bug-backlog,
      debt-backlog, improvement-queue) that the registry does not carry —
      it carries bug/debt/improvement (see
      schema_validate._SCHEMA_NAME_TO_QUERY_TYPE). This was two rename maps
      disagreeing, not a real drift; single-sourcing on the shared map (this
      module no longer keeps its own rename table) fixed it. These three
      schemas now PASS.
    - Uses a line-oriented `applies_to:` scan (first match, first line
      split on ": "), not a real YAML parser — mirrors the original's
      `grep '^applies_to:' | head -1 | awk -F': ' '{print $2}'` shape
      exactly, including its inability to handle a multi-line or
      block-scalar applies_to: value.
"""

from __future__ import annotations

import sys
from pathlib import Path
from typing import List, Optional, Tuple

from coordinator_core.data_root import data_root
from coordinator_core.frontmatter.schema_validate import (
    _SCHEMA_NAME_TO_QUERY_TYPE,
    build_type_to_glob,
)

_DELIBERATE_DIVERGENCES = frozenset(
    {"cross-repo-memo.yaml", "handoff-archived.yaml",
     "cross-repo-memo.schema.json", "handoff-archived.schema.json"}
)

# DR-047 schema-format-migration note (2026-07, DoE-claude commit 758de78b
# "schema: migrate 8 legacy .yaml schemas to first-class .schema.json"):
# DoE-claude's live schemas/ dir has since migrated ALL schema files from
# schemas/*.yaml to schemas/*.schema.json (JSON Schema, applies_to: still a
# top-level string field, now JSON-quoted rather than YAML-bare). Both
# extensions are recognised here so the gate keeps working across the
# migration boundary; *.yaml is retained for the unit-test fixtures in
# test_verify_schema_registry_sync.py (which still write bare-YAML *.yaml
# files) and for any repo that has not yet migrated.
_SCHEMA_SUFFIXES = (".schema.json", ".yaml")


def _schema_to_query_type(schema_name: str) -> str:
    """schema filename -> query --type name.

    Single-sourced on `schema_validate._SCHEMA_NAME_TO_QUERY_TYPE` — the
    SAME map `build_type_to_glob()` derives the registry from — rather than
    a locally hand-maintained rename table (the prior `_LEGACY_TYPE_RENAMES`
    carrying only 2 of 5 real renames was the false-positive bug this port
    fixes; see module docstring).

    lesson-entry maps to None in the canonical map (query-records.js
    excludes it from Part-1 derivation, handling it via a Part-2 supplement
    keyed 'lesson' instead — see build_type_to_glob) — reported here as
    'lesson' to match that supplement's actual query type name.
    """
    base = schema_name
    for suffix in _SCHEMA_SUFFIXES:
        if base.endswith(suffix):
            base = base[: -len(suffix)]
            break
    query_type = _SCHEMA_NAME_TO_QUERY_TYPE.get(base, base)
    return "lesson" if query_type is None else query_type


def _extract_applies_to(schema_file: Path) -> Optional[str]:
    """First `applies_to:` (YAML) or `"applies_to":` (JSON Schema) line's
    value, quotes/whitespace stripped.

    YAML mirrors: grep '^applies_to:' | head -1 | awk -F': ' '{print $2}' |
    tr -d '"' | tr -d "'" | tr -d '[:space:]'

    JSON Schema (post DR-047 *.schema.json migration) uses the same
    line-oriented-scan discipline -- first line matching `"applies_to":`
    (any leading whitespace, i.e. JSON indentation), value between the
    quotes that follow the colon, trailing comma tolerated.
    """
    try:
        text = schema_file.read_text(encoding="utf-8", errors="replace")
    except OSError:
        print(f"skip: _extract_applies_to: text = schema_file.read_text(encoding=\"utf-8\", errors=\"replace\") failed: {sys.exc_info()[1]}", file=sys.stderr)
        return None
    for line in text.splitlines():
        if line.startswith("applies_to:"):
            # Review: code-reviewer -- str.partition(": ") splits on the
            # FIRST occurrence only and keeps everything after it, which
            # diverges from `awk -F': ' '{print $2}'` (splits on EVERY
            # occurrence, keeps only field 2 -- i.e. up to the NEXT ": "
            # if the value itself contains one). str.split(": ") + index 1
            # matches awk's field-2-only semantics exactly.
            fields = line.split(": ")
            rest = fields[1] if len(fields) > 1 else ""
            value = rest.replace('"', "").replace("'", "")
            value = "".join(value.split())
            return value
        stripped = line.strip()
        if stripped.startswith('"applies_to"'):
            # JSON Schema line shape: "applies_to": "state/foo/*.yaml",
            fields = stripped.split(":", 1)
            rest = fields[1] if len(fields) > 1 else ""
            rest = rest.strip()
            if rest.endswith(","):
                rest = rest[:-1]
            value = rest.replace('"', "").replace("'", "")
            value = "".join(value.split())
            return value
    return None


def _schemas_with_applies_to(schemas_dir: Path) -> List[Path]:
    """Sorted-by-name union of schemas_dir's *.yaml/*.schema.json files, minus
    _DELIBERATE_DIVERGENCES, minus files with no applies_to: -- the exact
    corpus run() counts into `checked`. Single-sourced here so a golden-test
    corpus-size pin (test_verify_schema_registry_sync.py) can measure exactly
    what the gate covers, rather than reimplementing this filter and risking
    drift between the two (see cross-repo/archive/2026-07-22-claude-central-em-
    corrections-accepted-and-verify-schema-registry-golden-corpus-narrow.md)."""
    schema_files = sorted(
        {*schemas_dir.glob("*.yaml"), *schemas_dir.glob("*.schema.json")},
        key=lambda p: p.name,
    )
    result: List[Path] = []
    for schema_file in schema_files:
        if schema_file.name in _DELIBERATE_DIVERGENCES:
            continue
        if not _extract_applies_to(schema_file):
            continue
        result.append(schema_file)
    return result


def _type_recognised(type_to_glob: dict, query_type: str) -> bool:
    """True iff query_type is a key in the natively-derived {type: glob}
    registry map (see schema_validate.build_type_to_glob) — dict-membership
    replaces the prior `node query-records.js --type ...` subprocess spawn
    and its exit-code check."""
    return query_type in type_to_glob


def run(plugin_root: Path) -> Tuple[int, List[str], List[str]]:
    """Run the sync check. Returns (exit_code, stdout_lines, stderr_lines)."""
    schemas_dir = plugin_root / "schemas"

    stdout_lines: List[str] = []
    stderr_lines: List[str] = []

    if not schemas_dir.is_dir():
        stderr_lines.append(
            f"verify-schema-registry-sync: ERROR — schemas dir not found: {schemas_dir}"
        )
        return 1, stdout_lines, stderr_lines

    type_to_glob = build_type_to_glob(schemas_dir)

    missing: List[str] = []

    schema_files = _schemas_with_applies_to(schemas_dir)
    checked = len(schema_files)
    for schema_file in schema_files:
        schema_name = schema_file.name
        applies_to = _extract_applies_to(schema_file)
        query_type = _schema_to_query_type(schema_name)

        if not _type_recognised(type_to_glob, query_type):
            missing.append(
                f"{schema_name}: type='{query_type}' not recognised by query-records.js "
                f"(applies_to={applies_to})"
            )

    if not missing:
        stdout_lines.append(
            f"verify-schema-registry-sync: OK — all {checked} schema applies_to types "
            "are recognised by query-records.js"
        )
        return 0, stdout_lines, stderr_lines

    stderr_lines.append(
        f"verify-schema-registry-sync: FAIL — {len(missing)} schema(s) with applies_to: "
        "NOT recognised by query-records.js runtime:"
    )
    for item in missing:
        stderr_lines.append(f"  MISSING: {item}")
    stderr_lines.append("")
    stderr_lines.append(
        "Fix: ensure the schema type is registered in _buildTypeToGlob() or its "
        "supplements in bin/query-records.js"
    )
    stderr_lines.append(
        "Spec: docs/plans/2026-06-23-deliverable-type-schema-taxonomy.md § Decision 3"
    )
    return 1, stdout_lines, stderr_lines


def _resolve_plugin_root() -> Path:
    """coordinator/bin/verify-schema-registry-sync.py lives at <plugin_root>/bin/
    and passes its own resolved schemas-parent as argv[0] (see that script's own
    resolution via coordinator_data_root.data_root("schemas")). Standalone
    invocation (no argv[0] hint) resolves the SAME live schemas/ dir natively via
    `coordinator_core.data_root.data_root("schemas")` and returns its parent —
    the coordinator root containing that schemas/ dir, co-located or
    DoE-resident. Previously fell back to `Path.cwd()` (a plain `node` no-op
    search-failure analog); that stopped being correct once schemas/ moved to a
    split-repo layout unrelated to cwd. Raises RuntimeError (naming both rungs
    tried) if neither rung resolves — `main()` catches and reports rather than
    letting the schemas-dir-not-found message fire misleadingly later."""
    return data_root("schemas").parent


def main(argv: List[str]) -> int:
    if argv:
        plugin_root = Path(argv[0]).resolve()
    else:
        try:
            plugin_root = _resolve_plugin_root()
        except RuntimeError as exc:
            print(
                f"verify-schema-registry-sync: schemas dir resolution failed: {exc}",
                file=sys.stderr,
            )
            return 1
    exit_code, stdout_lines, stderr_lines = run(plugin_root)
    for line in stdout_lines:
        print(line)
    for line in stderr_lines:
        print(line, file=sys.stderr)
    return exit_code


if __name__ == "__main__":
    sys.exit(main(sys.argv[1:]))
