"""Generated persona/agent-identifier roster consumed by `attribution.patterns`.

Runtime code must never read DoE-claude's tree: `PERSONA_NAMES` and
`AGENT_IDENTIFIERS` below are frozen constants, regenerated by hand from DoE
`coordinator/agents/*.md` via `derive_persona_names` / `derive_agent_identifiers`
(pin-tested in `tests/test_roster_pin.py`, which is the only reader of DoE's
tree in this package). `EXTERNAL_PERSONA_NAMES` holds persona names that come
from a plugin-extension roster outside DoE-claude, never derived from DoE's own
agent files, so the pin test does not (and must not) enforce them.
"""
from __future__ import annotations

import re
from typing import Iterable

_DESCRIPTION_RE = re.compile(r'^description:\s*"(.*)"\s*$', re.MULTILINE)
_PERSONA_CLAUSE_RE = re.compile(r"Personas are Opus-only\.\s*(.*)")

# Leading tokens that read as capitalized but are never a persona's proper
# name — excluded so a generic role sentence ("Terminal subtractive pass: …")
# does not get misread as a name.
_CLAUSE_STOPWORDS = {"The", "A", "An", "This", "That", "Terminal", "Never", "Always"}


def _persona_clause(agent_text: str) -> str | None:
    """Return the sentence following "Personas are Opus-only." in an agent
    file's `description:` frontmatter field, or None when the file carries no
    such clause (a non-persona agent, e.g. a mechanical worker)."""
    match = _DESCRIPTION_RE.search(agent_text)
    if not match:
        return None
    clause_match = _PERSONA_CLAUSE_RE.search(match.group(1))
    if not clause_match:
        return None
    return clause_match.group(1)


def _name_from_clause(clause: str) -> str | None:
    """Extract the persona's proper name from the leading persona clause.

    Handles the four shapes seen in DoE's roster:
      "the VP-Product Reviewer (they/them), VP Product — …"     -> name before " ("
      "Angelique, APM — …"                 -> name before ","
      "Waste — Kira: is this code too …"    -> name between "—" and ":"
      "the Data Science Reviewer — data science, …"           -> name before " —"
      "the Front-End Reviewer reviews front-end code …"       -> name before a lowercase word
    Returns None for a role sentence carrying no persona name.
    """
    name: str | None = None
    m = re.match(r"^(\S+)\s+\(", clause)
    if m:
        name = m.group(1)
    if name is None:
        m = re.match(r"^(\S+),\s", clause)
        if m:
            name = m.group(1)
    if name is None:
        m = re.search(r"—\s*(\S+?):", clause)
        if m:
            name = m.group(1)
    if name is None:
        m = re.match(r"^(\S+)\s+—", clause)
        if m:
            name = m.group(1)
    if name is None:
        m = re.match(r"^(\S+)\s+[a-z]", clause)
        if m:
            name = m.group(1)
    if name is not None and name in _CLAUSE_STOPWORDS:
        return None
    return name


def derive_persona_names(agent_texts: Iterable[str]) -> tuple[str, ...]:
    """Derive the persona-name roster from DoE agent-file texts.

    Pure function: takes the full text of each `coordinator/agents/*.md`
    file, extracts the persona name from the leading persona clause of its
    `description:` field, and returns the deduplicated names in first-seen
    order. A file whose description carries no "Personas are Opus-only."
    clause, or whose clause names no one (a mechanical-role sentence),
    contributes nothing.
    """
    names: list[str] = []
    for text in agent_texts:
        clause = _persona_clause(text)
        if clause is None:
            continue
        name = _name_from_clause(clause)
        if name and name not in names:
            names.append(name)
    return tuple(names)


def derive_agent_identifiers(agent_stems: Iterable[str]) -> tuple[str, ...]:
    """Derive the agent-identifier roster from DoE agent-file stems.

    Pure function: takes each `coordinator/agents/*.md` file's stem (its
    filename without the `.md` suffix — the identifier a `Review:
    coordinator:<identifier>` annotation names) and returns the deduplicated
    stems, sorted for a stable, reviewable constant.
    """
    return tuple(sorted(set(agent_stems)))


# Regenerated 2026-09-26 from DoE-claude `coordinator/agents/*.md` via
# derive_persona_names() — see tests/test_roster_pin.py for the pin.
PERSONA_NAMES = (
    "Angelique",
    "the Data Science Reviewer",
    "the UX Reviewer",
    "Kira",
    "the Front-End Reviewer",
    "the Staff Engineer",
    "the VP-Product Reviewer",
    "the Director of Engineering",
)

# Persona names that come from a plugin-extension roster outside DoE-claude —
# the Game Dev Reviewer, from example-game-workbench-repo's `plugin/game-dev/agents/`. Never derived
# from DoE's own agent files, so test_roster_pin.py does not enforce these.
EXTERNAL_PERSONA_NAMES = ("the Game Dev Reviewer",)

# Regenerated 2026-09-26 from DoE-claude `coordinator/agents/*.md` stems via
# derive_agent_identifiers().
AGENT_IDENTIFIERS = (
    "apm",
    "atlas-clarity-reviewer",
    "atlassian-worker",
    "blitz-em",
    "code-reviewer",
    "code-reviewer-weekly",
    "coverage-auditor",
    "dep-cve-auditor",
    "doc-link-checker",
    "docs-checker",
    "drive-worker",
    "eng-director",
    "enricher",
    "executor",
    "exit-criterion-falsifier",
    "external-pattern-checker",
    "falsifier-integrity-reviewer",
    "git-commit-agent",
    "group-em-assistant",
    "notebooklm-research-scout",
    "overengineering-reviewer",
    "parallel-review-synthesizer",
    "plan-author",
    "plan-coverage-checker",
    "premise-checker",
    "prior-art-checker",
    "queue-grind-op-runner",
    "repo-scout",
    "repo-specialist",
    "research-scout",
    "research-specialist",
    "research-sweep",
    "research-synthesizer",
    "research-worker",
    "review-integrator",
    "security-audit-worker",
    "senior-front-end",
    "staff-data-sci",
    "staff-eng",
    "staff-ux",
    "structured-synthesizer",
    "subtractive-adjudicator",
    "test-evidence-parser",
    "test-runner",
    "vp-product",
    "workflow-maker",
)
