"""
coordinator_core.py_probe_sh -- the ONE POSIX-sh Python-interpreter-probe
snippet, shared by every emitted git-hook that needs to resolve python3 /
python / py from inside a `#!/bin/sh` body.

Purpose (ORIGIN, three sites): three independent call sites each hand-rolled
the same `command -v python3 || command -v python || command -v py` probe into
an EMITTED shell hook body (`coordinator_core.ops.install_meta_repo_precommit_hook`,
`coordinator_core.ops.install_claude_klabauter_precommit_hook`,
`coordinator.bin.lib.git_hook_install`). On Windows, PATH commonly resolves
those names first to Microsoft Store App Execution Alias stubs --
non-functional launchers -- so every one of those three probes would invoke
the stub instead of a real interpreter. `.cmd` launchers generated by
`gen-launcher-shim.py` already filter this (`findstr /I /C:"\\WindowsApps\\"`);
none of the three `sh`-emitted probes did, until 47c4c70b fixed the first of
the three (the meta-repo installer) and this module generalized that fix into
a shared primitive for the other two rather than a second and third hand-copy.

CURRENT CONSUMERS ARE THREE MODULES, FOUR CALL SITES -- NOT THE "THREE
INDEPENDENT call sites" the origin paragraph above names, and not the FOUR
this docstring itself asserted between 2026-08-2x and the C17 row of
`docs/plans/2026-08-21-the-cli-bootstrap-tax-dies-at-the-interpreter-floor.md`.
That earlier "four" count is now stale too: `coordinator_core.ops.
install_claude_klabauter_precommit_hook` converted off this primitive at C17 -- git's
own hook-exec contract still forces a shell for its emitted trampoline, but
that trampoline now bakes `sys.executable` at install time (a real
filesystem path the running installer already resolved) instead of walking
`$PATH` in shell, so it no longer calls `python_probe_lines` at all. Today's
callers: `coordinator.bin.lib.git_hook_install` (two sites),
`coordinator_core.ops.install_meta_repo_precommit_hook`, and
`coordinator_core.ops.install_doe_claude_precommit_hook` (DoE-claude's own
hook -- another repo's surface, out of C17's scope; see that plan's C17 row
for why only the claude-klabauter installer converts). Grep `python_probe_lines`
before quoting a count; this line drifts as consumers are added or removed
and is not a substitute for the grep.

`_is_store_python`-equivalent filtering is mirrored here (case-insensitive
`windowsapps` path-component check), not imported from
`coordinator_core.pyresolve` -- that module's `_is_store_python` runs
IN-PROCESS, on a candidate path a running Python interpreter already
resolved; this module has no process to run inside -- it emits TEXT that a
future `sh` process (git's hook runner) will interpret. The two mirror the
same defect class deliberately, per two disjoint consumer shapes -- see that
module's own docstring, "Two consumers".

Walking `$PATH` directory-by-directory per candidate name (rather than
rejecting a candidate NAME and falling through to the next name) is
load-bearing, and was established empirically (see 47c4c70b's commit
message), not by reasoning: on the realistic Windows topology the
WindowsApps stub and the real interpreter share a name (`python.exe`), so
"reject this name, try the next name" never reaches the real interpreter.
Directory-by-directory is also what the `.cmd` generator's own `where` loop
does. Do not regress to the simpler per-name-only shape.

Two emission shapes, one shared body:
    - `python_probe_lines(var)` -- newline-joined POSIX-sh source defining
      `_py_resolve()` and assigning `<var>="$(_py_resolve)"`. Used verbatim
      by both `_hook_body`-style standalone hooks (one call, own line) and
      spliced into a single-line `{ ...; }` append block (embedded newlines
      inside a semicolon-chained compound statement are valid POSIX sh --
      `sh` does not care whether a statement separator is `\\n` or `;`, and
      mixing the two within one script is unremarkable).

Not shared: the surrounding gate-execution / shim-body assembly machinery in
each of the three call sites. Each site's contract around WHAT runs after
python is resolved differs (gate registries with clamped exit codes vs. a
single target script with a self-heal fallback chain) -- see
`install_claude_klabauter_precommit_hook`'s own module docstring, "Kept as an
independent module", for why that surrounding machinery stays independently
duplicated even though this one probe snippet does not. Sharing only the
probe (not the whole gate-block shape) does not reintroduce the coupling
that docstring warns against.

Bootstrap-safety: stdlib only, zero external calls, zero subprocess -- same
contract as `coordinator_core.win_portability`, which this module sits
alongside rather than inside (that module's own scope is Python-side
path/exec primitives operating on real filesystem paths; this module emits
shell TEXT for a process that has not started yet -- a different concern).
"""

from __future__ import annotations

import sys

from coordinator_core.win_portability import split_path

__all__ = ["python_probe_lines", "baked_python_lines"]


def _sh_double_quote_escape(value: str) -> str:
    """Escape `value` for interpolation inside an sh double-quoted string."""
    for char in ("\\", '"', "$", "`"):
        value = value.replace(char, "\\" + char)
    return value


def baked_python_lines(var: str = "_py") -> str:
    # foreign-identity: OUT-OF-CLASS — the "claude-klabauter-59" citation at
    # line 143 below is prose inside this function's docstring, not
    # agent-facing rendered runtime text (per C6 brief note on this site)
    """Return POSIX-sh source assigning a BAKED interpreter path to `<var>`,
    instead of walking `$PATH` at hook-run time.

    Use this from an installer that is ITSELF running under the interpreter
    the emitted hook should use. Use `python_probe_lines` where that is not
    true and a candidate set genuinely must be walked when the hook fires.

    WHY THIS IS NOT A WEAKENING OF THE PROBE. Both of `python_probe_lines`'
    load-bearing behaviours are discharged BY CONSTRUCTION rather than
    reproduced: there is no candidate SET to walk, because `sys.executable`
    IS the interpreter the installer is already executing under; and there is
    no WindowsApps stub-vs-real collision to disambiguate, because a
    Microsoft Store App Execution Alias stub cannot be the process that is
    resolving this line. This is C17's shape
    (`install_claude_klabauter_precommit_hook._py_resolve_line`, 2026-08-21), lifted
    here so it outlives that module's deletion and so the hooks
    `coordinator.bin.lib.git_hook_install` emits can reach it.

    WHAT IT REMOVES. `python_probe_lines` emits `<var>="$(_py_resolve)"` — a
    command substitution, i.e. a SUBSHELL, wrapping nested loops over
    candidate names x `$PATH` entries x exe suffixes. That is one process per
    emitted hook, paid on every fire. Reported as a SPAWN COUNT rather than a
    duration deliberately: the per-hook delta sits at roughly one scheduler
    quantum on this box, and a process-time figure inside the quantum is not
    a result (DR-344 § the brightline; the predecessor plan was corrected for
    quoting one).

    THE WALK IS THE FALLBACK, NOT A CASUALTY — AND ON A FAIL-OPEN HOOK THAT IS
    LOAD-BEARING. A baked absolute path goes stale the moment Python is
    upgraded, a venv is rebuilt, or the hook is installed on a box where the
    recorded path does not exist. `[ -x "$<var>" ]` re-tests executability ONCE
    at hook-run time (not per-candidate), and on failure falls back to
    `_py_resolve` — so the emitted body still carries the walk and still finds
    an interpreter, paying its subshell ONLY when the bake is dead.

    Why that fallback is not optional here, stated because the obvious
    simplification is to drop it: `install_claude_klabauter_precommit_hook`'s C17 bake
    (this function's ancestor) lands on `pre-commit`, which fails CLOSED — a
    bad bake stops commits and forces a human to act, loudly. The hooks
    `git_hook_install` emits fail OPEN: an unresolved interpreter warns to
    stderr and `exit 0`s, so commits keep flowing without trailers and without
    a push. A bare bake there is not graceful degradation, it is a SILENT-OFF
    mode that presents exactly like "the engine already did this work" — and
    nothing goes red. C17's shape is therefore not portable to a fail-open
    hook without keeping a recovery rung; "C17 did it" does not survive the
    fail-open/fail-closed difference. (Finding raised by claude-klabauter-59's
    staff-eng review, 2026-08-25; the first revision of this function dropped
    the walk outright and would have shipped that fleet-wide.)

    Negative spec: this does NOT replace `python_probe_lines`, and that
    function's `$PATH` walk is not dead code.
    `install_doe_claude_precommit_hook` and `install_meta_repo_precommit_hook`
    emit hooks into OTHER repos, where the installing interpreter is not
    necessarily the one the emitted hook should run under. Repointing those
    is a cross-repo change needing their owners' sign-off, never a mechanical
    sweep from here.
    """
    baked = "/".join(split_path(sys.executable))
    walk = python_probe_lines(var)
    assignment = '{}="$(_py_resolve)"'.format(var)
    if not walk.endswith(assignment):  # pragma: no cover - emitter contract drift
        raise AssertionError(
            "python_probe_lines no longer ends with the {!r} assignment; "
            "baked_python_lines composes on that shape and must be updated "
            "with it rather than silently emitting a body without a "
            "fallback.".format(assignment)
        )
    function_only = walk[: -len(assignment)].rstrip("\n")
    return "\n".join(
        [
            function_only,
            '{}="{}"'.format(var, _sh_double_quote_escape(baked)),
            '[ -x "${}" ] || {}="$(_py_resolve)"'.format(var, var),
        ]
    )


def python_probe_lines(var: str = "_py") -> str:
    """Return POSIX-sh source (one string, internally newline-joined)
    defining `_py_resolve()` and assigning `<var>="$(_py_resolve)"`.

    `_py_resolve()` walks $PATH directory-by-directory, in candidate order
    python3 -> python -> py, testing both the bare name and a `.exe`-suffixed
    form per directory (MSYS/git-bash resolves the extension via
    `command -v` but a manual `-x` file test does not), and skips any hit
    whose resolved path contains a `windowsapps` path component
    (case-insensitive). No-op filtering on POSIX, where that path component
    never appears.

    The case-insensitive match is a literal `case` bracket-expression glob,
    NOT a `tr`-based case-fold, and that is load-bearing rather than
    stylistic: the filter must resolve zero external binaries. A `$(... |
    tr ...)` fold fails OPEN -- when `tr` is off the hook's PATH the command
    substitution yields the empty string, the `case` matches nothing, and the
    stub is selected, which is the exact defect this filter exists to
    prevent. Observed, not reasoned: the `tr` form returned the WindowsApps
    stub under a PATH carrying only the stub. Every construct emitted here is
    a `sh` builtin or reserved word.

    Prints the first surviving candidate's absolute path and
    returns 0; returns 1 (empty `<var>`) if nothing survives -- callers must
    already handle an empty `<var>` (missing-interpreter branch), unchanged
    from the pre-fix probe's own empty-on-failure contract.
    """
    return "\n".join(
        [
            "_py_resolve() {",
            '  _py_oldifs="$IFS"',
            "  for _py_cand in python3 python py; do",
            "    IFS=:",
            "    for _py_dir in $PATH; do",
            '      IFS="$_py_oldifs"',
            '      [ -n "$_py_dir" ] || continue',
            '      for _py_exe in "$_py_dir/$_py_cand" "$_py_dir/$_py_cand.exe"; do',
            '        [ -x "$_py_exe" ] || continue',
            '        case "$_py_exe" in',
            "          */[Ww][Ii][Nn][Dd][Oo][Ww][Ss][Aa][Pp][Pp][Ss]/*) continue ;;",
            "        esac",
            "        printf '%s' \"$_py_exe\"",
            '        IFS="$_py_oldifs"',
            "        return 0",
            "      done",
            "    done",
            "    IFS=:",
            "  done",
            '  IFS="$_py_oldifs"',
            "  return 1",
            "}",
            f'{var}="$(_py_resolve)"',
        ]
    )
