"""Coverage for ``fleet_env_lock``'s carry-forward mode and its permanent
banned-package check.

Carry-forward exists because ``--emit-lock`` requires every
``fleet-env-sources.toml`` row to resolve via the machine-local registry, and
not every box carries every contributing repo (``example_league_data_repo`` and
``experiments`` are absent from this box entirely — neither cloned nor
registered). Without a carry-forward mode, regenerating the union on such a
box would silently drop those sources' specs rather than fail or preserve
them. This module proves three things: strict mode is unchanged (still
fails), carry-forward reuses exactly the tagged lines already committed for
an unresolvable source, and the loud per-source notice actually names each
one carried.

It also proves the ``BANNED_PACKAGES`` gate: a source declaring a banned
package fails generation before any file is written, regardless of whether
``--carry-forward-unresolvable`` is set.

Spec backlink: this session's task — re-resolve the fleet shared environment
to drop chromadb (CVE-2026-45829) and its ``overrides`` transitive dep.
Contract: docs/reference/fleet-shared-environment-contract.md
"""
from __future__ import annotations

import pytest

from coordinator_core.install import fleet_env_lock


def _write_sources(tmp_path, rows):
    lines = []
    for row in rows:
        lines.append("[[source]]")
        for key, value in row.items():
            lines.append(f'{key} = "{value}"')
        lines.append("")
    path = tmp_path / "fleet-env-sources.toml"
    path.write_text("\n".join(lines), encoding="utf-8")
    return path


def test_strict_mode_still_fails_on_a_missing_source(tmp_path, monkeypatch):
    sources = _write_sources(tmp_path, [{"repo": "ghost_repo", "manifest": "pyproject.toml"}])
    monkeypatch.setattr(fleet_env_lock, "registry_get", lambda key: None)

    with pytest.raises(fleet_env_lock.FleetEnvLockError, match="ghost_repo"):
        fleet_env_lock.collect_specs(sources)


def test_run_strict_mode_still_fails_on_a_missing_source(tmp_path, monkeypatch):
    sources = _write_sources(tmp_path, [{"repo": "ghost_repo", "manifest": "pyproject.toml"}])
    out = tmp_path / "fleet-env-requirements.in"
    monkeypatch.setattr(fleet_env_lock, "registry_get", lambda key: None)

    with pytest.raises(fleet_env_lock.FleetEnvLockError, match="ghost_repo"):
        fleet_env_lock.run(sources_path=sources, requirements_in_path=out)
    assert not out.exists()


def test_carry_forward_reuses_exactly_the_tagged_lines(tmp_path, monkeypatch):
    sources = _write_sources(
        tmp_path,
        [
            {"repo": "resolvable_repo", "manifest": "pyproject.toml"},
            {"repo": "ghost_repo", "manifest": "engine/pyproject.toml"},
        ],
    )
    existing_in = tmp_path / "fleet-env-requirements.in"
    existing_in.write_text(
        "\n".join(
            [
                "# GENERATED by coordinator_core.install.fleet_env_lock",
                "",
                "pandas>=2.2  # ghost_repo:engine/pyproject.toml",
                "transformers>=4.41  # ghost_repo:engine/pyproject.toml",
                "unrelated>=1.0  # some_other_repo:pyproject.toml",
                "",
            ]
        ),
        encoding="utf-8",
    )

    repo_root = tmp_path / "resolvable_repo"
    repo_root.mkdir()
    (repo_root / "pyproject.toml").write_text(
        '[project]\ndependencies = ["requests>=2.31"]\n', encoding="utf-8"
    )

    def fake_registry_get(key: str):
        if key == "repos.resolvable_repo":
            return str(repo_root)
        return None

    monkeypatch.setattr(fleet_env_lock, "registry_get", fake_registry_get)

    pairs = fleet_env_lock.collect_specs(
        sources,
        carry_forward_unresolvable=True,
        existing_requirements_in_path=existing_in,
    )

    assert ("requests>=2.31", "resolvable_repo:pyproject.toml") in pairs
    assert ("pandas>=2.2", "ghost_repo:engine/pyproject.toml") in pairs
    assert ("transformers>=4.41", "ghost_repo:engine/pyproject.toml") in pairs
    assert not any(spec.startswith("unrelated") for spec, _ in pairs)


def test_carry_forward_notice_names_each_carried_source(tmp_path, monkeypatch, capsys):
    sources = _write_sources(
        tmp_path,
        [
            {"repo": "ghost_one", "manifest": "pyproject.toml"},
            {"repo": "ghost_two", "manifest": "review/pyproject.toml"},
        ],
    )
    existing_in = tmp_path / "fleet-env-requirements.in"
    existing_in.write_text(
        "\n".join(
            [
                "click>=8.0  # ghost_one:pyproject.toml",
                "rich>=13.0  # ghost_two:review/pyproject.toml",
                "",
            ]
        ),
        encoding="utf-8",
    )
    monkeypatch.setattr(fleet_env_lock, "registry_get", lambda key: None)

    fleet_env_lock.collect_specs(
        sources,
        carry_forward_unresolvable=True,
        existing_requirements_in_path=existing_in,
    )

    captured = capsys.readouterr()
    assert "carried forward from the committed .in, not re-read: ghost_one:pyproject.toml" in captured.err
    assert (
        "carried forward from the committed .in, not re-read: ghost_two:review/pyproject.toml"
        in captured.err
    )


def test_carry_forward_without_an_existing_in_file_fails_loud(tmp_path, monkeypatch):
    sources = _write_sources(tmp_path, [{"repo": "ghost_repo", "manifest": "pyproject.toml"}])
    missing_in = tmp_path / "does-not-exist.in"
    monkeypatch.setattr(fleet_env_lock, "registry_get", lambda key: None)

    with pytest.raises(fleet_env_lock.FleetEnvLockError, match="carry-forward"):
        fleet_env_lock.collect_specs(
            sources,
            carry_forward_unresolvable=True,
            existing_requirements_in_path=missing_in,
        )


def test_banned_package_blocks_requirements_in_generation(tmp_path, monkeypatch):
    sources = _write_sources(tmp_path, [{"repo": "bad_repo", "manifest": "pyproject.toml"}])
    repo_root = tmp_path / "bad_repo"
    repo_root.mkdir()
    (repo_root / "pyproject.toml").write_text(
        '[project]\ndependencies = ["chromadb>=1.4,<1.5"]\n', encoding="utf-8"
    )
    monkeypatch.setattr(
        fleet_env_lock, "registry_get", lambda key: str(repo_root) if key == "repos.bad_repo" else None
    )
    out = tmp_path / "fleet-env-requirements.in"

    with pytest.raises(fleet_env_lock.FleetEnvLockError, match="chromadb"):
        fleet_env_lock.run(sources_path=sources, requirements_in_path=out)
    assert not out.exists()


def test_banned_package_blocks_lock_generation_even_if_not_in_requirements_in(tmp_path, monkeypatch):
    req_in = tmp_path / "fleet-env-requirements.in"
    req_in.write_text("foo>=1  # some_repo:pyproject.toml\n", encoding="utf-8")
    overrides = tmp_path / "fleet-env-overrides.toml"
    overrides.write_text("", encoding="utf-8")
    lock_out = tmp_path / "fleet-env.lock"

    def fake_run(argv, **kwargs):
        from pathlib import Path

        project_dir = Path(kwargs["cwd"])
        (project_dir / "uv.lock").write_text(
            '[[package]]\nname = "foo"\nversion = "1.0.0"\n\n'
            '[[package]]\nname = "chromadb"\nversion = "1.4.1"\n',
            encoding="utf-8",
        )

        class _FakeResult:
            returncode = 0
            stderr = ""

        return _FakeResult()

    monkeypatch.setattr(fleet_env_lock.subprocess, "run", fake_run)

    with pytest.raises(fleet_env_lock.FleetEnvLockError, match="chromadb"):
        fleet_env_lock.generate_lock(
            requirements_in_path=req_in, overrides_path=overrides, lock_path=lock_out
        )
    assert not lock_out.exists()
