"""coordinator_core.install.door_install -- installs the native warm-engine
door as the on-PATH `coordinator-invoke` entrypoint.

Spec backlink: state/handoffs/2026-08-21_103635_reaching-the-warm-engine.md

WHY A DEDICATED STEP, NOT THE GENERIC `coordinator/bin/` SCAN. The
existing `coordinator-invoke.cmd` + extensionless Unix-half forwarder pair
in settings-home `bin/` is auto-generated by `substrate.py ::
_derive_agent_helper_target_map` scanning `coordinator/bin/` for Python-
source CLIs and writing a matching launcher for each. That scan assumes
its target is source Python it can `exec_cli()` into; `.exe` is not among
`_AGENT_HELPER_DATA_SUFFIXES`'s exclusions, so a raw compiled `door.exe`
dropped into `coordinator/bin/` would be MIS-processed by that machinery
rather than skipped, not correctly installed by it. The door needs its
own step.

WHY `coordinator-invoke.exe`, SPECIFICALLY, WINS THE BARE NAME ON WINDOWS.
Verified live on this box (2026-08-21), not assumed:

  - PATHEXT here is `.COM;.EXE;.BAT;.CMD;...` -- `.EXE` outranks `.CMD`.
    Confirmed BOTH cmd.exe and PowerShell resolve a bare name to a same-
    directory `.exe` over a `.cmd`/extensionless sibling (isolated test,
    temp dir, PATH-prepended only for that one call). This is also why the
    `coordinator-invoke.cmd` sibling `install_bin_forwarders` writes is
    harmless dead weight once the door is installed, not a fixed hazard:
    it is never reached by a bare `coordinator-invoke` invocation on a box
    that also carries the door's `.exe` in the same directory, PATHEXT
    ranking settling the collision before this module has to. Its BODY
    would still be wrong if it WERE reached post-door-install (it execs
    the co-located extensionless sibling through python, and that sibling
    is the door's native binary once installed, not the python trampoline
    it was written to invoke) -- reachability, not correctness, is what
    makes it safe to leave alone.
  - PowerShell's resolution ranks a `.ps1` sibling ABOVE `.exe` if one
    exists (matches `coordinator-invoke.cmd`'s own header warning). This
    WAS a hypothetical, kept-true-by-absence constraint when this
    docstring was first written; it stopped being one the moment
    `install_bin_forwarders` started deriving a `coordinator-invoke.ps1`
    forwarder from `coordinator/bin/coordinator-invoke.py` (both land in
    the SAME settings-home `bin/` this module installs into, one second
    apart in a single `scripts/setup.py` run, live-measured
    2026-08-22) -- a `.ps1` sibling is now a certainty on every install,
    not an absence to keep true. `install_door()` below removes that one
    shadowing sibling on every successful install so the constraint holds
    by construction instead of by accident; see
    `_remove_shadowing_forwarder_siblings`'s own docstring. `.cmd` needs no
    matching removal for the PATHEXT reason above; POSIX has no PATHEXT
    step and no `.ps1` bare-name resolution of its own, but a `.ps1` file
    left in the same directory is inert weight there too, not a distinct
    hazard, and removing it uniformly (not just under `sys.platform ==
    "win32"`) is simpler than adding a platform branch to a one-line
    unlink for a file this module already knows the exact name of.
  - `~/.coordinator-claude-settings/bin` sits EARLIER on PATH than
    `<interpreter>/Scripts`, where the pip/editable-install
    `coordinator-invoke.exe` console-script entrypoint already lives
    (`docs/install/agent-install-manifest.json`'s own
    `coordinator_invoke_console_script` prerequisite entry) -- so
    settings-home `bin/` is the correct install target: directory order
    on PATH decides before same-directory PATHEXT ranking ever applies.

WHY THE BARE EXTENSIONLESS `coordinator-invoke` ON POSIX. POSIX has no
PATHEXT -- there is no extension-ranking step at all, so the bare name IS
the file name, not a stem an extension gets appended to. The only ranking
question left is directory order on PATH, same axis as the Windows case
above: settings-home `bin/` must precede whatever other `coordinator-invoke`
a `pip`/editable install might place on PATH, for the same reason it must
precede `<interpreter>/Scripts` on Windows -- the settings-home entry is
the one meant to win. `shutil.copy2` preserves the source file's mode bits
(including the exec bit) across the copy, so a prebuilt `door` copied in
this way stays executable with no extra `chmod`; a binary produced by a
FRESH compile on this box, rather than copied, is not guaranteed to come
out of the compiler with the exec bit set and must have it set explicitly.

NOT THE INTERACTIVE LAUNCH CHAIN. `docs/reference/interactive-launch-
chain.md`'s "direct child" invariant is scoped to `claude.exe` itself
being spawned directly by the operator's shell. `coordinator-invoke`
dispatch is a separate subsystem -- a subprocess invoked from inside an
already-running session or a hook, never part of that chain. Confirmed by
the PM-adjacent EM on this dispatch; not re-litigated here.

WHY A PREBUILT BINARY, NOT COMPILING AT INSTALL TIME. No install box can
be assumed to carry clang or MSVC -- requiring one would make a C
compiler a NEW install-chain dependency for every coordinator install,
which is the exact class of problem `warm/door/build.py`'s own runtime-
sidecar revision existed to avoid for the ENGINE ROOT. `install_door()`
therefore prefers the committed `coordinator_core/warm/door/door.exe`,
falling back to compiling from source only when no prebuilt is present
(e.g. a from-scratch dev checkout that has never run the door build).

VERIFYING THE COMMITTED BINARY MATCHES ITS COMMITTED SOURCE. Two pieces,
per the PM's own ruling on this ("rebuild it yourself and see it work;
here is the source hash it came from" -- explicitly NOT bit-for-bit
determinism across different compilers/toolchains, which is out of
scope):

  1. `build.py :: write_provenance()` records, next to every compiled
     `door.exe`, a `<name>.provenance.json` carrying the SHA-256 of the
     `door.c` it was built from, plus the compiler and its version.
     Committed alongside the binary -- a mismatch between that recorded
     hash and the CURRENT `door.c` is detectable with one `sha256sum`,
     by anyone, without needing a compiler at all.
  2. `build.py :: verify_reproducible()` (also `build.py --verify`'s CLI
     mode; `rebuild_and_verify_prebuilt()` below is a same-named
     re-export) goes further: actually rebuilds from the current source
     and hash-compares the RESULT against the committed binary. This
     needs the SAME compiler installed, and relies on `_compile()`'s
     `/Brepro` linker flag (verified directly, 2026-08-21: without it,
     two back-to-back builds from byte-identical `door.c` differed in
     SHA-256; with it, they matched exactly).

Neither runs automatically on every install (that would reintroduce the
compiler dependency this whole design avoids) -- both are CI/audit-time
checks, not install-time ones.

`bin_dst` IS ALWAYS AN EXPLICIT PARAMETER, never resolved internally via
`coordinator_core._settings_home.settings_home()`. This is what makes
`install_door()` trivially testable against a scratch directory instead
of the live, ~40-concurrent-session settings-home -- see this module's
own tests.

WIRED, NOT DEFERRED. This paragraph used to end "wiring a call to this
function into substrate.py's real install flow is a separate,
deliberately-deferred decision: this module only builds the capability."
That stopped being true and read as authoritative long after it did.
Both routes are live: `scripts/setup.py :: install_warm_door` calls
`install_door()`, and `substrate.py :: _write_native_door_forwarder`
calls `install_named_forwarder()` for every door-eligible name (C5,
docs/plans/2026-08-26-every-forwarder-that-can-reach-the-door-does.md).
"""

from __future__ import annotations

import argparse
import filecmp
import hashlib
import json
import os
import shutil
import sys
import time
from pathlib import Path
from typing import Iterable, NamedTuple, Optional

from coordinator_core.warm.door import build as door_build
from coordinator_core.warm.engine_root import is_engine_root

__all__ = [
    "BARE_FORWARDER_NAME",
    "DOOR_INSTALLED_NAME",
    "install_door",
    "is_door_installed",
    "installed_provenance_path",
    "verify_installed_provenance",
    "ProvenanceVerdict",
    "ImageCurrencyAudit",
    "audit_installed_image_currency",
    "rebuild_and_verify_prebuilt",
    "named_forwarder_path",
    "install_named_forwarder",
    "remove_shadowing_ps1_sibling",
    "remove_superseded_python_forwarders",
]

#: Installed name is platform-resolved, not a single `.exe`-spelled
#: literal: POSIX's `coordinator-invoke` carries no extension (there is no
#: PATHEXT to rank one against), Windows keeps `coordinator-invoke.exe` for
#: the reasons the module docstring's Windows paragraph gives.
DOOR_INSTALLED_NAME = "coordinator-invoke.exe" if sys.platform == "win32" else "coordinator-invoke"

#: The platform-INVARIANT bare identity `coordinator-invoke` derives from --
#: `DOOR_INSTALLED_NAME` above minus the Windows-only `.exe` suffix, and
#: also the installed-forwarder NAME `_derive_agent_helper_target_map`
#: (substrate.py) resolves for `coordinator/bin/coordinator-invoke.py` on
#: EVERY platform (only the `.py` suffix is stripped there -- see that
#: function's own docstring). Named once so `install_door()`'s shadow-sibling
#: removal and `door_uninstall`'s fallback-forwarder re-emission agree on
#: the same string without either re-deriving it from `DOOR_INSTALLED_NAME`.
BARE_FORWARDER_NAME = "coordinator-invoke"

#: Sibling suffixes `install_bin_forwarders` (substrate.py Step 3b) writes
#: alongside the bare `coordinator-invoke` forwarder that can WIN bare-name
#: resolution over the door once installed -- see the module docstring's
#: Windows paragraph for why `.ps1` qualifies and `.cmd` does not.
_SHADOWING_SIBLING_SUFFIXES = (".ps1",)

_DOOR_DIR = Path(__file__).resolve().parents[1] / "warm" / "door"

#: Prebuilt lookup + provenance filenames follow each platform's OWN build
#: module's output convention -- `build.py`'s default output is `door.exe`
#: (provenance `door.exe.provenance.json`), `build_posix.py`'s default
#: output is the extensionless `door` (provenance `door.provenance.json`).
#: Both are committed at `_DOOR_DIR`; this module only picks the pair that
#: matches the platform it is running on.
_PREBUILT_DOOR_EXE = _DOOR_DIR / ("door.exe" if sys.platform == "win32" else "door")
_PREBUILT_PROVENANCE = _DOOR_DIR / (
    "door.exe.provenance.json" if sys.platform == "win32" else "door.provenance.json"
)


class DoorInstallError(RuntimeError):
    """Raised by `install_door()` on a fatal precondition -- an invalid
    `engine_root`, or (check-only mode) a stale/absent install."""


def rebuild_and_verify_prebuilt(
    *,
    engine_root: Path,
    python_bin: Optional[Path] = None,
    compiler: Optional[str] = None,
    prebuilt: Path = _PREBUILT_DOOR_EXE,
) -> bool:
    """Thin delegate to `door_build.verify_reproducible()` -- the single
    canonical implementation lives there (it is also `build.py --verify`'s
    own CLI mode) so this module does not carry a second copy of the
    rebuild-and-hash-compare logic to drift out of sync with it. Kept as
    a re-export here because `install_door()`'s own docstring and this
    module's callers reference it by this name.
    """
    return door_build.verify_reproducible(
        engine_root, python_bin=python_bin, compiler=compiler, prebuilt=prebuilt
    )


def is_door_installed(bin_dst: Path) -> bool:
    """Non-raising presence check: True iff both `DOOR_INSTALLED_NAME` and
    its engine-root sidecar already exist at `bin_dst`. Same presence test
    `install_door(check_only=True)` runs, but returns a bool instead of
    raising `DoorInstallError` on absence -- a sibling, not a wrapper,
    added for callers (C4's step) that need to branch on presence rather
    than catch control flow out of `install_door`."""
    bin_dst = Path(bin_dst)
    dest_exe = bin_dst / DOOR_INSTALLED_NAME
    dest_sidecar = bin_dst / door_build.SIDECAR_FILENAME
    return dest_exe.exists() and dest_sidecar.exists()


def _prebuilt_image_bytes() -> bytes:
    """The committed prebuilt's bytes -- the single currency oracle, read
    through one function so its unreadable case has ONE convention.

    Both currency checks (`verify_installed_provenance`'s `stale` leg and
    `audit_installed_image_currency`) compare installed bytes against this
    file, and each previously opened it with its own `except OSError`.
    They disagreed: one returned a status, the other raised, so a checkout
    shipping no prebuilt for its platform made `check_door_provenance`
    print a clean line while `check_settings_home` FAILED loudly on the
    identical cause. That divergence is what produced the `unverifiable`
    defect -- and it was patched on one side only, because there was no one
    side to patch. Raising is the convention; a caller that must not fail
    maps the exception to its own status explicitly, in view of this
    contract rather than beside it.
    """
    try:
        return _PREBUILT_DOOR_EXE.read_bytes()
    except OSError as exc:
        raise DoorInstallError(
            f"door_install: no readable prebuilt at {_PREBUILT_DOOR_EXE}: {exc}"
        ) from exc


def installed_provenance_path(bin_dst: Path) -> Path:
    """The provenance sidecar path `install_door()` writes/copies its
    provenance record to: `DOOR_INSTALLED_NAME` plus a `.provenance.json`
    suffix, e.g. `coordinator-invoke.exe.provenance.json` on Windows.

    Named once so the naming convention exists in exactly one place --
    `door_uninstall.py :: _provenance_path` used to derive this identical
    path independently; it now delegates here instead of carrying a second,
    driftable copy of the same one-line derivation."""
    return Path(bin_dst) / (DOOR_INSTALLED_NAME + ".provenance.json")


class ProvenanceVerdict(NamedTuple):
    """Result of `verify_installed_provenance()` -- `status` is one of
    `"no-door"`, `"absent"`, `"unrecorded"`, `"mismatch"`, `"stale"`,
    `"unverifiable"`, `"ok"` (see that function's own docstring); `detail` is a human-readable
    explanation."""

    status: str
    detail: str


def verify_installed_provenance(bin_dst: Path) -> ProvenanceVerdict:
    """Checks the installed door binary's ACTUAL bytes against the hash its
    own provenance sidecar claims for them -- the only check that can catch
    a sidecar describing a binary that is no longer there.

    WHY THE RECORD'S OWN FIELD IS THE ORACLE, NOT MTIME. `shutil.copy2`
    preserves the SOURCE file's mtime across a copy, so an installed
    sidecar's mtime routinely predates the install that placed it there --
    that staleness-that-looks-like-freshness is exactly what made a stale
    sidecar read as plausible on 2026-08-30 (see `build.py ::
    write_provenance`'s `image_sha256` paragraph for the full incident).
    mtime answers "when was this file last written", never "does this file
    still describe the binary beside it" -- only a content hash recorded
    IN the sidecar and re-derived FROM the binary can answer that.

    Five statuses, deliberately not collapsed into a bool:
      - `"no-door"` -- no installed door binary at
        `bin_dst / DOOR_INSTALLED_NAME`. Nothing to verify.
      - `"absent"` -- door present, sidecar missing, unreadable, or not
        valid JSON.
      - `"unrecorded"` -- sidecar present and parseable but carries no
        `image_sha256` (a record written before this field existed). This
        CANNOT be checked, and is reported as such -- it must never be
        read as a pass.
      - `"mismatch"` -- `image_sha256` present and differs from the
        installed binary's actual sha256. `detail` names both hashes and
        both paths, so a reader never has to re-derive either by hand.
      - `"stale"` -- sidecar and binary agree with EACH OTHER, but the
        binary is not the build this tree ships at `_PREBUILT_DOOR_EXE`.
      - `"unverifiable"` -- sidecar and binary agree, and the currency
        question could not be ASKED: no readable prebuilt in this checkout
        (a platform this tree ships no `door`/`door.exe` for). Distinct
        from `"ok"` on purpose -- see below.

    INTERNAL CONSISTENCY IS NOT CURRENCY, AND THE STALE CASE SATISFIES IT.
    The four statuses above answer "does the sidecar describe the binary
    beside it" -- a question a build-behind install passes cleanly, because
    the installer copies exe and sidecar together and a stale PAIR is
    perfectly self-consistent. That is how a door image one build behind
    the fix that shipped for it read as `ok` here while `cross-repo-memo`
    hung on the missing `COORDINATOR_DOOR_STDIN_MODE` gate (2026-09-01).
    The oracle for currency is the committed prebuilt, never the sidecar,
    so the `"stale"` leg below re-derives against `_PREBUILT_DOOR_EXE`
    rather than against anything the install itself wrote.

    AN UNANSWERABLE CURRENCY QUESTION IS ITS OWN STATUS, NOT `ok`. An
    unreadable prebuilt used to fall through to `ok` here, which is exactly
    the shape the paragraph above condemns: the caller cannot tell "verified
    current" from "could not look", and `install_health_run ::
    check_door_provenance` printed the same clean line for both while
    `settings_home_report.check_settings_home`'s currency leg FAILED loudly
    on the identical root cause. Two sibling gates, opposite verdicts, one
    condition. It returns `"unverifiable"` instead -- reported, never a pass,
    and (like `"unrecorded"`) not a fleet-wide failure either, since failing
    every box whose platform ships no prebuilt would fail the fleet rather
    than the defect.
    """
    bin_dst = Path(bin_dst)
    dest_exe = bin_dst / DOOR_INSTALLED_NAME
    if not dest_exe.exists():
        return ProvenanceVerdict("no-door", f"no door binary at {dest_exe}")

    provenance_path = installed_provenance_path(bin_dst)
    try:
        record = json.loads(provenance_path.read_text(encoding="utf-8"))
    except (OSError, json.JSONDecodeError) as exc:
        return ProvenanceVerdict(
            "absent", f"sidecar missing or unreadable at {provenance_path}: {exc}"
        )

    recorded = record.get("image_sha256")
    if not recorded:
        return ProvenanceVerdict(
            "unrecorded",
            f"{provenance_path} carries no image_sha256 -- predates image "
            "hashing and cannot be checked against the installed binary",
        )

    actual = hashlib.sha256(dest_exe.read_bytes()).hexdigest()
    if actual != recorded:
        return ProvenanceVerdict(
            "mismatch",
            f"installed binary {dest_exe} hashes to {actual}, but its "
            f"sidecar {provenance_path} records image_sha256={recorded}",
        )

    try:
        prebuilt = hashlib.sha256(_prebuilt_image_bytes()).hexdigest()
    except DoorInstallError as exc:
        return ProvenanceVerdict(
            "unverifiable",
            f"{dest_exe} matches its recorded image_sha256, but currency "
            f"could not be checked: {exc}",
        )
    if actual != prebuilt:
        return ProvenanceVerdict(
            "stale",
            f"installed binary {dest_exe} agrees with its own sidecar "
            f"({actual}) but is not the current prebuilt "
            f"{_PREBUILT_DOOR_EXE} ({prebuilt}) -- the install is a build "
            "behind; re-run the installer from a stamped engine root",
        )

    return ProvenanceVerdict(
        "ok", f"{dest_exe} matches its recorded image_sha256 and the current prebuilt"
    )


class ImageCurrencyAudit(NamedTuple):
    """Per-slot verdict from `audit_installed_image_currency()`. Each field
    is a sorted list of installed NAMES (not paths) -- `current` carries the
    prebuilt's bytes, `stale` carries some other build's.

    A slot with no file at all is in NEITHER list. It was a third field
    once; nothing downstream ever read it, and an absent slot is already
    reported by `settings_home_report.check_settings_home`'s own
    forwarder-missing leg, which reads the artifact this audit does not
    look at. A field kept because it completed a taxonomy, rather than
    because a caller asked, is dead structure."""

    current: "list[str]"
    stale: "list[str]"


def audit_installed_image_currency(
    bin_dst: Path, names: "Iterable[str]"
) -> ImageCurrencyAudit:
    """Classifies every argv[0]-dispatched door image slot in `bin_dst`
    against the committed prebuilt -- the currency oracle
    `install_named_forwarder` has no counterpart for, and the one a
    presence check cannot stand in for.

    WHY PRESENCE CANNOT STAND IN. Under ONE ENTRYPOINT PER PLATFORM
    (`substrate._write_agent_helper_forwarders`) the image IS the only
    launcher a name gets, so "the slot is populated" is satisfied by an
    image from any build, including one predating the fix the name needs.
    A check whose success signal is satisfied by the failure it exists to
    catch is worse than no check. Counts and forensics for the 2026-09-01
    incident live once, in `tests/test_door_image_currency.py`'s module
    docstring.

    THE POPULATION IS DERIVED FROM `names`, NEVER FROM THE INSTALLER'S OWN
    MANIFEST. `_native-forwarder-manifest.json` is written BY the writer
    whose failure this audit exists to detect, so a manifest-driven audit
    reports nothing owed on precisely the box that owes everything. Callers
    pass the same derivation the writer consumes
    (`substrate._derive_agent_helper_target_map`), so a name the writer was
    asked to serve and did not is visible here.

    ANYTHING AT THE SLOT THAT IS NOT THE PREBUILT IS `stale`, INCLUDING A
    NON-DOOR FILE. There is no byte-marker that identifies a door build
    (checked: the image carries no version string), so this makes no
    attempt to guess door-shape. It does not need to: under ONE ENTRYPOINT
    PER PLATFORM the correct content of this slot is the current door and
    nothing else, so a foreign file there is a defect on the same terms as
    an old one. No static-bin-family exemption is offered or needed:
    `_derive_agent_helper_target_map` excludes the names those families own
    (`_AGENT_HELPER_RESERVED_NAMES`), so they never reach `names` from the
    only caller that exists.

    ONE READ PER INODE, NOT ONE PER NAME. The slots are hardlinks to a
    single image by construction (`install_named_forwarder`'s spike
    verdict), so hashing per name would read the same 176 KiB 373 times on
    a box whose load norm is 50-70 concurrent sessions. Results are
    memoised on `(st_dev, st_ino)` and a size mismatch short-circuits
    before any read: the full 374-slot audit costs one prebuilt read plus
    one image read.
    """
    bin_dst = Path(bin_dst)
    prebuilt_bytes = _prebuilt_image_bytes()
    prebuilt_size = len(prebuilt_bytes)

    current: "list[str]" = []
    stale: "list[str]" = []
    seen: "dict[tuple, bool]" = {}

    for name in sorted(set(names)):
        dest = named_forwarder_path(bin_dst, name)
        try:
            st = dest.stat()
        except OSError:
            continue
        if st.st_size != prebuilt_size:
            stale.append(name)
            continue
        key = (st.st_dev, st.st_ino)
        if key not in seen:
            try:
                seen[key] = dest.read_bytes() == prebuilt_bytes
            except OSError:
                seen[key] = False
        (current if seen[key] else stale).append(name)

    return ImageCurrencyAudit(current=current, stale=stale)


def claim_bare_name(bin_dst: Path) -> "list[Path]":
    """Public entry point for the shadow-sibling removal -- the door's
    counterpart to installing it.

    NOT called from inside `install_door()` -- deliberately. `install_door`
    is the WINDOWS install path only; on POSIX, `scripts/setup.py ::
    install_warm_door` produces the door via
    `door_install_posix_build.build_or_advise` and never calls
    `install_door` at all, so a removal hung off that one function would be
    dead code on every Mac and Linux box (measured: a full `scripts/setup.py
    --i-am-agent` run landed the door and left `coordinator-invoke.ps1` in
    place, 2026-08-22). Both platforms land the door at the identical
    `bin_dst / DOOR_INSTALLED_NAME` path, so ONE caller -- `install_warm_door`,
    once `dest` is established by either of its branches -- calls this
    single function for both, rather than duplicating the removal call into
    every producer of a door binary.

    Idempotent and non-raising -- see `_remove_shadowing_forwarder_siblings`
    (the implementation this wraps) for why. Must NOT be called on a
    degraded/ADVISORY path where no door actually landed, or it would strip
    the fallback forwarder the box is relying on instead of the door; every
    caller gates on that already (a degraded `build_or_advise`/failed
    `install_door` returns before this is ever reached).
    """
    return _remove_shadowing_forwarder_siblings(bin_dst)


def _remove_shadowing_forwarder_siblings(bin_dst: Path) -> "list[Path]":
    """Deletes the `install_bin_forwarders`-written siblings of
    `BARE_FORWARDER_NAME` that would WIN bare-name resolution over the door
    once it is installed at the same path -- today just
    `coordinator-invoke.ps1` (PowerShell ranks a same-directory `.ps1`
    above a same-directory `.exe`; see the module docstring's Windows
    paragraph). `coordinator-invoke.cmd` is deliberately left alone: PATHEXT
    ranks `.EXE` above `.CMD`, so it is unreachable by a bare-name lookup
    once the door's `.exe`/extensionless binary sits beside it, dead weight
    rather than a live shadow.

    Private implementation -- `claim_bare_name` above is the public entry
    point every real caller uses (`install_door()` itself no longer calls
    this internally; see that function's own docstring for why keeping the
    invocation OUT of `install_door` is load-bearing, not incidental).
    Non-raising: a sibling that is already absent is simply skipped, and an
    `OSError` on the unlink itself (permissions, a concurrent remover) is
    swallowed and reported rather than raised -- a caller reaches this only
    after a door is already correctly installed, and a failure to also
    clear a shadow must not un-succeed that install.

    Returns the list of paths actually removed (possibly empty).
    """
    bin_dst = Path(bin_dst)
    removed: "list[Path]" = []
    for suffix in _SHADOWING_SIBLING_SUFFIXES:
        candidate = bin_dst / (BARE_FORWARDER_NAME + suffix)
        try:
            if candidate.exists():
                candidate.unlink()
                removed.append(candidate)
        except OSError as exc:
            print(
                f"[door-install] could not remove shadowing sibling {candidate}: {exc}",
                file=sys.stderr,
            )
    return removed


def install_door(bin_dst: Path, engine_root: Path, *, check_only: bool = False) -> Path:
    """Installs the door at `bin_dst / DOOR_INSTALLED_NAME` plus its
    engine-root sidecar. Prefers the committed prebuilt binary (see
    module docstring); falls back to compiling from source only when no
    prebuilt is present.

    `engine_root` must carry a valid `coordinator_core/_engine_stamp`
    (`warm.engine_root.is_engine_root`) -- refuses otherwise, mirroring
    `door_build.build()`'s own refusal, so this function can never point
    a fresh install at an unstamped (never warm-capable) tree.

    `check_only=True` verifies without writing: both the exe and its
    sidecar must already exist at `bin_dst`, mirroring the `check_only`
    convention `substrate.py`'s own forwarder writers use. Does not
    verify the exe's CONTENT against the prebuilt (that is
    `rebuild_and_verify_prebuilt()`'s job, and is deliberately not paid
    on every check-only call) -- only presence.

    On a REAL install (`check_only=False`), also removes the
    `install_bin_forwarders`-written siblings that would shadow the door at
    bare-name resolution -- see `_remove_shadowing_forwarder_siblings` and
    the module docstring's Windows paragraph. `door_uninstall.uninstall_door`
    is this removal's counterpart: it re-emits a fallback forwarder at
    `BARE_FORWARDER_NAME` when it removes a door that claimed that name, so
    uninstalling never leaves the box with no `coordinator-invoke` at all.

    Also runs `_sweep_displaced_images(bin_dst)` before returning -- the
    reaper for `.stale-` siblings `_replace_possibly_running_image` and
    `install_named_forwarder` leave behind when a displaced image was still
    mapped at the moment they tried to clean up after themselves. Never run
    on the `check_only` path: that flag's contract is to mutate nothing.

    Returns the path to the installed (or verified) executable.
    """
    engine_root = Path(engine_root)
    if not is_engine_root(engine_root):
        raise DoorInstallError(
            f"door_install: {engine_root} is not a valid engine root "
            "(no readable, non-empty coordinator_core/_engine_stamp)"
        )

    bin_dst = Path(bin_dst)
    dest_exe = bin_dst / DOOR_INSTALLED_NAME
    dest_sidecar = bin_dst / door_build.SIDECAR_FILENAME

    if check_only:
        if dest_exe.exists() and dest_sidecar.exists():
            print(f"[door-install] check: {dest_exe} present (no-op)")
            return dest_exe
        raise DoorInstallError(
            f"door_install: check failed -- {dest_exe} or {dest_sidecar} missing "
            "(would install)"
        )

    bin_dst.mkdir(parents=True, exist_ok=True)

    dest_provenance = installed_provenance_path(bin_dst)

    if _PREBUILT_DOOR_EXE.exists():
        _replace_possibly_running_image(_PREBUILT_DOOR_EXE, dest_exe)
        print(f"[door-install] copied prebuilt {_PREBUILT_DOOR_EXE} -> {dest_exe}")
        if _PREBUILT_PROVENANCE.exists():
            shutil.copy2(_PREBUILT_PROVENANCE, dest_provenance)
        else:
            # A missing prebuilt sidecar next to a present prebuilt exe used
            # to be a SILENT skip while the exe copy above is unconditional
            # -- that asymmetry is exactly how a destination keeps a stale
            # record: the binary changes, nothing tells the sidecar to. A
            # record describing a different binary is worse than no record
            # at all, so any pre-existing destination sidecar is removed
            # rather than left to misdescribe the binary this call just
            # installed.
            print(
                f"[door-install] WARNING: no prebuilt provenance at "
                f"{_PREBUILT_PROVENANCE} -- installing without one",
                file=sys.stderr,
            )
            try:
                dest_provenance.unlink()
            except FileNotFoundError:
                pass
    else:
        door_build.build(engine_root, output=dest_exe)
        print(f"[door-install] no prebuilt found -- compiled fresh at {dest_exe}")

    if dest_provenance.exists():
        verdict = verify_installed_provenance(bin_dst)
        if verdict.status == "mismatch":
            raise DoorInstallError(
                "door_install: the committed prebuilt exe and its committed "
                f"provenance sidecar disagree with each other: {verdict.detail}"
            )
        if verdict.status == "unrecorded":
            print(f"[door-install] NOTE: {verdict.detail}")

    # `door_build.build()`'s own sidecar write (compiled-fresh branch)
    # already targets `dest_exe`'s directory, so this is only load-
    # bearing for the copied-prebuilt branch -- but calling it
    # unconditionally is simpler than branching and is idempotent
    # (last writer wins, and both writers agree on the same content for
    # the same `engine_root`).
    door_build.write_sidecar(dest_exe, engine_root)

    swept = _sweep_displaced_images(bin_dst)
    if swept:
        print(f"[door-install] swept {len(swept)} stale displaced image(s) from {bin_dst}")

    return dest_exe


def named_forwarder_path(bin_dst: Path, name: str) -> Path:
    """The install path a per-name native door forwarder image (C5,
    docs/plans/2026-08-26-every-forwarder-that-can-reach-the-door-does.md)
    lands at: `name` plus the platform-appropriate suffix -- `.exe` on
    Windows (PATHEXT ranks `.EXE` ahead of `.CMD`, so this wins bare-name
    resolution over any pre-existing `.cmd` forwarder for the same name
    without that forwarder needing to be touched at all -- it becomes
    unreachable dead weight, not a live shadow, exactly as
    `_remove_shadowing_forwarder_siblings`'s own docstring already argues
    for `DOOR_INSTALLED_NAME` itself), no suffix on POSIX (there is no
    PATHEXT-style ranking there -- the bare name IS the file name, and on
    POSIX this path is the SAME path the Python agent-helper forwarder for
    `name` already occupies, so installing here intentionally overwrites
    it rather than colliding with it). Mirrors `DOOR_INSTALLED_NAME`'s own
    platform branch exactly, generalized from a single literal to an
    arbitrary `name`."""
    suffix = ".exe" if sys.platform == "win32" else ""
    return Path(bin_dst) / f"{name}{suffix}"


def install_named_forwarder(
    bin_dst: Path, engine_root: Path, name: str, *, check_only: bool = False
) -> Path:
    """Installs a per-name native door forwarder image at
    `named_forwarder_path(bin_dst, name)` -- additive to `install_door()`'s
    single-name `DOOR_INSTALLED_NAME` surface, never replacing it (C5).

    HARDLINKS OR COPIES (spike verdict 2026-08-27, f4e754bad): 393
    hardlinks measured at 179ms process time and ~0 real disk (extents
    shared) against 344ms/65.6MiB real for 393 copies, on a 171.0 KiB
    image. Hardlinks are SAME-VOLUME ONLY (`WinError 17` confirmed linking
    `X:` to `C:`), so this function first ensures the door is installed at
    `bin_dst / DOOR_INSTALLED_NAME` via `install_door()` (idempotent -- a
    call where it is already present and current just re-copies the same
    171.0 KiB, never a correctness issue) and links the named forwarder to
    THAT sibling, never straight out of the repo -- the install chain
    already copies the door into `bin_dst`, so the same-volume constraint
    is satisfied by construction. Falls back to `shutil.copy2` if the link
    itself fails for any reason (e.g. a filesystem without hardlink
    support) -- correctness over the perf win.

    `check_only=True` verifies presence only, mirroring `install_door`'s
    own `check_only` convention -- never re-derives content equality, and
    never calls `install_door` (no mutation permitted in check-only mode).
    """
    dest = named_forwarder_path(bin_dst, name)

    if check_only:
        if dest.exists():
            return dest
        raise DoorInstallError(
            f"door_install: named forwarder check failed -- {dest} missing (would install)"
        )

    source = install_door(bin_dst, engine_root, check_only=False)

    # SELF-COLLISION GUARD. `coordinator-invoke` is itself a member of the
    # door-eligible population, and for that one name `named_forwarder_path`
    # resolves to exactly the path `install_door` just wrote -- the canonical
    # door. Without this branch the unlink below DELETES `source`, and both
    # `os.link` and its `shutil.copy2` fallback then raise `FileNotFoundError`
    # out of this function. Nothing in `substrate._write_agent_helper_
    # forwarders`'s per-name loop catches it, so a real install run reaching
    # this name in sorted() order aborts the WHOLE run -- every name after it
    # alphabetically never gets written. It is not a missing-coverage bug for
    # one name, it is an install-crashing one for the tail of the corpus.
    # Reproduced against a real engine-stamped root: 381/382 names install
    # clean, `coordinator-invoke` raises uncaught
    # (state/audits/2026-08-27-native-launcher-coverage.md, finding F0).
    #
    # The canonical door IS the correct artifact at this path, so the right
    # answer is to return it, not to link it to itself.
    # Compared normcase/abspath rather than by `Path.__eq__`, which is
    # case-sensitive even on Windows and would miss a `bin_dst` spelled with
    # different case than `install_door` returned.
    if os.path.normcase(os.path.abspath(dest)) == os.path.normcase(os.path.abspath(source)):
        return dest

    displaced: Optional[Path] = None
    if dest.exists() or dest.is_symlink():
        try:
            dest.unlink()
        except OSError:
            displaced = dest.with_name(f"{dest.name}.stale-{os.getpid()}-{int(time.time())}")
            try:
                os.replace(dest, displaced)
            except OSError:
                displaced = None

    try:
        os.link(source, dest)
    except OSError:
        shutil.copy2(source, dest)

    if displaced is not None:
        try:
            displaced.unlink()
        except OSError:
            print(
                f"[door-install] could not remove displaced stale image {displaced} "
                f"(likely still mapped by a running process) -- left for a later "
                f"sweep; {dest.name} is current",
                file=sys.stderr,
            )

    return dest


def _replace_possibly_running_image(source: Path, dest: Path) -> None:
    """Copies `source` over `dest` even when `dest` is a door/forwarder image
    a running session currently has mapped open.

    THE LOCK IS THE NORMAL CONDITION, NOT AN EDGE CASE. Measured live
    2026-08-30: a full `install-substrate` run died with `PermissionError:
    [WinError 32] ... being used by another process` on a plain
    `shutil.copy2(_PREBUILT_DOOR_EXE, dest_exe)`, because every session on
    the box reaches the engine THROUGH these door images and the load norm
    is 50-70 concurrent sessions -- a door invocation is in flight
    essentially always. There is no quiet moment to wait for, so a retry
    loop cannot fix this; the failure mode is structural, not transient.

    RENAME IS PERMITTED WHERE OVERWRITE IS NOT. Windows refuses to open a
    mapped executable for writing or deletion, but permits renaming it --
    the directory entry moves while an already-mapped process keeps
    executing the same file via its already-open handle. So: rename the old
    image aside to a `.stale-<pid>-<timestamp>` sibling (freeing the
    original path), copy the new image in at that now-free path, then
    best-effort clean up the displaced file.

    A failed install must never leave the box with no door -- `install_door`'s
    own docstring already states this invariant. If the copy to the freed
    path fails for any reason, the displaced original is renamed straight
    back before the exception propagates.

    The final `unlink()` of the displaced file is EXPECTED to fail while a
    process still executes the old image -- that failure is swallowed and
    reported, not raised: `dest` already carries the new content by that
    point, and leaving a harmless `.stale-` residue for a later sweep is the
    correct outcome of installing over a live box, not a defect to surface
    as one.

    THE CHEAPEST CORRECT INSTALL IS THE ONE THAT DOES NOT WRITE. When `dest`
    already carries `source`'s bytes, the rename-aside path above is not
    merely wasted work -- it is actively counterproductive: it displaces a
    perfectly current image, cannot unlink the displacement while it stays
    mapped (the load norm, per this docstring's own opening paragraph), and
    so leaves `.stale-` residue on exactly the runs that had nothing to
    install. A content check up front, before any write is attempted, means
    a no-op install neither writes through 375 hardlinks nor manufactures
    residue it can never clean up -- which is what makes re-running the
    installer on a busy box safe and near-free rather than a source of
    accumulating churn.
    """
    if dest.exists():
        try:
            unchanged = filecmp.cmp(source, dest, shallow=False)
        except OSError:
            unchanged = False
        if unchanged:
            return

    try:
        shutil.copy2(source, dest)
        return
    except PermissionError:
        if not dest.exists():
            raise

    displaced = dest.with_name(f"{dest.name}.stale-{os.getpid()}-{int(time.time())}")
    os.replace(dest, displaced)
    try:
        shutil.copy2(source, dest)
    except BaseException:
        os.replace(displaced, dest)
        raise

    try:
        displaced.unlink()
    except OSError:
        print(
            f"[door-install] could not remove displaced stale image {displaced} "
            f"(likely still mapped by a running process) -- left for a later "
            f"sweep; {dest.name} is current",
            file=sys.stderr,
        )


def _sweep_displaced_images(bin_dst: Path) -> "list[Path]":
    """Best-effort removal of `*.stale-*` siblings left by
    `_replace_possibly_running_image` and `install_named_forwarder`'s own
    displaced-image handling -- the sweep those functions' docstrings
    promise and that no caller previously ran.

    A DISPLACED IMAGE STILL MAPPED BY A LIVE PROCESS IS NOT A SWEEP FAILURE.
    Skipping it silently is the correct behaviour, not a degraded one: the
    process holding it will eventually exit, at which point the SAME file
    becomes reapable, and the next install's call to this function is the
    sweep for it -- there is no moment this pass could wait for that a retry
    loop would reach any sooner, and a box with 50-70 concurrent sessions
    means some fraction of `.stale-` siblings are essentially always mapped
    by something. That is why this is a single best-effort pass over
    whatever is unlinkable right now, not a loop that retries what is not.

    Non-raising, per-entry: one `.stale-` sibling still in use is skipped
    without raising or being reported, and the sweep continues to the rest
    -- mirrors `_remove_shadowing_forwarder_siblings`'s posture (a cleanup
    step's own failure must never un-succeed the install it follows).

    Returns the paths actually removed (possibly empty).
    """
    bin_dst = Path(bin_dst)
    removed: "list[Path]" = []
    if not bin_dst.is_dir():
        return removed
    for candidate in bin_dst.glob("*.stale-*"):
        try:
            candidate.unlink()
            removed.append(candidate)
        except OSError:
            continue
    return removed


def engine_carries_entrypoint_script(engine_root: Path, name: str) -> bool:
    """True when `engine_root` carries the `coordinator/bin/<name>.py` this
    name's door image would dial.

    THE ORACLE HAS TO BE THE ENGINE, NOT THIS REPO, and that is the whole
    point of this function. A door image resolves its own basename and sends
    it as the request's `entrypoint`; the server resolves that name through
    `ops/invoke_from_argv.py :: _resolve_entrypoint_script`, which looks for
    `<engine_root>/coordinator/bin/<name>.py` and nothing else. The
    door-eligible roster, by contrast, is derived from the GENERATOR's own
    `coordinator/bin/` -- and the two namespaces are not the same one:

      - EXCLUSION. A publisher-side CLI is deliberately not carried into the
        published engine at all. `publish`, `percolate-push`,
        `percolate-round` and `coordinator-publish` are the sharp case:
        they are the chain that produces the mirror, so they do not ship in
        it.
      - RENAME. `setup/percolate-hooks/percolate-store.yaml`'s `substitute`
        section rewrites repo-identifying names at publish time, so
        `check-claude-klabauter-doctor-sentinel.sh` lands as
        `check-claude-klabauter-doctor-sentinel.py`. The script IS published;
        the NAME the door would ask for is not.

    Measured 2026-08-29: 14 of 365 door-eligible names had no script under
    their own name in the engine their image dials.

    WHAT THAT COST, and why this is not a cosmetic roster tidy. Such a name
    has NO working leg. Warm, `_resolve_entrypoint_script` raises a plain
    `ValueError` -> -32603, which `door_core.c :: is_provably_undispatched`
    correctly refuses to treat as proof of non-dispatch, so the door emits
    -32004 and the invocation FAILS rather than degrading. Cold, `door.c ::
    fall_through` spawns `<engine_root>\\coordinator\\bin\\<name>.py` -- the
    same absent path. And on Windows the `.exe` outranks the `.cmd` in
    PATHEXT, so the broken image SHADOWS the `publish.cmd` forwarder that
    does work (it resolves claude-klabauter's own tree via `_resolve_claude_klabauter.py`). The
    net effect is a name that worked before it was cut over and fails after.

    Checked at INSTALL time, against the root actually being installed from,
    rather than modelled in the census that builds the roster. The publish
    transform is a moving target -- an exclusion list plus a substitution
    table, both editable in the publishing repo -- and any static model of it
    in the generator is a second source of truth that goes stale silently.
    The engine on disk cannot.
    """
    return (Path(engine_root) / "coordinator" / "bin" / f"{name}.py").is_file()


#: The generator's own `coordinator/bin/`, resolved the same way
#: `forwarder_door_census._BIN_DIR` resolves it -- the tree the installed NAME
#: comes from, as against the engine tree the image dials.
_GENERATOR_BIN_DIR = Path(__file__).resolve().parents[2] / "coordinator" / "bin"


def launcher_is_installable(engine_root: Path, name: str) -> bool:
    """False only for a name that HAS a `.py` CLI here and does NOT have one in
    `engine_root` -- the publish-excluded and publish-renamed set.

    NARROWER THAN `engine_carries_entrypoint_script`, and the narrowing is the
    correction that matters. "The engine cannot resolve this name" is true of
    two populations that want opposite treatment:

      1. THE EXCLUDED AND THE RENAMED. `coordinator/bin/<name>.py` exists HERE
         and not in the engine -- the publisher chain that produces the mirror
         (`publish`, `percolate-push`, `percolate-round`,
         `coordinator-publish`), claude-klabauter's own migrations and probes, and the
         names `percolate-store.yaml`'s `substitute` section rewrites. These
         get no launcher: they are repo-side tools, run from their own
         checkout, and PM-ruled 2026-08-29 ("we shouldn't need a publish.exe
         nor a publish.cmd").
      2. THE EXTENSIONLESS TWELVE. `chunk-commits`, `static-check`,
         `with-suite-mutex`, `coordinator-precommit-foreign-platform-check`
         and their siblings exist as extensionless files with NO `.py` twin in
         EITHER tree, so `_resolve_entrypoint_script` (which hardcodes
         `<name>.py`) has never resolved them -- recorded in
         `warm_entrypoint_allowlist.json`'s own `$comment` as a known,
         separate defect. They are nonetheless live PATH tools: the git hooks
         this install writes invoke them by name. Stripping their launchers
         breaks committing on the box.

    A predicate keyed only on the engine cannot tell those apart, and the
    version that could not was measured doing real damage: it queued all 26
    for removal, hook CLIs included. Requiring the `.py` to exist HERE is what
    separates "deliberately not shipped" from "never resolvable in the first
    place" -- the second is someone else's open row, not this function's to
    act on.

    A THIRD population reads as case 2 above but is neither live nor
    someone else's open row: a KILLED op (K-068) whose `.py` was deleted
    from both trees returns True here, same as the extensionless twelve --
    this predicate cannot distinguish "never had one" from "used to have
    one and was deliberately killed". That is correct for THIS function
    (a killed op's image is additive-installer-invisible either way, since
    this predicate only gates the per-name install loop's write/keep
    decision) but means a killed op's stale image is never reaped through
    this path. `_sweep_orphaned_agent_helpers`'s killed-op-name
    identification (C1, `_KILLED_OP_ORPHAN_NAMES` in `substrate.py`) is the
    roster- and predicate-independent mechanism that actually retires it --
    do not expect this predicate to also do that job.
    """
    if not (_GENERATOR_BIN_DIR / f"{name}.py").is_file():
        return True
    return engine_carries_entrypoint_script(engine_root, name)


def remove_stale_named_forwarder(bin_dst: Path, name: str) -> Optional[Path]:
    """Removes a previously-installed native image for `name`, returning the
    path removed or None.

    The cleanup half of `engine_carries_entrypoint_script`: a name cut over
    by an earlier install, and only later found to have no script in the
    engine it dials, leaves a broken `.exe` behind that outranks the working
    Python pair on PATH. Re-running the installer has to take it back out,
    or the fix never reaches a box that already ran the broken cutover.

    NEVER touches the canonical door itself. `DOOR_INSTALLED_NAME` resolves
    here to the same path `install_door` writes, and removing it would strip
    every session on the box of its engine entrypoint -- the same
    self-collision `install_named_forwarder` guards against, in the opposite
    direction.
    """
    dest = named_forwarder_path(bin_dst, name)
    canonical = bin_dst / DOOR_INSTALLED_NAME
    if os.path.normcase(os.path.abspath(dest)) == os.path.normcase(os.path.abspath(canonical)):
        return None
    if not dest.exists():
        return None
    try:
        dest.unlink()
    except OSError:
        return None
    return dest


def remove_shadowing_ps1_sibling(bin_dst: Path, name: str) -> Optional[Path]:
    """Removes `name + ".ps1"` at `bin_dst` if present -- the per-name
    counterpart to `_remove_shadowing_forwarder_siblings` for an arbitrary
    native-forwarder `name` rather than only `BARE_FORWARDER_NAME`. Same
    reasoning as that function's own docstring: PowerShell ranks a
    same-directory `.ps1` ABOVE a same-directory `.exe`, so a leftover
    `.ps1` for a cut-over name would silently shadow its native forwarder
    on PowerShell alone. `.cmd` needs no matching removal -- PATHEXT ranks
    `.EXE` ahead of `.CMD`, so a `.cmd` sibling is unreachable dead weight,
    not a live shadow, once the native image exists (mirrors
    `_remove_shadowing_forwarder_siblings`'s own `.cmd` paragraph).

    Non-raising, idempotent, best-effort: returns the removed path, or
    `None` if there was nothing to remove or the removal failed -- matches
    `_remove_shadowing_forwarder_siblings`'s own posture (a failure to
    clear a shadow must not un-succeed the forwarder install it follows).
    """
    candidate = Path(bin_dst) / f"{name}.ps1"
    try:
        if candidate.exists():
            candidate.unlink()
            return candidate
    except OSError as exc:
        print(
            f"[door-install] could not remove shadowing sibling {candidate}: {exc}",
            file=sys.stderr,
        )
    return None


def remove_superseded_python_forwarders(
    bin_dst: Path, name: str, *, exempt_names: "frozenset[str]" = frozenset()
) -> "list[Path]":
    """Removes the Python forwarder pair a cut-over `name` no longer needs
    (C5 kill, PM ruling 2026-08-27). Once a native door image exists for
    `name`, its Python-trampoline forwarders are not merely outranked, they
    are WRONG IF REACHED: the `.cmd` half execs the co-located
    extensionless sibling through python, and on Windows that sibling is
    the door's native binary post-cutover, not the trampoline the `.cmd`
    was generated to invoke. Keeping them relied on PATHEXT ranking AND on
    install ordering to hold a known-wrong body unreachable -- neither is
    an invariant, and at 382 eligible names that is a large population of
    wrong-bodied files kept harmless by an incidental property. This
    removes the reliance rather than documenting it.

    PLATFORM ASYMMETRY, AND WHY THE BARE NAME IS NOT UNIFORMLY REMOVABLE.
    On Windows the native image is `name.exe`, so the bare extensionless
    `name` and `name.cmd` are both genuinely superseded and both go. On
    POSIX `named_forwarder_path` puts the native image AT the bare `name`
    path itself -- the Python forwarder was already overwritten in place by
    the native install, so the bare name there IS the live door image, and
    removing it would uninstall the very forwarder this call follows. Only
    a stray `.cmd` (never generated on POSIX, but cheap to sweep if an
    earlier cross-platform install left one) is removable there.

    `exempt_names` -- STATIC-FAMILY OWNERSHIP, this function's own contract
    (it is the function that deletes files; it does not import
    `coordinator_core.install.substrate` to look up family membership
    itself, which would create a dependency this module does not otherwise
    have). A name a static bin family owns (e.g. `claude-home`, written by
    `ch_family` before the agent-helper loop runs) has a bare/`.cmd` pair
    that is NOT this kill's superseded Python trampoline -- it is that
    family's own file, and deleting it strips the family of its install.
    Defaults to the empty set so every existing caller is unaffected. A name
    in this set is left untouched entirely -- neither candidate below is
    even considered for it. `substrate._cut_over_to_native_door`, the sole
    installer-side caller, does not pass `static_family_names` here: a
    static-owned name never reaches this call from there (it returns
    earlier via `_STATIC_FAMILY_ALREADY_SERVED`), so the parameter is
    exercised directly by this module's own tests instead.

    Non-raising, idempotent, best-effort: returns the paths actually
    removed. Mirrors `remove_shadowing_ps1_sibling`'s posture -- a failure
    to clear a superseded forwarder must not un-succeed the native install
    it follows, because the native image is already on disk and already
    winning bare-name resolution by that point.

    Negative-spec:
      - Does NOT touch `name + ".ps1"` -- that is
        `remove_shadowing_ps1_sibling`'s job, run for a shadowing rather
        than a superseded reason.
      - Does NOT run for a name whose native install did not succeed. The
        caller gates on that: a doorless root keeps its Python pair, which
        IS the doorless-fallback path and is not collateral of this kill.
      - Does NOT remove anything for a name in `exempt_names` -- that name's
        bare/`.cmd` files belong to a static bin family, not to this kill.
    """
    if name in exempt_names:
        return []
    removed = []
    candidates = [Path(bin_dst) / f"{name}.cmd"]
    if sys.platform == "win32":
        candidates.append(Path(bin_dst) / name)
    for candidate in candidates:
        try:
            if candidate.exists():
                candidate.unlink()
                removed.append(candidate)
        except OSError as exc:
            print(
                f"[door-install] could not remove superseded forwarder {candidate}: {exc}",
                file=sys.stderr,
            )
    return removed


def main(argv: Optional[list] = None) -> int:
    parser = argparse.ArgumentParser(
        description=(
            f"Install the native warm-engine door ({DOOR_INSTALLED_NAME}) "
            "into a bin directory, plus its engine-root sidecar. NEVER "
            "resolves the real settings-home itself -- pass --bin-dst "
            "explicitly, and prefer a scratch directory unless you have "
            "PM sign-off to touch the live one."
        )
    )
    parser.add_argument("--bin-dst", type=Path, required=True, help="Destination bin directory.")
    parser.add_argument("--engine-root", type=Path, required=True, help="Published engine root.")
    parser.add_argument("--check-only", action="store_true")
    parser.add_argument(
        "--verify-reproducible", action="store_true",
        help="Also rebuild from source and hash-compare against the committed prebuilt.",
    )
    parser.add_argument(
        "--python", type=Path, default=None,
        help=(
            "Interpreter to bake into the REBUILD that --verify-reproducible "
            "hash-compares against (default: this interpreter). The committed "
            "binary bakes an absolute interpreter path, so a rebuild that bakes "
            "a different one differs in bytes for that reason alone -- pass the "
            "path the prebuilt was built with to compare like with like."
        ),
    )
    args = parser.parse_args(argv)

    if args.verify_reproducible:
        # `python_bin` is threaded through rather than left to default. Without
        # it this check reported MISMATCH on any machine whose `sys.executable`
        # basename differs from the one baked into the committed binary --
        # `python3.exe` here against a prebuilt built with `python.exe`, same
        # source, same compiler, different embedded string. That is a
        # verification gate nobody can pass, which is worse than no gate: it
        # fooled this workstream twice (see the door's own build lesson,
        # "check the invocation before the artifact") and a gate that always
        # cries wolf trains its readers to wave it through.
        ok = rebuild_and_verify_prebuilt(
            engine_root=args.engine_root, python_bin=args.python
        )
        print(f"[door-install] reproducibility check: {'MATCH' if ok else 'MISMATCH'}")
        if not ok:
            print(
                "[door-install] if the ONLY difference is the baked interpreter, "
                "re-run with --python pointing at the one the prebuilt was built "
                "with (read it out of the binary, or off door.exe.provenance.json's "
                "sibling build). A genuine source/binary divergence needs a rebuild.",
                file=sys.stderr,
            )
            return 1

    try:
        dest = install_door(args.bin_dst, args.engine_root, check_only=args.check_only)
    except DoorInstallError as exc:
        print(f"[door-install] {exc}", file=sys.stderr)
        return 1
    print(f"[door-install] installed at {dest}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
