"""coordinator_core.install.door_install -- installs the native warm-engine
door as the on-PATH `coordinator-invoke` entrypoint.

Spec backlink: state/handoffs/2026-08-21_103635_reaching-the-warm-engine.md

WHY A DEDICATED STEP, NOT THE GENERIC `coordinator/bin/` SCAN. The
existing `coordinator-invoke.cmd` + extensionless Unix-half forwarder pair
in settings-home `bin/` is auto-generated by `substrate.py ::
_derive_agent_helper_target_map` scanning `coordinator/bin/` for Python-
source CLIs and writing a matching launcher for each. That scan assumes
its target is source Python it can `exec_cli()` into; `.exe` is not among
`_AGENT_HELPER_DATA_SUFFIXES`'s exclusions, so a raw compiled `door.exe`
dropped into `coordinator/bin/` would be MIS-processed by that machinery
rather than skipped, not correctly installed by it. The door needs its
own step.

WHY `coordinator-invoke.exe`, SPECIFICALLY, WINS THE BARE NAME. Verified
live on this box (2026-08-21), not assumed:

  - PATHEXT here is `.COM;.EXE;.BAT;.CMD;...` -- `.EXE` outranks `.CMD`.
    Confirmed BOTH cmd.exe and PowerShell resolve a bare name to a same-
    directory `.exe` over a `.cmd`/extensionless sibling (isolated test,
    temp dir, PATH-prepended only for that one call).
  - PowerShell's resolution ranks a `.ps1` sibling ABOVE `.exe` if one
    exists (matches `coordinator-invoke.cmd`'s own header warning) --
    settings-home `bin/` currently carries no `coordinator-invoke.ps1`,
    so this is a live constraint to keep true, not a present problem.
  - `~/.coordinator-claude-settings/bin` sits EARLIER on PATH than
    `<interpreter>/Scripts`, where the pip/editable-install
    `coordinator-invoke.exe` console-script entrypoint already lives
    (`docs/install/agent-install-manifest.json`'s own
    `coordinator_invoke_console_script` prerequisite entry) -- so
    settings-home `bin/` is the correct install target: directory order
    on PATH decides before same-directory PATHEXT ranking ever applies.

NOT THE INTERACTIVE LAUNCH CHAIN. `docs/reference/interactive-launch-
chain.md`'s "direct child" invariant is scoped to `claude.exe` itself
being spawned directly by the operator's shell. `coordinator-invoke`
dispatch is a separate subsystem -- a subprocess invoked from inside an
already-running session or a hook, never part of that chain. Confirmed by
the PM-adjacent EM on this dispatch; not re-litigated here.

WHY A PREBUILT BINARY, NOT COMPILING AT INSTALL TIME. No install box can
be assumed to carry clang or MSVC -- requiring one would make a C
compiler a NEW install-chain dependency for every coordinator install,
which is the exact class of problem `warm/door/build.py`'s own runtime-
sidecar revision existed to avoid for the ENGINE ROOT. `install_door()`
therefore prefers the committed `coordinator_core/warm/door/door.exe`,
falling back to compiling from source only when no prebuilt is present
(e.g. a from-scratch dev checkout that has never run the door build).

VERIFYING THE COMMITTED BINARY MATCHES ITS COMMITTED SOURCE. Two pieces,
per the PM's own ruling on this ("rebuild it yourself and see it work;
here is the source hash it came from" -- explicitly NOT bit-for-bit
determinism across different compilers/toolchains, which is out of
scope):

  1. `build.py :: write_provenance()` records, next to every compiled
     `door.exe`, a `<name>.provenance.json` carrying the SHA-256 of the
     `door.c` it was built from, plus the compiler and its version.
     Committed alongside the binary -- a mismatch between that recorded
     hash and the CURRENT `door.c` is detectable with one `sha256sum`,
     by anyone, without needing a compiler at all.
  2. `build.py :: verify_reproducible()` (also `build.py --verify`'s CLI
     mode; `rebuild_and_verify_prebuilt()` below is a same-named
     re-export) goes further: actually rebuilds from the current source
     and hash-compares the RESULT against the committed binary. This
     needs the SAME compiler installed, and relies on `_compile()`'s
     `/Brepro` linker flag (verified directly, 2026-08-21: without it,
     two back-to-back builds from byte-identical `door.c` differed in
     SHA-256; with it, they matched exactly).

Neither runs automatically on every install (that would reintroduce the
compiler dependency this whole design avoids) -- both are CI/audit-time
checks, not install-time ones.

`bin_dst` IS ALWAYS AN EXPLICIT PARAMETER, never resolved internally via
`coordinator_core._settings_home.settings_home()`. This is what makes
`install_door()` trivially testable against a scratch directory instead
of the live, ~40-concurrent-session settings-home -- see this module's
own tests. Wiring a call to this function into substrate.py's real
install flow (passing the REAL `settings_home_path / "bin"`) is a
separate, deliberately-deferred decision: this module only builds the
capability.
"""

from __future__ import annotations

import argparse
import shutil
import sys
from pathlib import Path
from typing import Optional

from coordinator_core.warm.door import build as door_build
from coordinator_core.warm.engine_root import is_engine_root

__all__ = [
    "DOOR_INSTALLED_NAME",
    "install_door",
    "rebuild_and_verify_prebuilt",
]

DOOR_INSTALLED_NAME = "coordinator-invoke.exe"

_DOOR_DIR = Path(__file__).resolve().parents[1] / "warm" / "door"
_PREBUILT_DOOR_EXE = _DOOR_DIR / "door.exe"
_PREBUILT_PROVENANCE = _DOOR_DIR / "door.exe.provenance.json"


class DoorInstallError(RuntimeError):
    """Raised by `install_door()` on a fatal precondition -- an invalid
    `engine_root`, or (check-only mode) a stale/absent install."""


def rebuild_and_verify_prebuilt(
    *,
    engine_root: Path,
    python_bin: Optional[Path] = None,
    compiler: Optional[str] = None,
    prebuilt: Path = _PREBUILT_DOOR_EXE,
) -> bool:
    """Thin delegate to `door_build.verify_reproducible()` -- the single
    canonical implementation lives there (it is also `build.py --verify`'s
    own CLI mode) so this module does not carry a second copy of the
    rebuild-and-hash-compare logic to drift out of sync with it. Kept as
    a re-export here because `install_door()`'s own docstring and this
    module's callers reference it by this name.
    """
    return door_build.verify_reproducible(
        engine_root, python_bin=python_bin, compiler=compiler, prebuilt=prebuilt
    )


def install_door(bin_dst: Path, engine_root: Path, *, check_only: bool = False) -> Path:
    """Installs the door at `bin_dst / DOOR_INSTALLED_NAME` plus its
    engine-root sidecar. Prefers the committed prebuilt binary (see
    module docstring); falls back to compiling from source only when no
    prebuilt is present.

    `engine_root` must carry a valid `coordinator_core/_engine_stamp`
    (`warm.engine_root.is_engine_root`) -- refuses otherwise, mirroring
    `door_build.build()`'s own refusal, so this function can never point
    a fresh install at an unstamped (never warm-capable) tree.

    `check_only=True` verifies without writing: both the exe and its
    sidecar must already exist at `bin_dst`, mirroring the `check_only`
    convention `substrate.py`'s own forwarder writers use. Does not
    verify the exe's CONTENT against the prebuilt (that is
    `rebuild_and_verify_prebuilt()`'s job, and is deliberately not paid
    on every check-only call) -- only presence.

    Returns the path to the installed (or verified) executable.
    """
    engine_root = Path(engine_root)
    if not is_engine_root(engine_root):
        raise DoorInstallError(
            f"door_install: {engine_root} is not a valid engine root "
            "(no readable, non-empty coordinator_core/_engine_stamp)"
        )

    bin_dst = Path(bin_dst)
    dest_exe = bin_dst / DOOR_INSTALLED_NAME
    dest_sidecar = bin_dst / door_build.SIDECAR_FILENAME

    if check_only:
        if dest_exe.exists() and dest_sidecar.exists():
            print(f"[door-install] check: {dest_exe} present (no-op)")
            return dest_exe
        raise DoorInstallError(
            f"door_install: check failed -- {dest_exe} or {dest_sidecar} missing "
            "(would install)"
        )

    bin_dst.mkdir(parents=True, exist_ok=True)

    if _PREBUILT_DOOR_EXE.exists():
        shutil.copy2(_PREBUILT_DOOR_EXE, dest_exe)
        print(f"[door-install] copied prebuilt {_PREBUILT_DOOR_EXE} -> {dest_exe}")
        if _PREBUILT_PROVENANCE.exists():
            shutil.copy2(_PREBUILT_PROVENANCE, dest_exe.parent / (dest_exe.name + ".provenance.json"))
    else:
        door_build.build(engine_root, output=dest_exe)
        print(f"[door-install] no prebuilt found -- compiled fresh at {dest_exe}")

    # `door_build.build()`'s own sidecar write (compiled-fresh branch)
    # already targets `dest_exe`'s directory, so this is only load-
    # bearing for the copied-prebuilt branch -- but calling it
    # unconditionally is simpler than branching and is idempotent
    # (last writer wins, and both writers agree on the same content for
    # the same `engine_root`).
    door_build.write_sidecar(dest_exe, engine_root)

    return dest_exe


def main(argv: Optional[list] = None) -> int:
    parser = argparse.ArgumentParser(
        description=(
            "Install the native warm-engine door (coordinator-invoke.exe) "
            "into a bin directory, plus its engine-root sidecar. NEVER "
            "resolves the real settings-home itself -- pass --bin-dst "
            "explicitly, and prefer a scratch directory unless you have "
            "PM sign-off to touch the live one."
        )
    )
    parser.add_argument("--bin-dst", type=Path, required=True, help="Destination bin directory.")
    parser.add_argument("--engine-root", type=Path, required=True, help="Published engine root.")
    parser.add_argument("--check-only", action="store_true")
    parser.add_argument(
        "--verify-reproducible", action="store_true",
        help="Also rebuild from source and hash-compare against the committed prebuilt.",
    )
    parser.add_argument(
        "--python", type=Path, default=None,
        help=(
            "Interpreter to bake into the REBUILD that --verify-reproducible "
            "hash-compares against (default: this interpreter). The committed "
            "binary bakes an absolute interpreter path, so a rebuild that bakes "
            "a different one differs in bytes for that reason alone -- pass the "
            "path the prebuilt was built with to compare like with like."
        ),
    )
    args = parser.parse_args(argv)

    if args.verify_reproducible:
        # `python_bin` is threaded through rather than left to default. Without
        # it this check reported MISMATCH on any machine whose `sys.executable`
        # basename differs from the one baked into the committed binary --
        # `python3.exe` here against a prebuilt built with `python.exe`, same
        # source, same compiler, different embedded string. That is a
        # verification gate nobody can pass, which is worse than no gate: it
        # fooled this workstream twice (see the door's own build lesson,
        # "check the invocation before the artifact") and a gate that always
        # cries wolf trains its readers to wave it through.
        ok = rebuild_and_verify_prebuilt(
            engine_root=args.engine_root, python_bin=args.python
        )
        print(f"[door-install] reproducibility check: {'MATCH' if ok else 'MISMATCH'}")
        if not ok:
            print(
                "[door-install] if the ONLY difference is the baked interpreter, "
                "re-run with --python pointing at the one the prebuilt was built "
                "with (read it out of the binary, or off door.exe.provenance.json's "
                "sibling build). A genuine source/binary divergence needs a rebuild.",
                file=sys.stderr,
            )
            return 1

    try:
        dest = install_door(args.bin_dst, args.engine_root, check_only=args.check_only)
    except DoorInstallError as exc:
        print(f"[door-install] {exc}", file=sys.stderr)
        return 1
    print(f"[door-install] installed at {dest}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
